#!/bin/bash
# regen_b26.sh -- regenerate lean/Jacobian/B26.lean and lean/Jacobian/B26/*.lean from scratch and compare.
# Needs Singular (4.3.2 gives byte-identical cofactors) and Python 3 with sympy.  Takes well under a minute.
# The Lean build itself: from lean/, `LEAN_NUM_THREADS=1 lake build Jacobian.B26` (about 8 min; one module at a time
# needs at most about 3.8 GB, for M5T; see README.md).
set -u
cd "$(dirname "$0")" || exit 1
LEAN_DIR=../../../lean/Jacobian
Singular -q m5_ideal_equality.sing | tail -3        # writes lift_S_to_J.txt, lift_J_to_S.txt (in-ring checks inside)
Singular -q m3_ideal_equality.sing | tail -1        # writes m3_lift_S_to_J.txt, m3_lift_J_to_S.txt
python3 gen_b26_lean.py ../m5_b2_6_eliminate_basis.sing B26.single.lean || exit 1
rm -rf regen_out && python3 split_b26.py B26.single.lean regen_out > /dev/null || exit 1
status=0
diff -r regen_out/Jacobian/B26 "$LEAN_DIR/B26" > /dev/null || { echo "DIFFERS: B26/"; status=1; }
cmp -s regen_out/Jacobian/B26.lean "$LEAN_DIR/B26.lean" || { echo "DIFFERS: B26.lean"; status=1; }
[ $status -eq 0 ] && echo "lean/Jacobian/B26.lean and lean/Jacobian/B26/ regenerated byte-identically"
rm -rf regen_out B26.single.lean __pycache__
exit $status
