"""gen_pilot_structured.py -- emit a Lean pilot module for one identity of the structured a_{8,16} route.

Input: the pickle written by g3_structured.py (integer polynomials; w is variable 0).  The identity is
    t = sum_j c_j * f_j + gq * R(w)
where the f_j are the substituted generators e_k o phi_<L (materialized; taken as hypotheses in the pilot) and gq is
minus the quotient by R.  It is checked by `decide +kernel` on `toPolyK` (Jacobian/ChartProof/Reflect.lean), with the
fact first in every product.
usage: python3 gen_pilot_structured.py PILOTS.pkl NAME OUT.lean
"""
import sys, pickle

pk, NAME, OUTF = sys.argv[1], sys.argv[2], sys.argv[3]
data = pickle.load(open(pk, "rb"))
VARS = data["vars"]
t, pairs, gq = data["pilots"][NAME]
assert t is not None and gq is not None and all(c is not None and f is not None for c, f in pairs)
used = set()
for p in [t, gq] + [c for c, _ in pairs] + [f for _, f in pairs]:
    for e in p:
        used.update(i for i, x in enumerate(e) if x)
order = [0] + sorted(i for i in used if i != 0)
vidx = {i: n for n, i in enumerate(order)}


def balanced(items, op):
    while len(items) > 1:
        items = [f"({op} {items[j]} {items[j+1]})" if j + 1 < len(items) else items[j] for j in range(0, len(items), 2)]
    return items[0]


def num(c):
    return f"(.num {c})" if c >= 0 else f"(.num ({c}))"


def expr(p):
    terms = []
    for e, c in sorted(p.items()):
        fs = [f"(.var {vidx[i]})" if x == 1 else f"(.pow (.var {vidx[i]}) {x})" for i, x in enumerate(e) if x]
        terms.append(num(c) if not fs else f"(.mul {num(c)} {balanced(fs, '.mul')})")
    return balanced(terms, ".add") if terms else "(.num 0)"


def mono_w(k):
    e = [0] * len(VARS); e[0] = k; return tuple(e)
Rw = {mono_w(5): 1, mono_w(4): -1, mono_w(3): 3, mono_w(2): 3, mono_w(0): 26}
nprod = sum(len(c) * len(f) for c, f in pairs) + 5 * len(gq)
maxdig = max(len(str(abs(c))) for p in [t, gq] + [c for c, _ in pairs] + [f for _, f in pairs] for c in p.values())
safe = NAME.replace(" ", "_")
L = ["import Jacobian.ChartProof.Reflect", "",
     f"/-! G3 pilot (generated by scripts/a816_lean_feasibility/gen_pilot_structured.py; not part of the Lean",
     f"build): structured a₈,₁₆ route, identity `{NAME}`;",
     f"{len(pairs)} facts, {nprod} monomial products, numerals up to {maxdig} digits. -/", "",
     "set_option maxHeartbeats 0", "set_option maxRecDepth 1000000", "",
     "namespace A816SPilot", "open Lean.Grind.CommRing BranchAb.ChartProof", "",
     "variable {α : Type*} [CommRing α]", "",
     "noncomputable def lcExprR (l : List (Expr × Expr)) : Expr :=",
     "  List.rec (.num 0) (fun p _ ih => .add (.mul p.2 p.1) ih) l", "",
     "theorem denote_lcExprR (ctx : Context α) (l : List (Expr × Expr)) (h : AllZero ctx l) :",
     "    (lcExprR l).denote ctx = 0 := by",
     "  induction l with",
     "  | nil => show denoteInt 0 = (0 : α); simp [denoteInt_eq]",
     "  | cons p l ih =>",
     "    obtain ⟨h1, h2⟩ := h",
     "    show (p.2.denote ctx) * (p.1.denote ctx) + (lcExprR l).denote ctx = 0",
     "    rw [h1, ih h2]; simp", "",
     "theorem lc_zeroR (ctx : Context α) (g : Expr) (l : List (Expr × Expr))",
     "    (hcert : Poly.beq' (toPolyK (.sub g (lcExprR l))) (.num 0) = true) (h : AllZero ctx l) :",
     "    g.denote ctx = 0 := by",
     "  rw [eq_of_toPolyK ctx g (lcExprR l) hcert]; exact denote_lcExprR ctx l h", "",
     f"noncomputable def eR : Expr :=\n  {expr(Rw)}", ""]
for j, (c, f) in enumerate(pairs):
    L += [f"noncomputable def f{j} : Expr :=\n  {expr(f)}", "", f"noncomputable def c{j} : Expr :=\n  {expr(c)}", ""]
L += [f"noncomputable def gq : Expr :=\n  {expr(gq)}", "", f"noncomputable def tgt : Expr :=\n  {expr(t)}", ""]
hyps = " ".join(f"(h{j} : f{j}.denote ctx = 0)" for j in range(len(pairs)))
lst = ", ".join(f"(c{j}, f{j})" for j in range(len(pairs))) + ", (gq, eR)"
andp = "⟨" + ", ".join(f"h{j}" for j in range(len(pairs))) + ", hR, trivial⟩"
L += [f"theorem tgt_zero (ctx : Context α) {hyps} (hR : eR.denote ctx = 0) : tgt.denote ctx = 0 :=",
      f"  lc_zeroR ctx tgt [{lst}] (by decide +kernel) {andp}", "", "end A816SPilot", ""]
open(OUTF, "w").write("\n".join(L))
print(f"wrote {OUTF}: {sum(len(x) + 1 for x in L)} bytes; facts {len(pairs)}; products {nprod}; max digits {maxdig}")
