"""gen_pilot_flat.py -- G3 pilot (flat route): emit one Lean module that kernel-checks a slice of the a_{8,16} certificate.

For a set of cofactor indices K it writes the reduced partial sum  s_K = sum_{k in K} (D_H H_k)(D_e e_k) mod R(w)
(w-degree <= 4) and its quotient G_K, and checks by kernel reflection (`decide +kernel` on `toPolyK`, the repository's
`Jacobian/ChartProof/Reflect.lean`) the identity of polynomials over Z

    s_K = sum_{k in K} e'_k * H'_k - R(w) * G_K .

Sums are emitted as balanced `.add` trees.  The fact is the first factor of each product (`mulK` recurses on its first
factor), as in branch (c)'s `T1Zero`.  Also reports the exact numbers of monomial products the kernel performs.
usage: python3 gen_pilot_flat.py A816_CERTIFICATE_DIR OUT.lean k1[,k2,...]
"""
import sys, os, runpy
A816, OUTF, KS = sys.argv[1], sys.argv[2], [int(t) for t in sys.argv[3].split(",")]
HERE = os.path.dirname(os.path.abspath(__file__))
sys.argv = ["flat_stats.py", A816, OUTF + ".stats.json"]
ns = runpy.run_path(os.path.join(HERE, "flat_stats.py"))
Hint, Eint, Rw, ctx, VARS = ns["Hint"], ns["Eint"], ns["Rw"], ns["ctx"], ns["VARS"]
import flint

wi = VARS.index("w")
used = set()
polys = {}
S = ctx.from_dict({})
GK = ctx.from_dict({})
for k in KS:
    G, s = divmod(Hint[k] * Eint[k], Rw)
    S += s; GK += G
for p in [S, GK] + [Hint[k] for k in KS] + [Eint[k] for k in KS]:
    for exps in p.to_dict():
        for i, e in enumerate(exps):
            if e:
                used.add(i)
order = [wi] + sorted(i for i in used if i != wi)
vidx = {i: n for n, i in enumerate(order)}


def mono(exps):
    fs = []
    for i, e in enumerate(exps):
        if e:
            v = f"(.var {vidx[i]})"
            fs.append(v if e == 1 else f"(.pow {v} {e})")
    if not fs:
        return None
    while len(fs) > 1:
        fs = [f"(.mul {fs[j]} {fs[j+1]})" if j + 1 < len(fs) else fs[j] for j in range(0, len(fs), 2)]
    return fs[0]


def num(c):
    c = int(c)
    return f"(.num {c})" if c >= 0 else f"(.num ({c}))"


def expr(p):
    terms = []
    for exps, c in sorted(p.to_dict().items()):
        assert c.denominator == 1
        m = mono(exps)
        terms.append(num(c.numerator) if m is None else f"(.mul {num(c.numerator)} {m})")
    if not terms:
        return "(.num 0)"
    while len(terms) > 1:
        terms = [f"(.add {terms[j]} {terms[j+1]})" if j + 1 < len(terms) else terms[j] for j in range(0, len(terms), 2)]
    return terms[0]


nprod = sum(len(Eint[k].to_dict()) * len(Hint[k].to_dict()) for k in KS) + 5 * len(GK.to_dict())
name = "k" + "_".join(map(str, KS))
eR = expr(Rw)
lines = [
    "import Jacobian.ChartProof.Reflect",
    "",
    f"/-! G3 pilot (generated by scripts/a816_lean_feasibility/gen_pilot_flat.py; not part of the Lean build):",
    f"cofactors {KS} of the a₈,₁₆ certificate,",
    f"{nprod} monomial products; numerals up to "
    f"{max(len(str(abs(int(c.numerator)))) for p in [S, GK] + [Hint[k] for k in KS] for c in p.to_dict().values())} digits. -/",
    "",
    "set_option maxHeartbeats 0",
    "set_option maxRecDepth 1000000",
    "",
    "namespace A816Pilot",
    "open Lean.Grind.CommRing BranchAb.ChartProof",
    "",
    "variable {α : Type*} [CommRing α]",
    "",
    "noncomputable def lcExprR (l : List (Expr × Expr)) : Expr :=",
    "  List.rec (.num 0) (fun p _ ih => .add (.mul p.2 p.1) ih) l",
    "",
    "theorem denote_lcExprR (ctx : Context α) (l : List (Expr × Expr)) (h : AllZero ctx l) :",
    "    (lcExprR l).denote ctx = 0 := by",
    "  induction l with",
    "  | nil => show denoteInt 0 = (0 : α); simp [denoteInt_eq]",
    "  | cons p l ih =>",
    "    obtain ⟨h1, h2⟩ := h",
    "    show (p.2.denote ctx) * (p.1.denote ctx) + (lcExprR l).denote ctx = 0",
    "    rw [h1, ih h2]; simp",
    "",
    "theorem lc_zeroR (ctx : Context α) (g : Expr) (l : List (Expr × Expr))",
    "    (hcert : Poly.beq' (toPolyK (.sub g (lcExprR l))) (.num 0) = true) (h : AllZero ctx l) :",
    "    g.denote ctx = 0 := by",
    "  rw [eq_of_toPolyK ctx g (lcExprR l) hcert]; exact denote_lcExprR ctx l h",
    "",
    f"noncomputable def eR : Expr :=\n  {eR}",
    "",
]
for k in KS:
    lines += [f"noncomputable def e{k} : Expr :=\n  {expr(Eint[k])}", "",
              f"noncomputable def h{k} : Expr :=\n  {expr(Hint[k])}", ""]
lines += [f"noncomputable def gq_{name} : Expr :=\n  {expr(-GK)}", "",
          f"noncomputable def s_{name} : Expr :=\n  {expr(S)}", ""]
hyps = " ".join(f"(he{k} : e{k}.denote ctx = 0)" for k in KS)
pairs = ", ".join(f"(h{k}, e{k})" for k in KS) + f", (gq_{name}, eR)"
proof_and = "⟨" + ", ".join(f"he{k}" for k in KS) + ", hR, trivial⟩"
lines += [f"theorem s_{name}_zero (ctx : Context α) {hyps} (hR : eR.denote ctx = 0) :",
          f"    (s_{name}).denote ctx = 0 :=",
          f"  lc_zeroR ctx s_{name} [{pairs}] (by decide +kernel) {proof_and}",
          "", "end A816Pilot", ""]
open(OUTF, "w").write("\n".join(lines))
print(f"wrote {OUTF}: {len(chr(10).join(lines))} bytes; products {nprod}; s {len(S.to_dict())} terms; "
      f"G {len(GK.to_dict())} terms; vars {len(order)}")
