#!/bin/bash
# regenerate.sh -- rebuild the structured certificate from scratch (about 2-3 minutes) and confirm that the printed
# a816_lift.txt and structured_reduced.json come out byte-identical.
set -u
cd "$(dirname "$0")"
REPO_SRC="$PWD/../a816_full.sing"          # scripts/a816_full.sing in the repository
if [ -z "${A816_SRC:-}" ]; then if [ -f "$REPO_SRC" ]; then A816_SRC=$REPO_SRC; else A816_SRC=$PWD/a816_full.sing; fi; fi
export A816_SRC

cp structured_reduced.json structured_reduced.bundle.json
python3 structured_cert.py || exit 1
python3 mk_singular_check.py structured_cert.json check_structured.sing a816_lift.regen.txt > /dev/null
Singular -q check_structured.sing 2>&1 | grep -E "SINGULAR CHECK"
ok=0
cmp -s a816_lift.regen.txt a816_lift.txt && echo "a816_lift.txt regenerated byte-identically" || { echo "a816_lift.txt DIFFERS"; ok=1; }
cmp -s structured_reduced.json structured_reduced.bundle.json && echo "structured_reduced.json regenerated byte-identically" || { echo "structured_reduced.json DIFFERS"; ok=1; }
rm -rf regen check_structured.sing a816_lift.regen.txt structured_reduced.bundle.json
exit $ok
