"""export_pari.py -- write span_check.gp: an independent PARI/GP check of the span certificate."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
cert = json.load(open(os.path.join(HERE, "cert.json")))
T1, T2, S1, S2 = cert["T1"], cert["T2"], cert["S1"], cert["S2"]
V = {T1: "t1", T2: "t2", S1: "s1", S2: "s2"}
def kel(c): return "Mod(" + " + ".join(f"({x})*w^{i}" for i, x in enumerate(c)) + ", R)"
def poly(p):
    if not p: return "0"
    out = []
    for m, c in p:
        mono = "*".join(f"{V[v]}^{e}" for v, e in m)
        out.append(kel(c) + ("*" + mono if mono else ""))
    return "(" + " + ".join(out) + ")"
L = ["\\\\ span_check.gp -- generated by export_pari.py from cert.json", "R = w^5 - w^4 + 3*w^3 + 3*w^2 + 26;"]
L.append("b = [" + ", ".join(poly(b) for b, M, Lq in cert["bML"]) + "];")
L.append("M = [" + ", ".join(poly(M) for b, M, Lq in cert["bML"]) + "];")
L.append("L = [" + ", ".join(poly(Lq) for b, M, Lq in cert["bML"]) + "];")
L.append("F = [" + ", ".join(poly(f) for f in cert["F"]) + "];")
L.append("G0 = [" + ", ".join(poly(g) for g in cert["G0"]) + "];")
L.append("G1 = [" + ", ".join(poly(g) for g in cert["G1"]) + "];")
L.append("sel = " + str([[i + 1 for i in tr] for tr in cert["minors_sel"]]) + ";")
L.append("c0 = [" + ", ".join(kel(c) for c in cert["c0"]) + "];")
L.append("c1 = [" + ", ".join(kel(c) for c in cert["c1"]) + "];")
L.append(r'''
iszero(p) = (simplify(lift(p)) == 0);
\\ 1. F_i = b_i + s1 M_i + s2 L_i
ok1 = 1; for(i=1,7, if(!iszero(F[i] - (b[i] + s1*M[i] + s2*L[i])), ok1 = 0));
print("1. F_i = b_i + s1*M_i + s2*L_i for all 7 rows: ", if(ok1,"PASS","FAIL"));
\\ 2. all 35 minors det[b|M|L] are binary quintics, rank of the 35 x 6 coefficient matrix
mino(i,j,k) = matdet([b[i],M[i],L[i]; b[j],M[j],L[j]; b[k],M[k],L[k]]);
allm = List(); forsubset([7,3], s, listput(allm, mino(s[1],s[2],s[3])));
nz = 0; C = matrix(35, 6);
{for(r=1,35, m = allm[r]; if(!iszero(m), nz++);
  for(e=0,5, C[r,e+1] = polcoef(polcoef(lift(m), 5-e, t1), e, t2)))};
print("2. nonzero minors: ", nz, " of 35;  rank over K5: ", matrank(C * Mod(1,R)));
\\ 3. t1^5 = sum c0_r * minor(sel_r), t2^5 = sum c1_r * minor(sel_r)
S0 = sum(r=1,6, c0[r] * mino(sel[r][1], sel[r][2], sel[r][3]));
S1c = sum(r=1,6, c1[r] * mino(sel[r][1], sel[r][2], sel[r][3]));
print("3. t1^5 = sum c0 * minors: ", if(iszero(S0 - t1^5),"PASS","FAIL"), ";  t2^5 = sum c1 * minors: ", if(iszero(S1c - t2^5),"PASS","FAIL"));
\\ 4. the multipliers used in Lean: t1^5 = sum G0_r F_r, t2^5 = sum G1_r F_r
print("4. t1^5 = sum G0*F: ", if(iszero(sum(r=1,7,G0[r]*F[r]) - t1^5),"PASS","FAIL"), ";  t2^5 = sum G1*F: ", if(iszero(sum(r=1,7,G1[r]*F[r]) - t2^5),"PASS","FAIL"));
\\ 5. control: a corrupted multiplier must fail
print("5. control (G0[1] perturbed by 1): ", if(iszero(sum(r=1,7,G0[r]*F[r]) + F[1] - t1^5),"PASSED (bad)","rejected (good)"));
''')
open(os.path.join(HERE, "span_check.gp"), "w").write("\n".join(L))
print("wrote span_check.gp", sum(len(x) for x in L), "bytes")
