"""
gen_sharp.py -- emit Jacobian/BranchAbSharp.lean:

  top_layer_E5       : the stated (rescaled K5) top layer satisfies E5, 2 A₂ B₃' − 3 A₂' B₃ = x²,
                       for every char-0 field and every root w (a consistency check of the hard-coded
                       top-layer values: the descent itself never uses E5).
  layers_K5_sharp    : every hypothesis of layers_K5 except hv is satisfiable (the lower-edge partial
                       solution A₀ = B₀ = 1, A₁ = B₁ = B₂ = 0), and there b₁₂,₂₄ = 0.  So layers_K5 is not
                       vacuous and the vertex condition (12,24) is exactly what it refutes.
"""
import json, os
from fractions import Fraction
from flint import fmpq_poly

cert = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "cert.json")))
top = cert["top"]
Rr = fmpq_poly([26, 0, 3, 3, -1, 1])
def q(s):
    f = Fraction(s)
    return f"({f.numerator} : L)" if f.denominator == 1 else f"(({f.numerator}) / {f.denominator} : L)"
def kel(c):
    terms = [q(s) + ("" if i == 0 else (" * w" if i == 1 else f" * w ^ ({i} : ℕ)")) for i, s in enumerate(c) if Fraction(s) != 0]
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"
TA = {int(v.split('_')[1]): top[v] for v in top if v[0] == 'a'}     # A₂.coeff i, i = 1..8
TB = {int(v.split('_')[1]): top[v] for v in top if v[0] == 'b'}     # B₃.coeff k, k = 2..12
REDL = []
for k in range(5, 9):
    wk = fmpq_poly([0] * k + [1]); qk, rk = divmod(wk, Rr)
    REDL.append((k, kel([str(rk[i]) for i in range(5)]),
                 "(" + " + ".join(f"({qk[i]} : L) * w ^ ({i} : ℕ)" for i in range(qk.degree() + 1)) + ")"))
RED = ", ".join(f"hw{k}" for k, _, _ in REDL)
HW = [f"  have hw{k} : w ^ ({k} : ℕ) = {r} := by linear_combination {qq} * hw" for k, r, qq in REDL]

L = ["""import Jacobian.BranchAbFinal

/-! Generated by gen_sharp.py.  Consistency of the hard-coded top layer (E5 holds) and sharpness of
`layers_K5` (only the vertex condition `b₁₂,₂₄ ≠ 0` is contradicted). -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false
set_option linter.unnecessarySeqFocus false

open BranchAb

namespace BranchAb
"""]
# ---- top_layer_E5
L.append("/-- The rescaled K₅ top layer solves the top-layer equation E5: `2 A₂ B₃' − 3 A₂' B₃ = x²`. -/")
L.append("theorem top_layer_E5 {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) (A₂ B₃ : Polynomial L)")
L.append("    (sA₂ : ∀ i, A₂.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8) (sB₃ : ∀ i, B₃.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12)")
for i in sorted(TA): L.append(f"    (tA{i} : A₂.coeff {i} = {kel(TA[i])})")
for k in sorted(TB): L.append(f"    (tB{k} : B₃.coeff {k} = {kel(TB[k])})")
L.append("    : layerTerm 2 3 A₂ B₃ = Polynomial.C 1 * Polynomial.X ^ 2 := by")
L += HW
ZN = []
for i in [0] + list(range(9, 23)):
    L.append(f"  have zA{i} : A₂.coeff {i} = 0 := coeff_zero_of_support _ 1 8 sA₂ {i} (by omega)"); ZN.append(f"zA{i}")
for k in [0, 1] + list(range(13, 23)):
    L.append(f"  have zB{k} : B₃.coeff {k} = 0 := coeff_zero_of_support _ 2 12 sB₃ {k} (by omega)"); ZN.append(f"zB{k}")
TOPS = ", ".join([f"tA{i}" for i in sorted(TA)] + [f"tB{k}" for k in sorted(TB)])
SIMP = ("coeff_layerTerm, Finset.sum_range_succ, Finset.sum_range_zero, Nat.cast_ofNat, Nat.cast_zero, "
        "Nat.cast_one, zero_add, " + ", ".join(ZN) + ", " + TOPS + ", mul_zero, zero_mul, add_zero, sub_zero, "
        "Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, one_mul")
L.append("  ext n")
L.append("  by_cases hn : n ≤ 21")
L.append("  · interval_cases n <;>")
L.append(f"      (simp only [{SIMP}] <;> (try norm_num) <;> (try ring_nf) <;> (try simp only [{RED}]) <;> (try ring_nf))")
L.append("  · rw [coeff_layerTerm, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow]")
L.append("    split_ifs with h2")
L.append("    · omega")
L.append("    rw [mul_zero]")
L.append("    refine Finset.sum_eq_zero (fun i hi => ?_)")
L.append("    by_cases hi8 : i ≤ 8")
L.append("    · rw [coeff_zero_of_support B₃ 2 12 sB₃ (n + 1 - i) (by omega), mul_zero]")
L.append("    · rw [coeff_zero_of_support A₂ 1 8 sA₂ i (by omega), mul_zero, zero_mul]")
L.append("")
# ---- sharpness: explicit lower-edge layers
def matchfn(name, T):
    arms = "\n".join(f"  | {i} => {kel(T[i])}" for i in sorted(T))
    return f"/-- The rescaled K₅ top-layer coefficients of `{name}`. -/\nnoncomputable def {name} {{L : Type*}} [Field L] (w : L) : ℕ → L\n{arms}\n  | _ => 0\n"
L.append(matchfn("topA", TA)); L.append(matchfn("topB", TB))
L.append("""lemma coeff_sum_C_mul_X_pow {L : Type*} [Field L] (f : ℕ → L) (N i : ℕ) :
    (∑ j ∈ Finset.range N, Polynomial.C (f j) * Polynomial.X ^ j).coeff i = if i < N then f i else 0 := by
  rw [Polynomial.finsetSum_coeff]
  simp only [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, mul_ite, mul_one, mul_zero]
  rw [Finset.sum_ite_eq]; simp [Finset.mem_range]
""")
L.append("""/-- **Sharpness.**  The lower-edge partial solution (`A₀ = B₀ = 1`, `A₁ = B₁ = B₂ = 0`, top layer the
rescaled K₅ point) satisfies E5, E4, E3, E2, the Newton-polygon supports and the top-layer values of
`layers_K5`, with `b₁₂,₂₄ = 0`.  So `layers_K5` is not vacuous: its content is exactly `b₁₂,₂₄ = 0`. -/""")
L.append("theorem layers_K5_sharp {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) :")
L.append("    ∃ A₀ A₁ A₂ B₀ B₁ B₂ B₃ : Polynomial L,")
L.append("      layerTerm 2 3 A₂ B₃ = Polynomial.C 1 * Polynomial.X ^ 2 ∧")
L.append("      layerTerm 2 2 A₂ B₂ + layerTerm 1 3 A₁ B₃ = 0 ∧")
L.append("      layerTerm 2 1 A₂ B₁ + layerTerm 1 2 A₁ B₂ + layerTerm 0 3 A₀ B₃ = 0 ∧")
L.append("      layerTerm 2 0 A₂ B₀ + layerTerm 1 1 A₁ B₁ + layerTerm 0 2 A₀ B₂ = 0 ∧")
L.append("      (∀ i, A₀.coeff i ≠ 0 → 0 ≤ i ∧ i ≤ 8) ∧ (∀ i, A₁.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8) ∧")
L.append("      (∀ i, A₂.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8) ∧ (∀ i, B₀.coeff i ≠ 0 → 0 ≤ i ∧ i ≤ 12) ∧")
L.append("      (∀ i, B₁.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 12) ∧ (∀ i, B₂.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12) ∧")
L.append("      (∀ i, B₃.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12) ∧")
L.append("      (∀ i, A₂.coeff i = topA w i) ∧ (∀ k, B₃.coeff k = topB w k) ∧ B₀.coeff 12 = 0 := by")
L.append("  set A₂ : Polynomial L := ∑ j ∈ Finset.range 9, Polynomial.C (topA w j) * Polynomial.X ^ j with hA₂")
L.append("  set B₃ : Polynomial L := ∑ j ∈ Finset.range 13, Polynomial.C (topB w j) * Polynomial.X ^ j with hB₃")
L.append("  have cA : ∀ i, A₂.coeff i = topA w i := by")
L.append("    intro i; rw [hA₂, coeff_sum_C_mul_X_pow]; split_ifs with h")
L.append("    · rfl")
L.append("    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 9 := ⟨i - 9, by omega⟩; rfl")
L.append("  have cB : ∀ i, B₃.coeff i = topB w i := by")
L.append("    intro i; rw [hB₃, coeff_sum_C_mul_X_pow]; split_ifs with h")
L.append("    · rfl")
L.append("    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 13 := ⟨i - 13, by omega⟩; rfl")
L.append("  have sA : ∀ i, A₂.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8 := by")
L.append("    intro i h; rw [cA] at h; by_contra hc; apply h")
L.append("    rcases Nat.lt_or_ge i 1 with h0 | h9")
L.append("    · obtain rfl : i = 0 := by omega")
L.append("      rfl")
L.append("    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 9 := ⟨i - 9, by omega⟩; rfl")
L.append("  have sB : ∀ i, B₃.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12 := by")
L.append("    intro i h; rw [cB] at h; by_contra hc; apply h")
L.append("    rcases Nat.lt_or_ge i 2 with h0 | h9")
L.append("    · interval_cases i <;> rfl")
L.append("    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 13 := ⟨i - 13, by omega⟩; rfl")
L.append("  refine ⟨Polynomial.C 1, 0, A₂, Polynomial.C 1, 0, 0, B₃, ?_, ?_, ?_, ?_, ?_, ?_, sA, ?_, ?_, ?_, sB, cA, cB, ?_⟩")
targs = " ".join([f"(by rw [cA]; rfl)" for _ in sorted(TA)] + [f"(by rw [cB]; rfl)" for _ in sorted(TB)])
L.append(f"  · exact top_layer_E5 w hw A₂ B₃ sA sB {targs}")
L.append("  · simp [layerTerm]")
L.append("  · simp [layerTerm]")
L.append("  · simp [layerTerm]")
L.append("  · intro i h; rw [Polynomial.coeff_C] at h; split_ifs at h with h0")
L.append("    · omega")
L.append("    · exact absurd rfl h")
L.append("  · intro i h; simp at h")
L.append("  · intro i h; rw [Polynomial.coeff_C] at h; split_ifs at h with h0")
L.append("    · omega")
L.append("    · exact absurd rfl h")
L.append("  · intro i h; simp at h")
L.append("  · intro i h; simp at h")
L.append("  · rw [Polynomial.coeff_C]; simp")
L.append("\nend BranchAb\n")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Jacobian", "BranchAbSharp.lean"), "w").write("\n".join(L))
print("written")
