"""
gen_lean_c2.py -- Lean 4 modules for the branch-(c) eliminations E1 (values), E0, E_{-1}, E_{-2}, continuing
gen_lean_c.py (E4/E3/E2 values, reduced E1 equations, Omega), from certgen/cert.json, certgen_c/cert_c.json and
certgen_c/cert_c2.json (make_cert_c2.py).  The conditions proved are exactly lower_c's (certgen_c/conds_c.json;
make_cert_c2.py asserts the equality term by term).

Proof design (bounded ring normalisation).  Substituting all lower-layer values into a raw equation and running
ring_nf once is too large for the deeper layers (estimated 1.8x, 4.8x and 8.2x the largest E1 module, whose heap
is 2.4 GB).  So every expensive identity is split into lemmas whose expansion work is bounded by BUDGET:

  chunk      c_{L}_{i}_{j}_{n} : sum_{t in chunk n} c_t * x_t * y_t = P_n       (values substituted; ring_nf + R(w))
  reduced    {L}red_{i}_{j}    : S_k = 0         from h (raw equation) and the chunks  (linear_combination, ring1)
  part       {name}_p{n}       : P_n = 0         from reduced equations r_j, P_n = sum_{j in part} m_j S_j
  value      {L}v_{u}          : u = value       from the parts (ring1)
  condition  {L}_{Cond}        : Cond = 0        from the parts (ring1)
  main       chart_descent_K5  : raw E4..E-2 equations -> Omega = Psi = Phi1 = Phi2 = Theta1..3 = pure rows = 0

The work of a product c*x*y is |X|*|Y|, |X| = number of (monomial, nonzero w-coefficient) pairs of x's value.
Every chunk / part / value / condition identity is re-checked in Python (exact over K5) before it is emitted.
"""
import json, os, sys, io, contextlib, shutil
from fractions import Fraction
from flint import fmpq_poly
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
with contextlib.redirect_stdout(io.StringIO()):
    import make_cert_c as mc
BUDGET = int(os.environ.get("BUDGET", "20000"))       # max expansion work per chunk / part lemma
MODBUDGET = int(os.environ.get("MODBUDGET", "20000")) # max total work per module
cert = json.load(open(os.path.join(HERE, "..", "certgen", "cert.json")))
cc = json.load(open(os.path.join(HERE, "cert_c.json")))
c2 = json.load(open(os.path.join(HERE, "cert_c2.json")))
OUT = os.path.join(HERE, "..", "Jacobian", "BranchC", "Descent2")
Rr = fmpq_poly([26, 0, 3, 3, -1, 1])
P_add, P_mul, P_scale, P_var, P_const, from_pj, Kc, red = mc.P_add, mc.P_mul, mc.P_scale, mc.P_var, mc.P_const, mc.from_pj, mc.Kc, mc.red
ZERO = mc.ZERO

# ------------------------------------------------------------------ Lean rendering (as gen_lean_c.py)
def q(s):
    f = Fraction(s)
    if f.denominator == 1: return f"({f.numerator} : L)"
    return f"(({f.numerator}) / {f.denominator} : L)"
def kel_s(c):
    terms = []
    for i, s in enumerate(c):
        if Fraction(s) == 0: continue
        terms.append(q(s) + ("" if i == 0 else (" * w" if i == 1 else f" * w ^ ({i} : ℕ)")))
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"
def kel(a): return kel_s([str(a[i]) for i in range(5)])            # fmpq_poly -> Lean
def mono(m): return " * ".join(v if e == 1 else f"{v} ^ ({e} : ℕ)" for v, e in m)
def poly(p):                                                          # dict poly -> Lean
    if not p: return "(0 : L)"
    return "(" + " + ".join(kel(c) + (" * " + mono(m) if m else "") for m, c in sorted(p.items())) + ")"
def poly_pj(p):                                                       # exactly gen_lean_c.poly (list order)
    if not p: return "(0 : L)"
    return "(" + " + ".join(kel_s(c) + (" * " + mono(m) if m else "") for m, c in p) + ")"
REDL = []
for k in range(5, 13):
    wk = fmpq_poly([0] * k + [1]); qk, rk = divmod(wk, Rr)
    REDL.append((k, kel_s([str(rk[i]) for i in range(5)]),
                 "(" + " + ".join(f"({qk[i]} : L) * w ^ ({i} : ℕ)" for i in range(qk.degree() + 1)) + ")"))
RED = ", ".join(f"hw{k}" for k, _, _ in REDL)
CLOSE = f"ring_nf <;> (try simp only [{RED}]) <;> (try ring_nf)"
HWLEM = [f"  have hw{k} : w ^ ({k} : ℕ) = {r} := by linear_combination {qq} * hw" for k, r, qq in REDL]
HDR = """import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Algebra.Field.Basic
import Mathlib.Algebra.CharZero.Defs
{imports}
/-! Generated by certgen_c/gen_lean_c2.py from certgen/cert.json, certgen_c/cert_c.json, certgen_c/cert_c2.json --
  exact K₅ certificates for the branch-(c) eliminations E₁ (values), E₀, E₋₁, E₋₂.  K₅ = ℚ[w]/(w⁵ − w⁴ + 3w³ + 3w² + 26);
  top layer = the rescaled K₅ point (a₁,₀ = b₂,₁ = 1).  The conditions are lower_c's (certgen_c/conds_c.json). -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace BranchC.Descent2
"""
FTR = "\nend BranchC.Descent2\n"
def lemma(name, binders, concl, body, doc=None):
    s = ([doc] if doc else []) + [f"theorem {name} {{L : Type*}} [Field L] [CharZero L]"]
    s += ["    " + b for b in binders]
    s[-1] += f" :\n    {concl} := by"
    return "\n".join(s + body) + "\n"
B_W = ["(w : L)", "(hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)"]; A_W = ["w", "hw"]
def B_vars(vs): return ["(" + " ".join(vs) + " : L)"] if vs else []

# ------------------------------------------------------------------ variables, values, hypothesis names
KEY = lambda v: (v[0], int(v.split('_')[1]), int(v.split('_')[2]))
top = {v: Kc(c) for v, c in cert["top"].items()}; TOPV = sorted(top, key=KEY)
T1, T2, S1, S2 = cert["T1"], cert["T2"], cert["S1"], cert["S2"]
R1, R2, QV = cc["R1"], cc["R2"], c2["QV"]
PARAMS = [T1, T2, S1, S2, R1, R2, QV]
Z, X, Y, V = cert["Z"], cert["X"], cc["Y"], cc["V"]
LAY = {L: c2["layers"][L] for L in ("E0", "Em1", "Em2")}
U0, U1, U2 = LAY["E0"]["U"], LAY["Em1"]["U"], LAY["Em2"]["U"]
VAL, HYP = {}, {}                  # var -> value poly ; var -> hypothesis name
for v in TOPV: VAL[v] = P_const(top[v]); HYP[v] = f"h_{v}"
for v, p, _ in cert["E4"]: VAL[v] = from_pj(p); HYP[v] = f"hz_{v}"
for v, p, _ in cert["E3"]: VAL[v] = from_pj(p); HYP[v] = f"hx_{v}"
for v, p, _ in cc["E2"]: VAL[v] = from_pj(p); HYP[v] = f"hy_{v}"
for v, p, _ in c2["E1v"]: VAL[v] = from_pj(p); HYP[v] = f"hv_{v}"
for v, p, _ in LAY["E0"]["values"]: VAL[v] = from_pj(p); HYP[v] = f"hu_{v}"
for v, p, _ in LAY["Em1"]["values"]: VAL[v] = from_pj(p); HYP[v] = f"hs_{v}"
assert not (set(VAL) & set(PARAMS))
VAL_STR = {}
for v in TOPV: VAL_STR[v] = kel_s(cert["top"][v])
for v, p, _ in cert["E4"]: VAL_STR[v] = poly_pj(p)
for v, p, _ in cert["E3"]: VAL_STR[v] = poly_pj(p)
for v, p, _ in cc["E2"]: VAL_STR[v] = poly_pj(p)
for v in VAL:
    if v not in VAL_STR: VAL_STR[v] = poly(VAL[v])
def size(v):
    if v not in VAL: return 1
    return max(1, sum(sum(1 for i in range(5) if c[i] != 0) for c in VAL[v].values()))
def value_or_var(v): return VAL.get(v, P_var(v))
def hyp_stmt(v): return f"({HYP[v]} : {v} = {VAL_STR[v]})"
def eqstr(terms): return " + ".join(f"{c} * {pv} * {qv}" if c >= 0 else f"({c}) * {pv} * {qv}" for c, pv, qv in terms)

# raw equations, reduced-equation names
RAWN, EQ, REDN = {}, {}, {}
for W, tag in (("-3", "4"), ("-2", "3")):
    RAWN[W] = []
    for k, terms in cert["eqs"][W]:
        n = f"h{tag}_{k[0]}_{k[1]}"; RAWN[W].append(n); EQ[n] = eqstr(terms)
for W, tag, rt in (("-1", "2c", "r2c"), ("0", "1", "r1"), ("1", "0", "r0"), ("2", "m1", "rm1"), ("3", "m2", "rm2")):
    RAWN[W] = []; REDN[W] = []
    for k, terms in cc["eqs"][W]:
        n = f"h{tag}_{k[0]}_{k[1]}"; RAWN[W].append(n); EQ[n] = eqstr(terms); REDN[W].append(f"{rt}_{k[0]}_{k[1]}")
for L, W in (("E0", "1"), ("Em1", "2"), ("Em2", "3")):
    assert [list(k) for k, _ in cc["eqs"][W]] == LAY[L]["keys"], L

files, deps, work_of = {}, {}, {}
def put(path, text_body, imports=(), work=0):
    """path like 'E0/c_18_37_1' -> module Jacobian.BranchC.Descent2.E0.c_18_37_1"""
    mod = "Jacobian.BranchC.Descent2." + path.replace("/", ".")
    files[path] = (list(imports), text_body); deps[mod] = list(imports); work_of[mod] = work
    return mod

# ------------------------------------------------------------------ generic: parts of sum_j m_j * S_j
def parts_lemmas(prefix, path, mults, polys, rnames, extra_vars, target, render=None):
    render = render or (lambda j: poly(polys[j]))
    """target(=value identity or condition) == sum_j m_j * polys[j]; emit part lemmas with work <= BUDGET.
       mults: list of fmpq_poly (K5) or None; returns (list of (lemma name, module, hyps used, part poly))."""
    idx = [j for j, m in enumerate(mults) if m is not None and m != 0]
    groups, cur, cw = [], [], 0
    for j in idx:
        wj = 5 * max(1, sum(sum(1 for i in range(5) if c[i] != 0) for c in polys[j].values()))
        if cur and cw + wj > BUDGET: groups.append(cur); cur, cw = [], 0
        cur.append(j); cw += wj
    if cur: groups.append(cur)
    out, total = [], {}
    for n, g in enumerate(groups, 1):
        P = {}
        for j in g: P = P_add(P, P_scale(polys[j], mults[j]))
        total = P_add(total, P)
        name = f"{prefix}_p{n}"
        binders = B_W + B_vars(PARAMS + extra_vars) + [f"({rnames[j]} : {render(j)} = 0)" for j in g]
        lc = " + ".join(f"{kel(mults[j])} * {rnames[j]}" for j in g)
        body = HWLEM + [f"  linear_combination (norm := skip) {lc}", f"  {CLOSE}"]
        w = sum(5 * max(1, sum(sum(1 for i in range(5) if c[i] != 0) for c in polys[j].values())) for j in g)
        mod = put(f"{path}_p{n}", lemma(name, binders, f"{poly(P)} = 0", body), work=w)
        out.append((name, mod, [rnames[j] for j in g], P))
    assert P_add(total, target, -1) == {}, prefix          # exact: sum of parts == target
    return out

# ------------------------------------------------------------------ E1 values (from the reduced E1 equations)
E1red = [from_pj(p) for p in cc["E1red"]]
op1 = c2["op1"]
e1v_mods = []
for v, p, E_ in c2["E1v"]:
    mults = [None] * len(E1red)
    for jj, i in enumerate(op1): mults[i] = Kc(E_[jj]) if Kc(E_[jj]) != 0 else None
    target = P_add(P_var(v), VAL[v], -1)
    prts = parts_lemmas(f"e1v_{v}", f"E1v/{v}", mults, E1red, REDN["0"], [x for x in V if x != QV], target,
                        render=lambda j: poly_pj(cc["E1red"][j]))
    used = sorted({h for _, _, hs, _ in prts for h in hs}, key=lambda h: REDN["0"].index(h))
    binders = B_W + B_vars(PARAMS + [x for x in V if x != QV]) + [f"({h} : {poly_pj(cc['E1red'][REDN['0'].index(h)])} = 0)" for h in used]
    body = [f"  have hp{n} := {name} " + " ".join(A_W + PARAMS + [x for x in V if x != QV] + hs) for n, (name, _, hs, _) in enumerate(prts, 1)]
    body += ["  linear_combination " + " + ".join(f"hp{n}" for n in range(1, len(prts) + 1))]
    mod = put(f"E1v/{v}", lemma(f"e1v_{v}", binders, f"{v} = {poly(VAL[v])}", body), imports=[m for _, m, _, _ in prts])
    e1v_mods.append((v, used, mod))

# ------------------------------------------------------------------ layers E0, E-1, E-2
LAYER_INFO = {}
for L, W, U, rt in (("E0", "1", U0, "r0"), ("Em1", "2", U1, "rm1"), ("Em2", "3", U2, "rm2")):
    reds = [from_pj(p) for p in LAY[L]["red"]]
    red_mods = []
    for (k, terms), hname, rname, S in zip(cc["eqs"][W], RAWN[W], REDN[W], reds):
        # chunks
        CUR = set(U)                                              # this layer's unknowns stay variables
        vov = lambda x: P_var(x) if x in CUR else value_or_var(x)
        sz = lambda x: 1 if x in CUR else size(x)
        chunks, cur, cw = [], [], 0
        for t in terms:
            c, pv, qv = t; wt = sz(pv) * sz(qv)
            if cur and cw + wt > BUDGET: chunks.append((cur, cw)); cur, cw = [], 0
            cur.append(t); cw += wt
        if cur: chunks.append((cur, cw))
        tot = {}
        chunk_info = []
        for n, (ch, cw) in enumerate(chunks, 1):
            P = {}
            for c, pv, qv in ch:
                P = P_add(P, P_scale(P_mul(vov(pv), vov(qv)), fmpq_poly([c])))
            tot = P_add(tot, P)
            vs = []
            for _, pv, qv in ch:
                for x in (pv, qv):
                    if x not in vs and x not in PARAMS: vs.append(x)
            valued = [x for x in vs if x in VAL and x not in CUR]
            name = f"c{rt[1:]}_{k[0]}_{k[1]}_{n}"
            binders = B_W + B_vars(PARAMS + vs) + [hyp_stmt(x) for x in valued]
            body = [f"  subst {HYP[x]}" for x in valued] + HWLEM + ["  linear_combination (norm := skip)", f"  {CLOSE}"]
            mod = put(f"{L}/c_{k[0]}_{k[1]}_{n}", lemma(name, binders, f"{eqstr(ch)} = {poly(P)}", body), work=cw)
            chunk_info.append((name, mod, vs, valued))
        assert P_add(tot, S, -1) == {}, (L, k)                   # exact: sum of chunks == reduced equation
        allv = []
        for _, pv, qv in terms:
            for x in (pv, qv):
                if x not in allv and x not in PARAMS: allv.append(x)
        valued = [x for x in allv if x in VAL and x not in CUR]
        binders = B_W + B_vars(PARAMS + allv) + [hyp_stmt(x) for x in valued] + [f"(h : {EQ[hname]} = 0)"]
        body = [f"  have hc{n} := {name} " + " ".join(A_W + PARAMS + vs + [HYP[x] for x in vl])
                for n, (name, _, vs, vl) in enumerate(chunk_info, 1)]
        body += ["  linear_combination h" + "".join(f" - hc{n}" for n in range(1, len(chunk_info) + 1))]
        mod = put(f"{L}/red_{k[0]}_{k[1]}", lemma(f"{L.lower()}red_{k[0]}_{k[1]}", binders, f"{poly(S)} = 0", body),
                  imports=[m for _, m, _, _ in chunk_info])
        red_mods.append((rname, hname, allv, valued, mod, S))
    op = LAY[L]["op"]
    # conditions (left null vectors) and values
    cond_mods = []
    for entry in LAY[L]["conds"]:
        nm, nv = entry[0], entry[1]
        if nv is None: cond_mods.append((nm, None, [REDN[W][entry[2]]], None)); continue
        mults = [None] * len(reds)
        for jj, i in enumerate(op): mults[i] = Kc(nv[jj]) if Kc(nv[jj]) != 0 else None
        target = from_pj(c2["conds"][nm])
        prts = parts_lemmas(f"{L.lower()}_{nm}", f"{L}/cond_{nm}", mults, reds, REDN[W], U, target)
        used = sorted({h for _, _, hs, _ in prts for h in hs}, key=lambda h: REDN[W].index(h))
        binders = B_W + B_vars(PARAMS + U) + [f"({h} : {poly(reds[REDN[W].index(h)])} = 0)" for h in used]
        body = [f"  have hp{n} := {name} " + " ".join(A_W + PARAMS + U + hs) for n, (name, _, hs, _) in enumerate(prts, 1)]
        body += ["  linear_combination " + " + ".join(f"hp{n}" for n in range(1, len(prts) + 1))]
        mod = put(f"{L}/cond_{nm}", lemma(f"{L.lower()}_{nm}", binders, f"{poly(target)} = 0", body),
                  imports=[m for _, m, _, _ in prts])
        cond_mods.append((nm, f"{L.lower()}_{nm}", used, mod))
    val_mods = []
    if L != "Em2":
        for v, p, Ew in LAY[L]["values"]:
            mults = [None] * len(reds)
            for jj, i in enumerate(op): mults[i] = Kc(Ew[jj]) if Kc(Ew[jj]) != 0 else None
            target = P_add(P_var(v), from_pj(p), -1)
            prts = parts_lemmas(f"{L.lower()}v_{v}", f"{L}/v_{v}", mults, reds, REDN[W], U, target)
            used = sorted({h for _, _, hs, _ in prts for h in hs}, key=lambda h: REDN[W].index(h))
            binders = B_W + B_vars(PARAMS + U) + [f"({h} : {poly(reds[REDN[W].index(h)])} = 0)" for h in used]
            body = [f"  have hp{n} := {name} " + " ".join(A_W + PARAMS + U + hs) for n, (name, _, hs, _) in enumerate(prts, 1)]
            body += ["  linear_combination " + " + ".join(f"hp{n}" for n in range(1, len(prts) + 1))]
            mod = put(f"{L}/v_{v}", lemma(f"{L.lower()}v_{v}", binders, f"{v} = {poly(VAL[v])}", body),
                      imports=[m for _, m, _, _ in prts])
            val_mods.append((v, f"{L.lower()}v_{v}", used, mod))
    LAYER_INFO[L] = (W, U, red_mods, cond_mods, val_mods)

# ------------------------------------------------------------------ main theorem
OMEGA = poly_pj(cc["Omega"])                                          # exactly gen_lean_c's statement
def lean_cond(nm): return poly(from_pj(c2["conds"][nm]))
CONDS = ["Psi", "Phi1", "Phi2", "Theta1", "Theta2", "Theta3", "E0pure_18_37", "Em1pure_17_36", "Em1pure_18_38",
         "Em2pure_16_35", "Em2pure_17_37"]
assert sorted(CONDS) == sorted(c2["conds"])
B_TOP = ["(" + " ".join(TOPV) + " : L)"] + [f"(h_{v} : {v} = {kel(top[v])})" for v in TOPV]
A_TOP = TOPV + [f"h_{v}" for v in TOPV]
ZP = [v for v, _, _ in cert["E4"]]; XP = [v for v, _, _ in cert["E3"]]; YP = [v for v, _, _ in cc["E2"]]
R3N = [f"r3_{n[3:]}" for n in RAWN["-2"]]
body = []
for v in ZP: body.append(f"  have hz_{v} := BranchAb.Descent.e4_{v} " + " ".join(A_W + A_TOP + Z + RAWN["-3"]))
for n, rn in zip(RAWN["-2"], R3N): body.append(f"  have {rn} := BranchAb.Descent.e3red_{n[3:]} " + " ".join(A_W + A_TOP + Z + [f"hz_{v}" for v in ZP] + X + [n]))
for v in XP: body.append(f"  have hx_{v} := BranchAb.Descent.e3_{v} " + " ".join(A_W + [T1, T2] + X + R3N))
for n, rn in zip(RAWN["-1"], REDN["-1"]):
    body.append(f"  have {rn} := BranchC.Descent.e2cred_{n[4:]} " + " ".join(A_W + A_TOP + Z + [f"hz_{v}" for v in ZP] + X + [f"hx_{v}" for v in XP] + Y + [n]))
for v in YP: body.append(f"  have hy_{v} := BranchC.Descent.e2c_{v} " + " ".join(A_W + [T1, T2, S1, S2] + Y + REDN["-1"]))
for n, rn in zip(RAWN["0"], REDN["0"]):
    body.append(f"  have {rn} := BranchC.Descent.e1red_{n[3:]} " + " ".join(A_W + A_TOP + Z + [f"hz_{v}" for v in ZP] + X + [f"hx_{v}" for v in XP] + Y + [f"hy_{v}" for v in YP] + V + [n]))
for v, used, _ in e1v_mods: body.append(f"  have hv_{v} := e1v_{v} " + " ".join(A_W + PARAMS + [x for x in V if x != QV] + used))
imports_main = [m for _, _, m in e1v_mods]
for L in ("E0", "Em1", "Em2"):
    W, U, red_mods, cond_mods, val_mods = LAYER_INFO[L]
    for rname, hname, allv, valued, mod, S in red_mods:
        body.append(f"  have {rname} := {L.lower()}red_{rname.split('_', 1)[1]} " + " ".join(A_W + PARAMS + allv + [HYP[x] for x in valued] + [hname]))
        imports_main.append(mod)
    for nm, lname, used, mod in cond_mods:
        if lname is None: continue
        body.append(f"  have hc_{nm} := {lname} " + " ".join(A_W + PARAMS + U + used)); imports_main.append(mod)
    for v, lname, used, mod in val_mods:
        body.append(f"  have {HYP[v]} := {lname} " + " ".join(A_W + PARAMS + U + used)); imports_main.append(mod)
def cond_proof(nm):
    for L in ("E0", "Em1", "Em2"):
        for n2, lname, used, mod in LAYER_INFO[L][3]:
            if n2 == nm: return f"hc_{nm}" if lname is not None else used[0]
body.append("  exact ⟨BranchC.Descent.e1_omega " + " ".join(A_W + [T1, T2, S1, S2, R1, R2] + V + REDN["0"]) + ", "
            + ", ".join(cond_proof(nm) for nm in CONDS) + "⟩")
concl = " ∧ ".join([f"{OMEGA} = 0"] + [f"{lean_cond(nm)} = 0" for nm in CONDS])
doc = """/-- **Branch (c): the E₄ … E₋₂ eliminations, exact over K₅.**  For every field `L` of characteristic zero and every
root `w` of `R`, the bracket equations of weights −3 … 3 (layers `E₄, E₃, E₂, E₁, E₀, E₋₁, E₋₂` of branch (c)) at the
rescaled K₅ top layer imply that `lower_c`'s conditions vanish: `Ω`, `Ψ`, `Φ₁`, `Φ₂`, `Θ₁`, `Θ₂`, `Θ₃` and the five pure rows
(certgen_c/conds_c.json), as polynomials in `b₁₁,₂₀, b₁₂,₂₂, b₁₁,₂₁, b₁₂,₂₃, a₆,₁₃, a₇,₁₅, b₁₀,₂₁`. -/"""
UALL = Z + X + Y + V + U0 + U1 + U2
main = lemma("chart_descent_K5", B_W + B_TOP + B_vars(UALL) + [f"({n} : {EQ[n]} = 0)" for W in ("-3", "-2", "-1", "0", "1", "2", "3") for n in RAWN[W]],
             concl, body, doc)
ext = ([f"Jacobian.Descent.E4.z_{v}" for v in ZP] + [f"Jacobian.Descent.E3red.{rn}" for rn in R3N] +
       [f"Jacobian.Descent.E3.x_{v}" for v in XP] + [f"Jacobian.BranchC.Descent.E2cred.{rn}" for rn in REDN["-1"]] +
       [f"Jacobian.BranchC.Descent.E2c.y_{v}" for v in YP] + [f"Jacobian.BranchC.Descent.E1red.{rn}" for rn in REDN["0"]] +
       ["Jacobian.BranchC.Descent.Omega1"])
files["MainChart"] = (ext + imports_main, main); deps["Jacobian.BranchC.Descent2.MainChart"] = ext + imports_main
work_of["Jacobian.BranchC.Descent2.MainChart"] = 0

# ------------------------------------------------------------------ write
shutil.rmtree(OUT, ignore_errors=True)
for path, (imps, text) in files.items():
    fn = os.path.join(OUT, path + ".lean"); os.makedirs(os.path.dirname(fn), exist_ok=True)
    open(fn, "w").write(HDR.format(imports="".join(f"import {m}\n" for m in imps)) + "\n" + text + FTR)
order = []                                                  # dependency order (Descent2 modules only)
seen = set()
def visit(m):
    if m in seen or not m.startswith("Jacobian.BranchC.Descent2"): return
    seen.add(m)
    for d in deps.get(m, []): visit(d)
    order.append(m)
for m in deps: visit(m)
open(os.path.join(HERE, "modules_c2.txt"), "w").write("\n".join(order) + "\n")
json.dump(work_of, open(os.path.join(HERE, "work_c2.json"), "w"), indent=0)
ws = sorted(work_of.values())
print(f"{len(files)} modules, {sum(len(t) for _, t in files.values())} bytes; BUDGET {BUDGET};"
      f" work per module: max {ws[-1]}, total {sum(ws)}; chunk modules {sum(1 for p in files if '/c_' in p)},"
      f" part modules {sum(1 for p in files if '_p' in p.split('/')[-1])}")
