"""
gen_bridge_c.py -- Jacobian/BranchC/Descent2R/Bridge.lean: from `DescentClaimC`'s hypotheses (the layer identities
`EIdent A B 0 n`, n = 4 .. -2, the branch-(c) supports, the rescaled K5 top layer, t2 = 1) to the scalar raw equations
of `chart_descent_refl` (Main.lean), hence to lower_c's conditions; and `DescentClaimC` from the explicit chart statement
`ChartEmptyC` (no zero of those conditions with b_{12,22} = 1).  Same recipe as `BranchAbFinal.lean`: coefficients of the
layer identities via `coeff_layerTermZ`, out-of-support coefficients set to zero, `linear_combination`.
Input: certgen_c/bridge_c.json (written by gen_refl_c.py).
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
b = json.load(open(os.path.join(HERE, "bridge_c.json")))
ALLV, TOPV, UNK, PARAMS, RAWH, CONCL = b["ALLV"], b["TOPV"], b["UNK"], b["PARAMS"], b["RAWH"], b["CONCL"]
OUT = os.path.join(HERE, "..", "Jacobian", "BranchC", "Descent2R", "Bridge.lean")

def layer_of(v):
    s, i, j = v.split("_"); i, j = int(i), int(j)
    return s, 2 * i - j, i
def cexpr(v):
    s, k, i = layer_of(v)
    return f"(({'A' if s == 'a' else 'B'} ({k})).coeff {i})"
def rangeP(k, i): return k <= 2 * i and i <= 8 and k <= 2 and i <= k + 8
def rangeQ(l, i): return l <= 2 * i and i <= 12 and 2 * l <= 3 * i and l <= 3 and i <= l + 12
# every in-support coefficient of the layers used is a variable of chart_descent_refl
ALLSET = set(ALLV)
for v in ALLV[1:]:
    s, k, i = layer_of(v)
    assert (rangeP(k, i) if s == "a" else rangeQ(k, i)), ("variable outside the support", v)
KS = {n: [k for k in range(-8, 3) if -12 <= n - k <= 3] for n in range(-2, 5)}
# every in-support coefficient that enters an equation with a NONZERO numeric coefficient is a variable
# (in-support coefficients such as a_0_0 = P(0,0), b_0_0 = Q(0,0) only ever get coefficient 0: k = 0, resp. B' kills them)
NOTVAR = set()
for n in KS:
    for m in range(0, 40):
        for k in KS[n]:
            l = n - k
            for a in range(0, m + 2):
                bb = m + 1 - a
                if rangeP(k, a) and rangeQ(l, bb) and k * bb - l * a != 0:
                    assert f"a_{a}_{2*a-k}" in ALLSET and f"b_{bb}_{2*bb-l}" in ALLSET, (n, m, k, a)
                elif rangeP(k, a) and rangeQ(l, bb):
                    for v in (f"a_{a}_{2*a-k}", f"b_{bb}_{2*bb-l}"):
                        if v not in ALLSET: NOTVAR.add(v)
print("in-support coefficients that are not variables (always with coefficient 0):", sorted(NOTVAR))

TAG = {4: "4", 3: "3", 2: "2c", 1: "1", 0: "0", -1: "m1", -2: "m2"}
L = []
L.append("""import Jacobian.BranchC.Descent2R.Main
import Jacobian.BranchC.DescentClaim

/-! Generated by certgen_c/gen_bridge_c.py.  **From `DescentClaimC`'s hypotheses to `lower_c`'s conditions.**

`descentClaimC_of_chartEmpty`: the explicit chart statement `ChartEmptyC` (no zero of lower_c's twelve conditions
with `b₁₂,₂₂ = 1`) implies `DescentClaimC`.  The layer identities `EIdent A B 0 n` (`n = 4 … −2`) give the 132 scalar
bracket equations of `Descent2R.chart_descent_refl` (coefficients via `coeff_layerTermZ`; coefficients outside the
branch-(c) supports vanish), which then gives the conditions.  With `main_theorem_c_of_claim`:
`main_theorem_c_of_chartEmpty : ChartEmptyC L → ¬∃ P Q λ, λ ≠ 0 ∧ NewtonNFc P Q ∧ jac P Q = C λ · x²`.
No `sorry`, no new axioms. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

open MvPolynomial

noncomputable section

namespace BranchC

open BranchAb

section
variable {K : Type*} [Field K]

/-- Coefficients of `LT_{a,b}(A,B) = a A B′ − b A′ B` for integer indices (`coeff_layerTerm` with `ℤ`). -/
theorem coeff_layerTermZ (a b : ℤ) (n : ℕ) (A B : Polynomial K) :
    (layerTermZ a b A B).coeff n =
      ∑ i ∈ Finset.range (n + 2),
        ((a : K) * ((n + 1 - i : ℕ) : K) - (b : K) * (i : K)) * A.coeff i * B.coeff (n + 1 - i) := by
  have h1 : ((a : Polynomial K) * A * Polynomial.derivative B).coeff n =
      ∑ i ∈ Finset.range (n + 2), (a : K) * ((n + 1 - i : ℕ) : K) * A.coeff i * B.coeff (n + 1 - i) := by
    rw [mul_assoc, Polynomial.coeff_intCast_mul, Polynomial.coeff_mul,
      Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk, Finset.sum_range_succ _ (n + 1), Finset.mul_sum]
    simp only [Polynomial.coeff_derivative, Nat.sub_self, Nat.cast_zero, mul_zero, zero_mul, add_zero]
    refine Finset.sum_congr rfl (fun i hi => ?_)
    have hi' : i ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
    have e1 : n - i + 1 = n + 1 - i := by omega
    rw [e1]; push_cast [Nat.cast_sub hi', Nat.cast_sub (by omega : i ≤ n + 1)]; ring
  have h2 : ((b : Polynomial K) * Polynomial.derivative A * B).coeff n =
      ∑ i ∈ Finset.range (n + 2), (b : K) * (i : K) * A.coeff i * B.coeff (n + 1 - i) := by
    rw [mul_assoc, Polynomial.coeff_intCast_mul, Polynomial.coeff_mul,
      Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk, Finset.sum_range_succ' _ (n + 1), Finset.mul_sum]
    simp only [Nat.cast_zero, mul_zero, zero_mul, add_zero]
    refine Finset.sum_congr rfl (fun i hi => ?_)
    have hi' : i ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
    simp only [Polynomial.coeff_derivative]
    have e1 : n + 1 - (i + 1) = n - i := by omega
    rw [e1]; push_cast; ring
  rw [layerTermZ, Polynomial.coeff_sub, h1, h2, ← Finset.sum_sub_distrib]
  refine Finset.sum_congr rfl (fun i _ => by ring)

theorem coeffA_zero {A : ℤ → Polynomial K} (hP : ∀ k i, (A k).coeff i ≠ 0 → rangeP k i)
    (k : ℤ) (i : ℕ) (h : ¬ rangeP k i) : (A k).coeff i = 0 := by
  by_contra hne; exact h (hP k i hne)

theorem coeffB_zero {B : ℤ → Polynomial K} (hQ : ∀ l i, (B l).coeff i ≠ 0 → rangeQ l i)
    (l : ℤ) (i : ℕ) (h : ¬ rangeQ l i) : (B l).coeff i = 0 := by
  by_contra hne; exact h (hQ l i hne)
""")
for n in range(4, -3, -1):
    ks = KS[n]
    lhs = " + ".join(f"layerTermZ ({k}) ({n - k}) (A ({k})) (B ({n - k}))" for k in ks)
    fin = "{" + ", ".join(str(k) for k in ks) + "}"
    rw = ", ".join(["Finset.sum_insert (by decide)"] * (len(ks) - 1) + ["Finset.sum_singleton"])
    shows = ", ".join(f"show ({n} : ℤ) - ({k}) = {n - k} by norm_num" for k in ks)
    L.append(f"""/-- `EIdent {n}` as an explicit sum (`k ∈ {fin}`). -/
theorem eIdent_c{TAG[n]} (A B : ℤ → Polynomial K) (h : EIdent A B 0 ({n})) :
    {lhs} = 0 := by
  unfold EIdent at h
  rw [ite_eq_right_of_eq_false _ _ (eq_false (show ({n} : ℤ) ≠ 5 by norm_num)), ← Finset.sum_filter] at h
  have hf : (Finset.Icc (-8 : ℤ) 2).filter (fun k => ({n} : ℤ) - k ∈ Finset.Icc (-12 : ℤ) 3) = {fin} := by
    decide
  rw [hf, {rw}] at h
  simp only [{shows}] at h
  linear_combination h
""")
L.append("end\n")
def cond_name(n): return "cond_" + ("Omega" if n == "Ω" else n)     # Jacobian/BranchC/CondsC.lean (gen_conds_c.py)
concl_hyps = " →\n    ".join(f"{cond_name(n)} w {' '.join(PARAMS)} = 0" for _, n, _ in CONCL)
L.append(f"""/-- **The branch-(c) chart statement** (explicit polynomials; NOT proved in Lean.  Its stratum `b₁₁,₂₀ = 0` is
kernel-checked, `T1Zero.chartEmpty_t1_zero`; the whole statement is proved outside Lean by the rank lemma of
chart_certificates/STEP3_4_CHART.md — see BRANCH_C_LEAN_STATUS.md §4):
no `w` with `R(w) = 0` and no `(b₁₁,₂₀, b₁₂,₂₂, b₁₁,₂₁, b₁₂,₂₃, a₆,₁₃, a₇,₁₅, b₁₀,₂₁)` with `b₁₂,₂₂ = 1` make lower_c's twelve
conditions vanish (`Ω, Ψ, Φ₁, Φ₂, Θ₁, Θ₂, Θ₃` and the five pure rows, each times a positive integer; generated from
certgen_c/conds_c.json by gen_refl_c.py; the polynomials are `BranchC.cond_*`, Jacobian/BranchC/CondsC.lean). -/
def ChartEmptyC (L : Type*) [Field L] : Prop :=
  ∀ (w : L), w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0 →
  ∀ ({' '.join(PARAMS)} : L), b_12_22 = 1 →
    {concl_hyps} → False
""")
# ---- the reduction
body = ["  intro w hw A B hA hB hPs hQs hE ht2"]
for n in range(4, -3, -1):
    body.append(f"  have L{TAG[n]} := eIdent_c{TAG[n]} A B (hE ({n}) (by norm_num) (by norm_num))")
zeros = {}
per_eq = []
for hname, (i, j), W, eq in RAWH:
    n, m = 2 * i + 1 - j, i
    assert 1 - W == n
    need = []
    for k in KS[n]:
        l = n - k
        for a in range(0, m + 2):
            bb = m + 1 - a
            if not rangeP(k, a): z = ("A", k, a)
            elif not rangeQ(l, bb): z = ("B", l, bb)
            else: continue
            need.append(z); zeros[z] = True
    per_eq.append((hname, n, m, eq, need))
def zname(z): return f"z{z[0]}_{('m' + str(-z[1])) if z[1] < 0 else z[1]}_{z[2]}"
for z in sorted(zeros):
    fn = "coeffA_zero hPs" if z[0] == "A" else "coeffB_zero hQs"
    rng = "rangeP" if z[0] == "A" else "rangeQ"
    body.append(f"  have {zname(z)} : ({z[0]} ({z[1]})).coeff {z[2]} = 0 := {fn} ({z[1]}) {z[2]} (by unfold {rng}; omega)")
SIMP = ("Polynomial.coeff_add, coeff_layerTermZ, Polynomial.coeff_zero, Finset.sum_range_succ, Finset.sum_range_zero, "
        "Nat.cast_ofNat, Nat.cast_zero, Nat.cast_one, Int.cast_ofNat, Int.cast_neg, Int.cast_one, Int.cast_zero, zero_add")
for hname, n, m, eq, need in per_eq:
    stmt = eq
    import re
    stmt = re.sub(r"\b([ab]_\d+_\d+)\b", lambda mm: cexpr(mm.group(1)), eq)
    zs = sorted(set(need))
    body.append(f"  have {hname} : {stmt} = 0 := by\n"
                f"    have e := congrArg (fun F => Polynomial.coeff F {m}) L{TAG[n]}\n"
                f"    simp only [{SIMP}{''.join(', ' + zname(z) for z in zs)}, mul_zero, zero_mul, add_zero, sub_zero] at e\n"
                f"    linear_combination e")
args = ["w", "hw"] + [cexpr(v) for v in TOPV]
for v in TOPV:
    s, k, i = layer_of(v)
    args.append(f"(hA {i})" if s == "a" else f"(hB {i})")
args += [cexpr(v) for v in UNK] + [h for h, _, _, _ in RAWH]
names = [f"c{i}" for i in range(len(CONCL))]
body.append(f"  obtain ⟨{', '.join(names)}⟩ := Descent2R.chart_descent_refl " + " ".join(args))
body.append(f"  exact hC w hw " + " ".join(cexpr(v) for v in PARAMS) + " ht2 " + " ".join(names))
L.append("""/-- **`DescentClaimC` from the explicit chart statement.** -/
theorem descentClaimC_of_chartEmpty (L : Type*) [Field L] [CharZero L] (hC : ChartEmptyC L) :
    DescentClaimC L := by
""" + "\n".join(body) + "\n")
L.append("""/-- **Branch (c) of the Jacobian conjecture (GGHV Prop. 4.3 case (1)), modulo `ChartEmptyC`.** -/
theorem main_theorem_c_of_chartEmpty {L : Type*} [Field L] [CharZero L] (hC : ChartEmptyC L) :
    ¬ ∃ (P Q : MvPolynomial (Fin 2) L) (lam : L), lam ≠ 0 ∧ NewtonNFc P Q ∧ jac P Q = C lam * X 0 ^ 2 :=
  main_theorem_c_of_claim (descentClaimC_of_chartEmpty L hC)

end BranchC
""")
open(OUT, "w").write("\n".join(L))
print("Bridge.lean:", os.path.getsize(OUT), "bytes;", len(zeros), "zero facts;", len(per_eq), "equations")
