"""
gen_t1zero_combine.py -- Jacobian/BranchC/T1Zero/Combine.lean: `ChartEmptyC` from its restriction `ChartEmptyC_T1ne0` to
b_{11,20} != 0, the stratum b_{11,20} = 0 being `T1Zero.chartEmpty_t1_zero` (kernel-checked); hence DescentClaimC and the
branch-(c) main theorem modulo `ChartEmptyC_T1ne0`.  Input: certgen_c/bridge_c.json (the same mirrors as Bridge.lean).
"""
import json, os, sys
sys.set_int_max_str_digits(0)
HERE = os.path.dirname(os.path.abspath(__file__))
b = json.load(open(os.path.join(HERE, "bridge_c.json")))
PARAMS, CONCL = b["PARAMS"], b["CONCL"]
assert PARAMS == ["b_11_20", "b_12_22", "b_11_21", "b_12_23", "a_6_13", "a_7_15", "b_10_21"]
assert [f for f, _, _ in CONCL[:7]] == ["ek_Omega", "ek_Psi", "ek_Phi1", "ek_Phi2", "ek_Theta1", "ek_Theta2", "ek_Theta3"]
def cond_name(n): return "cond_" + ("Omega" if n == "Ω" else n)
concl_hyps = " →\n    ".join(f"{cond_name(n)} w {' '.join(PARAMS)} = 0" for _, n, _ in CONCL)   # as in gen_bridge_c.py (ChartEmptyC)
cs = [f"c{i}" for i in range(len(CONCL))]
P = " ".join(PARAMS)
txt = f"""import Jacobian.BranchC.Descent2R.Bridge
import Jacobian.BranchC.T1Zero.Main

/-! Generated by certgen_c/gen_t1zero_combine.py.  **The stratum `b₁₁,₂₀ = 0` of the branch-(c) chart statement.**

`ChartEmptyC` (Bridge.lean) splits along `b₁₁,₂₀ = 0`.  That stratum is `T1Zero.chartEmpty_t1_zero`, checked by the
kernel from the exact slice certificate of step 1.  What remains is `ChartEmptyC_T1ne0`: the same statement with the
extra hypothesis `b₁₁,₂₀ ≠ 0`.  It is NOT proved in Lean.  The evidence for it is modular certificates only: 𝔽₁₀₁,
𝔽₁₀₀₀₀₀₃, 𝔽_{{109⁵}}; see BRANCH_C_LEAN_STATUS.md.  No `sorry`, no new axioms. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false

open MvPolynomial

noncomputable section

namespace BranchC

open BranchAb

/-- **What remains of the branch-(c) chart statement** (open): `ChartEmptyC` restricted to `b₁₁,₂₀ ≠ 0`. -/
def ChartEmptyC_T1ne0 (L : Type*) [Field L] : Prop :=
  ∀ (w : L), w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0 →
  ∀ ({P} : L), b_12_22 = 1 → b_11_20 ≠ 0 →
    {concl_hyps} → False

/-- `ChartEmptyC` from its `b₁₁,₂₀ ≠ 0` part; the stratum `b₁₁,₂₀ = 0` is `T1Zero.chartEmpty_t1_zero`. -/
theorem chartEmptyC_of_T1ne0 (L : Type*) [Field L] [CharZero L] (h : ChartEmptyC_T1ne0 L) : ChartEmptyC L := by
  intro w hw {P} ht2 {' '.join(cs)}
  by_cases ht1 : b_11_20 = 0
  · exact T1Zero.chartEmpty_t1_zero w hw {P} ht1 ht2 {' '.join(cs[:7])}
  · exact h w hw {P} ht2 ht1 {' '.join(cs)}

/-- **`DescentClaimC` modulo `ChartEmptyC_T1ne0`.** -/
theorem descentClaimC_of_chartEmpty_T1ne0 (L : Type*) [Field L] [CharZero L] (h : ChartEmptyC_T1ne0 L) :
    DescentClaimC L :=
  descentClaimC_of_chartEmpty L (chartEmptyC_of_T1ne0 L h)

/-- **Branch (c) of the Jacobian conjecture (GGHV Prop. 4.3 case (1)), modulo `ChartEmptyC_T1ne0`.** -/
theorem main_theorem_c_of_chartEmpty_T1ne0 {{L : Type*}} [Field L] [CharZero L] (h : ChartEmptyC_T1ne0 L) :
    ¬ ∃ (P Q : MvPolynomial (Fin 2) L) (lam : L), lam ≠ 0 ∧ NewtonNFc P Q ∧ jac P Q = C lam * X 0 ^ 2 :=
  main_theorem_c_of_claim (descentClaimC_of_chartEmpty_T1ne0 L h)

end BranchC
"""
OUT = os.path.join(HERE, "..", "Jacobian", "BranchC", "T1Zero", "Combine.lean")
open(OUT, "w").write(txt)
print("Combine.lean:", len(txt), "bytes")
