"""
gen_conds_c.py -- Jacobian/BranchC/CondsC.lean: lower_c's twelve chart conditions as named polynomial functions
`BranchC.cond_<name> (w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 : L) : L`.

Each is the explicit polynomial of bridge_c.json's CONCL (the mirror of `Descent2R.ek_*` / `er*`, i.e. exactly the
expression `Expr.denote` of that fact unfolds to), with the same balanced `+`-tree; subtrees of at most CHUNK terms
are split off as separate definitions `cond_<name>_c<i>`.  Elaborating one polynomial of a few hundred terms with big
numerals costs minutes of typeclass inference (superlinear in the tree size); in pieces it is linear, and it is done
once here instead of in every file that states the conditions (Descent2R.Main, Bridge, T1Zero, Combine).
The tree shape is preserved, so `ek.denote ctx = 0` and `cond_<name> w … = 0` stay definitionally equal (checked by
Lean where they are used).
"""
import json, os, sys
sys.set_int_max_str_digits(0)
sys.setrecursionlimit(100000)
HERE = os.path.dirname(os.path.abspath(__file__))
CHUNK = int(os.environ.get("CHUNK", "32"))
b = json.load(open(os.path.join(HERE, "bridge_c.json")))
PARAMS, CONCL = b["PARAMS"], b["CONCL"]
ARGS = "w " + " ".join(PARAMS)

def cond_name(f, n):
    return "cond_" + ("Omega" if n == "Ω" else n)

def match_parens(s):
    st, m = [], {}
    for i, ch in enumerate(s):
        if ch == "(": st.append(i)
        elif ch == ")": m[st.pop()] = i
    assert not st
    return m

def parse(s, i, m):
    """s[i] = '(' ; returns ('+', left, right) or ('leaf', i, j) for the parenthesised group starting at i"""
    j = m[i]; k = i + 1
    while k < j:
        if s[k] == "(":
            k = m[k] + 1; continue
        if s.startswith(" + ", k):
            assert s[i + 1] == "(" and s[k + 3] == "(", "unexpected node shape"
            left = parse(s, i + 1, m); right = parse(s, k + 3, m)
            assert m[k + 3] == j - 1
            return ("+", left, right)
        k += 1
    return ("leaf", i, j)

def nleaves(t): return 1 if t[0] == "leaf" else nleaves(t[1]) + nleaves(t[2])
def text(s, t): return s[t[1]:t[2] + 1] if t[0] == "leaf" else f"({text(s, t[1])} + {text(s, t[2])})"

out = ["""import Jacobian.ChartProof.Reflect

/-! Generated by certgen_c/gen_conds_c.py from certgen_c/bridge_c.json.  **lower_c's twelve branch-(c) chart
conditions** `Ω, Ψ, Φ₁, Φ₂, Θ₁, Θ₂, Θ₃` and the five pure rows, each times a positive integer (certgen_c/conds_c.json,
minimal integer scale), as explicit polynomials in `w` (a root of `R`) and the seven chart parameters
`b₁₁,₂₀, b₁₂,₂₂, b₁₁,₂₁, b₁₂,₂₃, a₆,₁₃, a₇,₁₅, b₁₀,₂₁`.  Subtrees of the balanced sum are separate definitions
(`cond_*_c<i>`) only to keep elaboration linear; the sum's shape is that of the reflected facts
`Descent2R.ek_*` / `Descent2R.er*`, so the two are definitionally equal. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace BranchC

section
variable {L : Type*} [Field L]
"""]
names = []
for f, n, mir in CONCL:
    cn = cond_name(f, n); names.append((f, n, cn))
    m = match_parens(mir)
    assert m[0] == len(mir) - 1
    tree = parse(mir, 0, m)
    assert text(mir, tree) == mir, f"reconstruction mismatch for {f}"
    chunks = []
    def emit(t):
        if t[0] == "leaf": return text(mir, t)
        if nleaves(t) <= CHUNK:
            cname = f"{cn}_c{len(chunks)}"; chunks.append((cname, text(mir, t)))
            return f"{cname} {ARGS}"
        return f"({emit(t[1])} + {emit(t[2])})"
    top = emit(tree)
    for cname, body in chunks:
        out.append(f"/-- a subtree of `{cn}` -/\nnoncomputable def {cname} ({ARGS} : L) : L :=\n  {body}\n")
    doc = f"lower_c's condition `{n}` (the fact `Descent2R.{f}`), {nleaves(tree)} terms"
    out.append(f"/-- {doc} -/\nnoncomputable def {cn} ({ARGS} : L) : L :=\n  {top}\n")
    # the unfolded definition is the mirror, character for character (up to the chunk names)
    expanded = top
    for cname, body in reversed(chunks):
        expanded = expanded.replace(f"{cname} {ARGS}", body)
    assert expanded == mir, f"chunked form does not expand to the mirror for {f}"
    print(f"{cn}: {nleaves(tree)} terms, {len(chunks)} chunks")
out.append("end\n\nend BranchC\n")
OUT = os.path.join(HERE, "..", "Jacobian", "BranchC", "CondsC.lean")
open(OUT, "w").write("\n".join(out))
json.dump([[f, n, cn] for f, n, cn in names], open(os.path.join(HERE, "conds_names_c.json"), "w"))
print("CondsC.lean:", os.path.getsize(OUT), "bytes")
