"""
gen_lean_c.py -- emit the branch-(c) E2/E1 certificate chain as Lean 4 modules, continuing the branch-(a,b)
E4/E3 certificates (Jacobian/Descent/{E4,E3red,E3}), from certgen/cert.json and certgen_c/cert_c.json.

  Jacobian/BranchC/Descent/E2cred/r2c_i_j.lean  E2 (branch c, with A_{-1}) equation, E4/E3 facts substituted
  Jacobian/BranchC/Descent/E2c/y_v.lean         y_p = poly(t,s) + lin(r)        (18 lemmas: E2 operator rank 18)
  Jacobian/BranchC/Descent/E1red/r1_i_j.lean    E1 equation with E4/E3/E2 facts substituted (20 lemmas)
  Jacobian/BranchC/Descent/Omega1.lean          W1 . (reduced E1) = Omega(t2, s2)  -- the E1 obstruction
  Jacobian/BranchC/Descent/MainOmega.lean       omega_descent_K5 : raw E4, E3, E2, E1 equations -> Omega = 0

Same proof style as certgen/gen_lean2.py: `linear_combination (norm := skip) sum mult * hyp`, closed by
`ring_nf`, reduction of w^k (k = 5..12) by R(w) = 0, and `ring_nf`.
"""
import json, os
from fractions import Fraction
from flint import fmpq_poly

HERE = os.path.dirname(os.path.abspath(__file__))
cert = json.load(open(os.path.join(HERE, "..", "certgen", "cert.json")))
cc = json.load(open(os.path.join(HERE, "cert_c.json")))
OUT = os.path.join(HERE, "..", "Jacobian", "BranchC", "Descent")
Rr = fmpq_poly([26, 0, 3, 3, -1, 1])
KEY = lambda v: (v[0], int(v.split('_')[1]), int(v.split('_')[2]))

def q(s):
    f = Fraction(s)
    if f.denominator == 1: return f"({f.numerator} : L)"
    return f"(({f.numerator}) / {f.denominator} : L)"
def kel(c):
    terms = []
    for i, s in enumerate(c):
        if Fraction(s) == 0: continue
        terms.append(q(s) + ("" if i == 0 else (" * w" if i == 1 else f" * w ^ ({i} : ℕ)")))
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"
def mono(m): return " * ".join(v if e == 1 else f"{v} ^ ({e} : ℕ)" for v, e in m)
def poly(p):
    if not p: return "(0 : L)"
    return "(" + " + ".join(kel(c) + (" * " + mono(m) if m else "") for m, c in p) + ")"

REDL = []
for k in range(5, 13):
    wk = fmpq_poly([0] * k + [1]); qk, rk = divmod(wk, Rr)
    REDL.append((k, kel([str(rk[i]) for i in range(5)]),
                 "(" + " + ".join(f"({qk[i]} : L) * w ^ ({i} : ℕ)" for i in range(qk.degree() + 1)) + ")"))
RED = ", ".join(f"hw{k}" for k, _, _ in REDL)
CLOSE = f"ring_nf <;> (try simp only [{RED}]) <;> (try ring_nf)"
HWLEM = [f"  have hw{k} : w ^ ({k} : ℕ) = {r} := by linear_combination {qq} * hw" for k, r, qq in REDL]
def lincomb(mults, hyps):
    parts = [f"{kel(m)} * {h}" for m, h in zip(mults, hyps) if any(Fraction(x) != 0 for x in m)]
    return " + ".join(parts) if parts else "0"

HDR = """import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Algebra.Field.Basic
import Mathlib.Algebra.CharZero.Defs

/-! Generated by certgen_c/gen_lean_c.py from certgen/cert.json and certgen_c/cert_c.json -- exact K₅
  certificates for the branch-(c) layers E₂ (with A₋₁) and E₁, continuing the branch-(a,b) E₄/E₃
  certificates.  K₅ = ℚ[w]/(w⁵ − w⁴ + 3w³ + 3w² + 26); top layer = the rescaled K₅ point (a₁,₀ = b₂,₁ = 1). -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace BranchC.Descent
"""
FTR = "\nend BranchC.Descent\n"

top = cert["top"]; TOPV = sorted(top, key=KEY)
Z, X = cert["Z"], cert["X"]
T1, T2, S1, S2 = cert["T1"], cert["T2"], cert["S1"], cert["S2"]
Y, V = cc["Y"], cc["V"]
R1, R2, QV = cc["R1"], cc["R2"], cc["Qv"]
EQ = {}; HN = {}
for W, tag in (("-3", "4"), ("-2", "3")):
    HN[W] = []
    for k, terms in cert["eqs"][W]:
        n = f"h{tag}_{k[0]}_{k[1]}"; HN[W].append(n)
        EQ[n] = " + ".join(f"{c} * {pv} * {qv}" if c >= 0 else f"({c}) * {pv} * {qv}" for c, pv, qv in terms)
for W, tag in (("-1", "2c"), ("0", "1")):
    HN[W] = []
    for k, terms in cc["eqs"][W]:
        n = f"h{tag}_{k[0]}_{k[1]}"; HN[W].append(n)
        EQ[n] = " + ".join(f"{c} * {pv} * {qv}" if c >= 0 else f"({c}) * {pv} * {qv}" for c, pv, qv in terms)

B_W = ["(w : L)", "(hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)"]; A_W = ["w", "hw"]
B_TOP = ["(" + " ".join(TOPV) + " : L)"] + [f"(h_{v} : {v} = {kel(top[v])})" for v in TOPV]
A_TOP = TOPV + [f"h_{v}" for v in TOPV]
SUBST_TOP = [f"  subst h_{v}" for v in TOPV]
def B_vars(vs): return ["(" + " ".join(vs) + " : L)"]
def B_hyps(names): return [f"({n} : {EQ[n]} = 0)" for n in names]
zfact = {v: poly(val) for v, val, _ in cert["E4"]}
xfact = {v: poly(val) for v, val, _ in cert["E3"]}
yfact = {v: poly(val) for v, val, _ in cc["E2"]}
ZP = [v for v, _, _ in cert["E4"]]; XP = [v for v, _, _ in cert["E3"]]; YP = [v for v, _, _ in cc["E2"]]
B_HZ = [f"(hz_{v} : {v} = {zfact[v]})" for v in ZP]; A_HZ = [f"hz_{v}" for v in ZP]
B_HX = [f"(hx_{v} : {v} = {xfact[v]})" for v in XP]; A_HX = [f"hx_{v}" for v in XP]
B_HY = [f"(hy_{v} : {v} = {yfact[v]})" for v in YP]; A_HY = [f"hy_{v}" for v in YP]
R3N = [f"r3_{n[3:]}" for n in HN["-2"]]
R2C = [poly(p_) for p_ in cc["E2red"]]; R1P = [poly(p_) for p_ in cc["E1red"]]
RN2C = [f"r2c_{n[4:]}" for n in HN["-1"]]; RN1 = [f"r1_{n[3:]}" for n in HN["0"]]
OMEGA = poly(cc["Omega"]); XTRA = poly(cc["Xtra1"][0])

def lemma(name, binders, concl, body, doc=None):
    s = ([doc] if doc else []) + [f"theorem {name} {{L : Type*}} [Field L] [CharZero L]"]
    s += ["    " + b for b in binders]
    s[-1] += f" :\n    {concl} := by"
    return "\n".join(s + body) + "\n"

files = {}; mods = []
def put(sub, name, text, hdr=HDR):
    files[f"{sub}/{name}" if sub else name] = hdr + "\n" + text + FTR
    mods.append(f"Jacobian.BranchC.Descent.{sub}.{name}" if sub else f"Jacobian.BranchC.Descent.{name}")

# ---- E2 (branch c), stage A: each E2 equation with the E4 and E3 facts substituted, reduced mod R
for n, rn, rp in zip(HN["-1"], RN2C, R2C):
    body = SUBST_TOP + [f"  subst {h}" for h in A_HZ] + [f"  subst {h}" for h in A_HX] + HWLEM + \
        ["  linear_combination (norm := skip) h", f"  {CLOSE}"]
    put("E2cred", rn, lemma(f"e2cred_{n[4:]}", B_W + B_TOP + B_vars(Z) + B_HZ + B_vars(X) + B_HX + B_vars(Y) +
                            [f"(h : {EQ[n]} = 0)"], f"{rp} = 0", body))
# ---- E2 (branch c), stage B: pivots from the reduced equations (the E2 operator has rank 18)
B_R2C = [f"({rn} : {rp} = 0)" for rn, rp in zip(RN2C, R2C)]
for v, val, E_ in cc["E2"]:
    body = HWLEM + [f"  linear_combination (norm := skip) {lincomb(E_, RN2C)}", f"  {CLOSE}"]
    put("E2c", f"y_{v}", lemma(f"e2c_{v}", B_W + B_vars([T1, T2, S1, S2] + Y) + B_R2C, f"{v} = {yfact[v]}", body))
# ---- E1, stage A: each E1 equation with the E4, E3, E2 facts substituted, reduced mod R
for n, rn, rp in zip(HN["0"], RN1, R1P):
    body = SUBST_TOP + [f"  subst {h}" for h in A_HZ] + [f"  subst {h}" for h in A_HX] + \
        [f"  subst {h}" for h in A_HY] + HWLEM + ["  linear_combination (norm := skip) h", f"  {CLOSE}"]
    put("E1red", rn, lemma(f"e1red_{n[3:]}", B_W + B_TOP + B_vars(Z) + B_HZ + B_vars(X) + B_HX + B_vars(Y) + B_HY +
                           B_vars(V) + [f"(h : {EQ[n]} = 0)"], f"{rp} = 0", body))
# ---- E1, stage B: the left null vector W1 of the E1 operator gives Omega
PARAMS = [T1, T2, S1, S2, R1, R2]
B_R1 = [f"({rn} : {rp} = 0)" for rn, rp in zip(RN1, R1P)]
body = HWLEM + [f"  linear_combination (norm := skip) {lincomb(cc['W1'], RN1)}", f"  {CLOSE}"]
doc = """/-- **The `E₁` obstruction.** The left null vector `W₁` of the 19 × 19 `E₁` operator, applied to the
reduced `E₁` equations, leaves `Ω(t₂, s₂)` (`t₂ = b₁₂,₂₂`, `s₂ = b₁₂,₂₃`): all `A₋₂`, `B₋₁`, `t₁`, `s₁`, `r`
terms cancel. -/"""
put("", "Omega1", lemma("e1_omega", B_W + B_vars(PARAMS + V) + B_R1, f"{OMEGA} = 0", body, doc))
# ---- main
HDR_MAIN = HDR.replace("import Mathlib.Tactic.LinearCombination\n",
    "import Mathlib.Tactic.LinearCombination\n" +
    "".join(f"import Jacobian.Descent.E4.z_{v}\n" for v in ZP) +
    "".join(f"import Jacobian.Descent.E3red.{rn}\n" for rn in R3N) +
    "".join(f"import Jacobian.Descent.E3.x_{v}\n" for v in XP) +
    "".join(f"import {m}\n" for m in mods))
body = []
for v in ZP:
    body.append(f"  have hz_{v} := BranchAb.Descent.e4_{v} " + " ".join(A_W + A_TOP + Z + HN["-3"]))
for n, rn in zip(HN["-2"], R3N):
    body.append(f"  have {rn} := BranchAb.Descent.e3red_{n[3:]} " + " ".join(A_W + A_TOP + Z + A_HZ + X + [n]))
for v in XP:
    body.append(f"  have hx_{v} := BranchAb.Descent.e3_{v} " + " ".join(A_W + [T1, T2] + X + R3N))
for n, rn in zip(HN["-1"], RN2C):
    body.append(f"  have {rn} := e2cred_{n[4:]} " + " ".join(A_W + A_TOP + Z + A_HZ + X + A_HX + Y + [n]))
for v in YP:
    body.append(f"  have hy_{v} := e2c_{v} " + " ".join(A_W + [T1, T2, S1, S2] + Y + RN2C))
for n, rn in zip(HN["0"], RN1):
    body.append(f"  have {rn} := e1red_{n[3:]} " + " ".join(A_W + A_TOP + Z + A_HZ + X + A_HX + Y + A_HY + V + [n]))
body.append(f"  exact e1_omega " + " ".join(A_W + PARAMS + V + RN1))
doc = """/-- **Exact K₅ derivation of the `E₁` obstruction (branch c).**  For every field `L` of characteristic
zero and every root `w` of `R`, the bracket equations of weights −3, −2, −1, 0 (the layers `E₄, E₃, E₂, E₁`
of branch (c), with `A₋₁`, `A₋₂`, `B₋₁`) at the rescaled K₅ top layer imply `Ω(b₁₂,₂₂, b₁₂,₂₃) = 0`. -/"""
main = lemma("omega_descent_K5", B_W + B_TOP + B_vars(Z + X + Y + V) + B_hyps(HN["-3"] + HN["-2"] + HN["-1"] + HN["0"]),
             f"{OMEGA} = 0", body, doc)
files["MainOmega"] = HDR_MAIN + "\n" + main + FTR
import shutil
for sub in ("E2cred", "E2c", "E1red"):
    shutil.rmtree(f"{OUT}/{sub}", ignore_errors=True); os.makedirs(f"{OUT}/{sub}", exist_ok=True)
for n, text in files.items():
    open(f"{OUT}/{n}.lean", "w").write(text)
open(os.path.join(HERE, "modules_c.txt"), "w").write("\n".join(mods + ["Jacobian.BranchC.Descent.MainOmega"]) + "\n")
print(len(files), "files;", sum(len(t) for t in files.values()), "bytes; Omega =", OMEGA[:120], "...")
