"""
gen_rank_c.py -- exact K5 rank certificates for the five branch-(c) layer operators (priority 3) as Lean 4.

For E_n (n = 2, 1, 0, -1, -2) the operator is the part of the weight-(1-n) bracket equations that is linear in
the new layer unknowns (A_{n-3}, B_{n-2}); its rows are the operator rows of the pipeline (rows with no new
unknown are pure conditions and are not part of the operator).  Shapes (rows x unknowns, rank):
  E2 19x20 (18), E1 19x19 (18), E0 18x17 (17), E-1 17x15 (15), E-2 16x13 (13).

Emitted (Jacobian/BranchC/Rank/E<n>.lean), over every field L of characteristic 0 and root w of R:
  opE<n>_piv_<v>  : (M x = 0) -> x_v = sum_f N_{v,f} x_f        (one per pivot; `rank >= r`)
  opE<n>_row_<k>  : row_k vanishes on the graph x_piv = N x_free   (one per row;  `rank <= r`)
  opE<n>_lnull_<i>: sum_e W_{i,e} row_e(x) = 0 identically       (left null vectors; `corank`)
  opE<n>_kernel   : (M x = 0) <-> (x_piv = N x_free)             (so dim ker = #free, rank = r exactly)
The top layer is the rescaled K5 point (certgen/cert.json); ranks are invariant under the torus rescaling,
so they are also the ranks of the pipeline's operators (normalisation a_{2,2} = 1).
"""
import json, os, sys
from fractions import Fraction
from flint import fmpq_poly, fmpq
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "certgen"))
from gen_system import build
Rr = fmpq_poly([26, 0, 3, 3, -1, 1]); ZERO = fmpq_poly([0]); ONE = fmpq_poly([1])
def Kc(c): return fmpq_poly([fmpq(*map(int, s.split('/'))) if '/' in s else fmpq(int(s)) for s in c]) % Rr
def red(a): return a % Rr
def inv(a):
    g, s, _ = a.xgcd(Rr); assert g == 1; return s % Rr
def kstr(a): return [str(a[i]) for i in range(5)]
cert = json.load(open(os.path.join(HERE, "..", "certgen", "cert.json")))
top = {v: Kc(c) for v, c in cert["top"].items()}
NPc = [(0, 0), (1, 0), (8, 14), (8, 16), (0, 8)]; NQc = [(0, 0), (2, 1), (12, 21), (12, 24), (0, 12)]
LPc, LQc, eqsc, _ = build(NPc, NQc)
wt = lambda ij: ij[1] - 2 * ij[0]
def layer_vars(letter, k, lo, hi): return [f"{letter}_{i}_{2*i-k}" for i in range(lo, hi + 1)]
spec = {2: ("E2", "b", 0, 1, 12, "a", -1, 0, 7), 1: ("E1", "a", -2, 0, 6, "b", -1, 0, 11),
        0: ("E0", "a", -3, 0, 5, "b", -2, 0, 10), -1: ("Em1", "a", -4, 0, 4, "b", -3, 0, 9),
        -2: ("Em2", "a", -5, 0, 3, "b", -4, 0, 8)}
EXPECT = {2: (19, 20, 18), 1: (19, 19, 18), 0: (18, 17, 17), -1: (17, 15, 15), -2: (16, 13, 13)}

def rref_with_transform(M, ncols):
    m = len(M)
    A = [M[i][:] + [ONE if j == i else ZERO for j in range(m)] for i in range(m)]
    piv = []; r = 0
    for c in range(ncols):
        i = next((i for i in range(r, m) if A[i][c] != 0), None)
        if i is None: continue
        A[r], A[i] = A[i], A[r]
        iv = inv(A[r][c]); A[r] = [red(x * iv) for x in A[r]]
        for j in range(m):
            if j != r and A[j][c] != 0:
                f = A[j][c]; A[j] = [red(A[j][l] - f * A[r][l]) for l in range(len(A[r]))]
        piv.append(c); r += 1
    return A[:r], piv, [row[ncols:] for row in A[r:]]

def q(s):
    f = Fraction(s)
    if f.denominator == 1: return f"({f.numerator} : L)"
    return f"(({f.numerator}) / {f.denominator} : L)"
def kel(c):
    terms = []
    for i, s in enumerate(c):
        if Fraction(s) == 0: continue
        terms.append(q(s) + ("" if i == 0 else (" * w" if i == 1 else f" * w ^ ({i} : ℕ)")))
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"
def linform(coeffs, vars_):
    parts = [f"{kel(kstr(c))} * {v}" for c, v in zip(coeffs, vars_) if c != 0]
    return "(" + (" + ".join(parts) if parts else "(0 : L)") + ")"
REDL = []
for k in range(5, 13):
    wk = fmpq_poly([0] * k + [1]); qk, rk = divmod(wk, Rr)
    REDL.append((k, kel([str(rk[i]) for i in range(5)]),
                 "(" + " + ".join(f"({qk[i]} : L) * w ^ ({i} : ℕ)" for i in range(qk.degree() + 1)) + ")"))
RED = ", ".join(f"hw{k}" for k, _, _ in REDL)
CLOSE = f"ring_nf <;> (try simp only [{RED}]) <;> (try ring_nf)"
HWLEM = [f"  have hw{k} : w ^ ({k} : ℕ) = {r} := by linear_combination {qq} * hw" for k, r, qq in REDL]
HDR = """import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Algebra.Field.Basic
import Mathlib.Algebra.CharZero.Defs

/-! Generated by certgen_c/gen_rank_c.py -- exact K₅ rank certificate for the branch-(c) layer operator
  {name} ({m} × {n}, rank {r}) at the rescaled K₅ top layer (certgen/cert.json).  Ranks are invariant under
  the torus rescaling to the pipeline's normalisation (a₂,₂ = 1).  Rows: bracket monomials {rows}.
  Unknowns: {unk}. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace BranchC.Rank
"""
OUT = os.path.join(HERE, "..", "Jacobian", "BranchC", "Rank")
import shutil
shutil.rmtree(OUT, ignore_errors=True); os.makedirs(OUT, exist_ok=True)
ALLMODS = []
summary = {}
for n, (tag, l1, k1, lo1, hi1, l2, k2, lo2, hi2) in spec.items():
    U = layer_vars(l1, k1, lo1, hi1) + layer_vars(l2, k2, lo2, hi2)
    W = 1 - n
    rows_all = sorted(k for k in eqsc if wt(k) == W)
    idx = {u: i for i, u in enumerate(U)}
    M = []; rows = []
    for k in rows_all:
        row = [ZERO] * len(U)
        for c, pv, qv in eqsc[k]:
            for a, b in ((pv, qv), (qv, pv)):
                if a in idx and b in top:
                    row[idx[a]] = red(row[idx[a]] + c * top[b])
        if any(x != 0 for x in row): M.append(row); rows.append(k)
    A, piv, null = rref_with_transform(M, len(U))
    m, nU, r = len(M), len(U), len(piv)
    assert (m, nU, r) == EXPECT[n], (n, m, nU, r)
    free = [c for c in range(nU) if c not in piv]
    # pivot relations x_p = sum_f N_{p,f} x_f  and their multipliers
    PIV = []
    for row, pc in zip(A, piv):
        Rw, Ew = row[:nU], row[nU:]
        N = {f: red(-Rw[f]) for f in free if Rw[f] != 0}
        # check: x_p - sum N x_f = sum_e Ew_e row_e(x)  (as linear forms)
        for c in range(nU):
            lhs = ONE if c == pc else (red(-N.get(c, ZERO)) if c in free else ZERO)
            rhs = ZERO
            for e in range(m): rhs = red(rhs + Ew[e] * M[e][c])
            assert red(lhs - rhs) == 0
        PIV.append((pc, N, Ew))
    for wv in null:   # left null vectors
        for c in range(nU):
            s = ZERO
            for e in range(m): s = red(s + wv[e] * M[e][c])
            assert s == 0
    # graph in kernel: row_e(x_piv := N x_free) = 0
    for e in range(m):
        for f in free:
            s = M[e][f]
            for pc, N, _ in PIV: s = red(s + M[e][pc] * N.get(f, ZERO))
            assert s == 0
    summary[tag] = dict(shape=[m, nU], rank=r, free=[U[f] for f in free], left_null=len(null), rows=[list(k) for k in rows])
    print(f"{tag}: {m}x{nU} rank {r}; free {[U[f] for f in free]}; left nullity {len(null)}  -- certificates verified")
    # ---------------- Lean
    rowexpr = [linform(M[e], U) for e in range(m)]
    B_W = ["(w : L)", "(hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)"]
    B_X = ["(" + " ".join(U) + " : L)"]
    B_ROWS = [f"(h{e} : {rowexpr[e]} = 0)" for e in range(m)]
    def piv_rhs(N): return linform([N.get(f, ZERO) for f in free], [U[f] for f in free])
    hdr = HDR.format(name=tag, m=m, n=nU, r=r, rows=", ".join(f"x^{k[0]}y^{k[1]}" for k in rows), unk=" ".join(U))
    os.makedirs(os.path.join(OUT, tag), exist_ok=True)
    mods = []
    def emit(fname, text, imports=()):
        h = hdr
        if imports:
            h = h.replace("import Mathlib.Tactic.LinearCombination\n",
                          "import Mathlib.Tactic.LinearCombination\n" + "".join(f"import {i}\n" for i in imports))
        open(os.path.join(OUT, tag, fname + ".lean"), "w").write(h + "\n" + text + "\nend BranchC.Rank\n")
        mods.append(f"Jacobian.BranchC.Rank.{tag}.{fname}")
    def lem(name, binders, concl, body, doc=None):
        s_ = ([doc] if doc else []) + [f"theorem {name} {{L : Type*}} [Field L] [CharZero L]"] + ["    " + b for b in binders]
        s_[-1] += f" :\n    {concl} := by"
        return "\n".join(s_ + body) + "\n"
    for pc, N, Ew in PIV:
        lc = " + ".join(f"{kel(kstr(Ew[e]))} * h{e}" for e in range(m) if Ew[e] != 0)
        emit(f"piv_{U[pc]}", lem(f"op{tag}_piv_{U[pc]}", B_W + B_X + B_ROWS, f"{U[pc]} = {piv_rhs(N)}",
                       HWLEM + [f"  linear_combination (norm := skip) {lc}", f"  {CLOSE}"]))
    FV = [U[f] for f in free]
    pivN = {pc: N for pc, N, _ in PIV}
    rowtxt = []
    for e in range(m):
        terms = []
        for c in range(nU):
            if M[e][c] == 0: continue
            terms.append(f"{kel(kstr(M[e][c]))} * {U[c] if c in free else piv_rhs(pivN[c])}")
        full = "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"
        stmt_vars = ["(" + " ".join(FV) + " : L)"] if FV else []
        rowtxt.append(lem(f"op{tag}_row_{e}", B_W + stmt_vars, f"{full} = 0", HWLEM + [f"  {CLOSE}"]))
    emit("rows", "\n".join(rowtxt))
    ln = []
    for i, wv in enumerate(null):
        comb = " + ".join(f"{kel(kstr(wv[e]))} * {rowexpr[e]}" for e in range(m) if wv[e] != 0)
        ln.append(lem(f"op{tag}_lnull_{i}", B_W + B_X, f"{comb} = 0", HWLEM + [f"  {CLOSE}"],
                       f"/-- Left null vector {i} of the `{tag}` operator: the combination vanishes identically. -/"))
    emit("lnull", "\n".join(ln))
    lhs = " ∧ ".join(f"{rowexpr[e]} = 0" for e in range(m))
    rhs = " ∧ ".join(f"{U[pc]} = {piv_rhs(N)}" for pc, N, _ in PIV)
    fw = ["  constructor", "  · rintro ⟨" + ", ".join(f"h{e}" for e in range(m)) + "⟩",
          "    exact ⟨" + ", ".join(f"op{tag}_piv_{U[pc]} " + " ".join(["w", "hw"] + U + [f"h{e}" for e in range(m)]) for pc, _, _ in PIV) + "⟩",
          "  · rintro ⟨" + ", ".join(f"g{pc}" for pc, _, _ in PIV) + "⟩",
          "    " + " ".join(f"subst g{pc};" for pc, _, _ in PIV).rstrip(";"),
          "    exact ⟨" + ", ".join(f"op{tag}_row_{e} " + " ".join(["w", "hw"] + FV) for e in range(m)) + "⟩"]
    doc = (f"/-- **The `{tag}` operator ({m} × {nU}) has rank exactly {r}** over every field of characteristic 0 "
           f"containing a root `w` of `R`: its kernel is the graph of the free unknowns {', '.join(FV) if FV else '(none: injective)'}. -/")
    emit("Kernel", lem(f"op{tag}_kernel", B_W + B_X, f"({lhs}) ↔ ({rhs})", fw, doc), imports=list(mods))
    ALLMODS.extend(mods)
json.dump(summary, open(os.path.join(HERE, "rank_c.json"), "w"), indent=1)
open(os.path.join(HERE, "modules_rank_c.txt"), "w").write("\n".join(ALLMODS) + "\n")
print("wrote", len(ALLMODS), "modules")
