"""
gen_t1zero_lean.py -- writes Jacobian/BranchC/T1Zero/*.lean from the certificates of gen_t1zero_c.py (imported; every
identity is re-checked there by exact integer arithmetic before anything is written).

Modules (namespace BranchC.T1Zero; imports only Jacobian.ChartProof.Reflect, so independent of the Descent2R chain):
  Defs      lc_zero2, cancel_int, eR, the condition copies ck_* (identical Exprs to Descent2R.ek_*: checked below
            through their mirrors, which must equal bridge_c.json's CONCL strings), eT1, eT2, eX, e_sq, f_*
  Sq        s_sq, s_X2                  Omega = o1 (S2 - kappa)^2 on T2 = 1; o1(w) != 0 by a Bezout identity
  F_<n>     s_f_<n>                     the six conditions on the slice T1 = 0, T2 = 1, S2 = kappa
  P_<n>     p_<n>, s_p_<n>              nu_n * f_n mod R (nu_n from the step-1 certificate certB_lowerc.json)
  Final     s_final
  Main      chartEmpty_t1_zero (hypotheses: the conditions as `BranchC.cond_*`, Jacobian/BranchC/CondsC.lean)
Environment: WRITE=0 checks without writing.
"""
import os, sys, json, shutil
sys.set_int_max_str_digits(0)
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import gen_t1zero_c as C

V, IDX, facts, steps, NAMES, EK = C.V, C.IDX, C.facts, C.steps, C.NAMES, C.EK
Dk, DO, cB, DD, slice_facts = C.Dk, C.DO, C.cB, C.DD, C.slice_facts

def term_expr(key, c):                                        # = gen_refl_c.term_expr
    m, i = key; out = f"(.num ({c}))"
    fs = ([("w", i)] if i else []) + list(m)
    for v, e in fs: out = f"(.mul {out} {'(.var %d)' % IDX[v] if e == 1 else '(.pow (.var %d) %d)' % (IDX[v], e)})"
    return out
def term_lean(key, c):                                        # = gen_refl_c.term_lean (mirror of Expr.denote)
    m, i = key; out = f"({c} : L)"
    fs = ([("w", i)] if i else []) + list(m)
    for v, e in fs: out = f"({out} * {v if e == 1 else '%s ^ %d' % (v, e)})"
    return out
def balanced(ts, op_):
    if not ts: return None
    while len(ts) > 1: ts = [op_(ts[j], ts[j + 1]) if j + 1 < len(ts) else ts[j] for j in range(0, len(ts), 2)]
    return ts[0]
def pe(P): return balanced([term_expr(k, v) for k, v in sorted(P.items(), key=repr)], lambda a, b: f"(.add {a} {b})") or "(.num 0)"
def pl(P): return balanced([term_lean(k, v) for k, v in sorted(P.items(), key=repr)], lambda a, b: f"({a} + {b})") or "(0 : L)"

b = json.load(open(os.path.join(HERE, "bridge_c.json")))
MIR = {f: m for f, n, m in b["CONCL"]}
assert b["ALLV"][:8] == V, b["ALLV"][:8]
for n in ["Omega"] + NAMES:     # ck_n = the chain's ek_n: same polynomial, term order and tree (so the mirrors agree)
    assert pl(EK[n][1]) == MIR["ek_" + n], n
print("mirrors of the 7 condition copies == bridge_c.json CONCL mirrors (Descent2R.ek_*): OK")

NS = "BranchC.T1Zero"
MOD = "Jacobian.BranchC.T1Zero."
HDR = """/-! Generated by certgen_c/gen_t1zero_lean.py ({doc}).  Branch (c), chart stratum `b₁₁,₂₀ = 0`: a kernel-checked
certificate.  Every polynomial identity is checked by the Lean kernel (`decide +kernel`, no `native_decide`) and was
checked in Python by exact integer arithmetic (certgen_c/gen_t1zero_c.py) before emission.  No `sorry`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace {ns}
open Lean.Grind.CommRing BranchAb.ChartProof

variable {{α : Type*}} [CommRing α]
"""
files = {}
def emit(mod, imports, doc, body):
    files[mod] = "\n".join(f"import {i}" for i in imports) + "\n\n" + HDR.format(doc=doc, ns=NS) + "\n" + "\n".join(body) + f"\nend {NS}\n"

LIB = r"""/-- `Σ eᵢ·cᵢ` with the fact first (`mulK` recurses on its first factor, so the factor with fewer terms goes first). -/
noncomputable def lcExprR (l : List (Expr × Expr)) : Expr :=
  List.rec (.num 0) (fun p _ ih => .add (.mul p.2 p.1) ih) l

theorem denote_lcExprR (ctx : Context α) (l : List (Expr × Expr)) (h : AllZero ctx l) :
    (lcExprR l).denote ctx = 0 := by
  induction l with
  | nil => show denoteInt 0 = (0 : α); simp [denoteInt_eq]
  | cons p l ih =>
    obtain ⟨h1, h2⟩ := h
    show (p.2.denote ctx) * (p.1.denote ctx) + (lcExprR l).denote ctx = 0
    rw [h1, ih h2]; simp

/-- `lc_zero` with two lists: products `cᵢ·eᵢ` (list `l₁`) and `eᵢ·cᵢ` (list `l₂`). -/
theorem lc_zero2 (ctx : Context α) (g : Expr) (l₁ l₂ : List (Expr × Expr))
    (hcert : Poly.beq' (toPolyK (.sub g (.add (lcExpr l₁) (lcExprR l₂)))) (.num 0) = true)
    (h₁ : AllZero ctx l₁) (h₂ : AllZero ctx l₂) : g.denote ctx = 0 := by
  rw [eq_of_toPolyK ctx g _ hcert]
  show (lcExpr l₁).denote ctx + (lcExprR l₂).denote ctx = 0
  rw [denote_lcExpr ctx l₁ h₁, denote_lcExprR ctx l₂ h₂, add_zero]

/-- Cancel a nonzero integer factor (characteristic 0). -/
theorem cancel_int {L : Type*} [Field L] [CharZero L] (ctx : Context L) (e : Expr) (k : Int) (hk : k ≠ 0)
    (h : (Expr.mul (.num k) e).denote ctx = 0) : e.denote ctx = 0 := by
  have h1 : denoteInt (α := L) k * e.denote ctx = 0 := h
  rw [denoteInt_eq] at h1
  exact (mul_eq_zero.mp h1).resolve_left (Int.cast_ne_zero.mpr hk)

/-- `R(w) = w⁵ − w⁴ + 3w³ + 3w² + 26` (the same `Expr` as `Descent2R.eR`). -/
noncomputable def eR : Expr :=
  (.add (.add (.add (.sub (.pow (.var 0) 5) (.pow (.var 0) 4)) (.mul (.num 3) (.pow (.var 0) 3))) (.mul (.num 3) (.pow (.var 0) 2))) (.num 26))
"""
DOCS = {"eT1": "`b₁₁,₂₀` (the stratum)", "eT2": "`b₁₂,₂₂ − 1` (the chart)",
        "eX": f"`X = {Dk}·b₁₂,₂₃ − Nκ(w)` = `{Dk}·(b₁₂,₂₃ − κ(w))`",
        "e_sq": f"`{DO}·No₁(w)·X²` (`Ω = o₁(S₂ − κT₂²)²` on the chart)"}
for n in ["Omega"] + NAMES:
    DOCS["ck_" + n] = f"`{EK[n][0]}·{n}`: lower_c's condition (certgen_c/conds_c.json); the same `Expr` as `Descent2R.ek_{n}`"
for n in NAMES:
    DOCS["f_" + n] = f"`{Dk}^{slice_facts[n][0]}·ck_{n}` on the slice `b₁₁,₂₀ = 0`, `b₁₂,₂₂ = 1`, `b₁₂,₂₃ = κ(w)`, reduced mod `R`"
RN = {"ek_" + n: "ck_" + n for n in ["Omega"] + NAMES}
def fn(f): return RN.get(f, f)
defs = [LIB]
for nm in ["ck_" + n for n in ["Omega"] + NAMES] + ["eT1", "eT2", "eX", "e_sq"] + [f"f_{n}" for n in NAMES]:
    P = facts["ek_" + nm[3:]] if nm.startswith("ck_") else facts[nm]
    defs.append(f"/-- {DOCS[nm]} -/\nnoncomputable def {nm} : Expr :=\n  {pe(P)}\n")
emit(MOD + "Defs", ["Jacobian.ChartProof.Reflect"], "definitions", defs)

def tgt_expr(t):
    if isinstance(t, tuple) and t[0] == "X2": return f"(Expr.mul (.num {t[1]}) (Expr.pow eX 2))"
    if isinstance(t, tuple) and t[0] == "num": return f"(Expr.num {t[1]})"
    return t
def cost(a, b): return a * (b + a * b)                        # mulK with a first factor of a terms (rough bound)
EST = {}
def thm(name, t, cl, doc):
    l1, l2, est = [], [], 0
    for m, f in cl:
        if not m: continue
        nf = len(facts[f])
        if len(m) <= nf: l1.append((m, f)); est += cost(len(m), nf)
        else: l2.append((m, f)); est += cost(nf, len(m))
    EST[name] = est
    hyps = " ".join(f"(h_{fn(f)} : {fn(f)}.denote ctx = 0)" for m, f in cl if m)
    s1 = ", ".join(f"({pe(m)}, {fn(f)})" for m, f in l1)
    s2 = ", ".join(f"({pe(m)}, {fn(f)})" for m, f in l2)
    a1 = ("⟨" + "".join(f"h_{fn(f)}, " for m, f in l1) + "trivial⟩") if l1 else "trivial"
    a2 = ("⟨" + "".join(f"h_{fn(f)}, " for m, f in l2) + "trivial⟩") if l2 else "trivial"
    return (f"/-- {doc} -/\ntheorem {name} (ctx : Context α) {hyps} :\n    {tgt_expr(t)}.denote ctx = 0 :=\n"
            f"  lc_zero2 ctx {tgt_expr(t)} [{s1}] [{s2}] (by decide +kernel) {a1} {a2}\n")

S = {s[0]: s for s in steps}
emit(MOD + "Sq", [MOD + "Defs"], "Ω on the chart", [
    thm("s_sq", "e_sq", S["s_sq"][2], "`Ω = o₁(S₂ − κT₂²)²` on `b₁₂,₂₂ = 1`, mod `R`"),
    thm("s_X2", ("X2", cB * DO), S["s_X2"][2], f"`a(w)·No₁(w) + b(w)·R(w) = {cB}` (Bezout): `o₁(w) ≠ 0`, so `X² = 0`")])
for n in NAMES:
    emit(MOD + f"F_{n}", [MOD + "Defs"], f"{n} on the slice",
         [thm(f"s_f_{n}", f"f_{n}", S[f"s_f_{n}"][2], f"`{n}` restricted to `b₁₁,₂₀ = 0`, `b₁₂,₂₂ = 1`, `b₁₂,₂₃ = κ(w)`")])
for n in NAMES:
    emit(MOD + f"P_{n}", [MOD + "Defs"], f"certificate part {n}",
         [f"/-- `ν_{n}·f_{n}` mod `R`; `ν_{n}` = the step-1 cofactor of `{n}` (certB_lowerc.json) times "
          f"`DD/({Dk}^{slice_facts[n][0]}·{EK[n][0]})` -/\nnoncomputable def p_{n} : Expr :=\n  {pe(facts['p_' + n])}\n",
          thm(f"s_p_{n}", f"p_{n}", S[f"s_p_{n}"][2], f"part `{n}` of the slice certificate")])

ctx = ("(.branch 4 (.branch 2 (.branch 1 (.leaf w) (.leaf b_11_20)) (.branch 3 (.leaf b_12_22) (.leaf b_11_21))) "
       "(.branch 6 (.branch 5 (.leaf b_12_23) (.leaf a_6_13)) (.branch 7 (.leaf a_7_15) (.leaf b_10_21))))")
fin = S["s_final"][2]
hy = [f"(c_{n} : cond_{n} w {' '.join(V[1:])} = 0)" for n in ["Omega"] + NAMES]      # Jacobian/BranchC/CondsC.lean
body = [f"  let ctx : Context L := {ctx}",
        "  have f_eR : eR.denote ctx = 0 := hw",
        f"  have f_eT1 : eT1.denote ctx = 0 := by\n    have h : {pl(facts['eT1'])} = 0 := by rw [ht1]; ring\n    exact h",
        f"  have f_eT2 : eT2.denote ctx = 0 := by\n    have h : {pl(facts['eT2'])} = 0 := by rw [ht2]; ring\n    exact h"]
body += [f"  have f_ck_{n} : ck_{n}.denote ctx = 0 := c_{n}" for n in ["Omega"] + NAMES]
body += ["  have f_e_sq := s_sq ctx f_ck_Omega f_eT2 f_eR",
         f"  have hX2 : (Expr.pow eX 2).denote ctx = 0 :=\n    cancel_int ctx (Expr.pow eX 2) {cB * DO} (by decide) (s_X2 ctx f_e_sq f_eR)",
         "  have hX2' : eX.denote ctx ^ 2 = 0 := hX2",
         "  have f_eX : eX.denote ctx = 0 := (pow_eq_zero_iff two_ne_zero).mp hX2'"]
for n in NAMES:
    body.append(f"  have f_f_{n} := s_f_{n} ctx f_ck_{n} f_eT1 f_eT2 f_eX f_eR")
for n in NAMES:
    body.append(f"  have f_p_{n} := s_p_{n} ctx f_f_{n} f_eR")
body += ["  have h0 := s_final ctx " + " ".join(f"f_{fn(f)}" for m, f in fin if m),
         f"  have h1 : denoteInt (α := L) {DD} = 0 := h0",
         "  rw [denoteInt_eq] at h1",
         "  exact absurd (Int.cast_eq_zero.mp h1) (by decide)"]
MAIN_DOC = """/-- **Branch (c), chart stratum `b₁₁,₂₀ = 0` (kernel-checked).**  No `w` with `R(w) = 0` and no point with
`b₁₁,₂₀ = 0`, `b₁₂,₂₂ = 1` make lower_c's conditions `cond_Omega, cond_Psi, …, cond_Theta3` (CondsC.lean) vanish. -/"""
emit(MOD + "Final", [MOD + f"P_{n}" for n in NAMES], "the final identity", [
    thm("s_final", ("num", DD), fin, f"`Σₙ p_n = DD` ({len(str(DD))} digits): the slice certificate `1 = Σ Lₙ·Fₙ` of step 1")])
emit(MOD + "Main", ["Jacobian.BranchC.CondsC", MOD + "Sq"] + [MOD + f"F_{n}" for n in NAMES] + [MOD + "Final"],
     "the stratum theorem", [
    MAIN_DOC + """
theorem chartEmpty_t1_zero {L : Type*} [Field L] [CharZero L] (w : L)
    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)
    (b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 : L) (ht1 : b_11_20 = 0) (ht2 : b_12_22 = 1)
    """ + "\n    ".join(hy) + " :\n    False := by\n" + "\n".join(body) + "\n"])

ODIR = os.path.join(HERE, "..", "Jacobian", "BranchC", "T1Zero")
if os.environ.get("WRITE", "1") == "1":
    if os.path.isdir(ODIR): shutil.rmtree(ODIR)
    os.makedirs(ODIR)
    for mod, txt in files.items():
        open(os.path.join(HERE, "..", *mod.split(".")) + ".lean", "w").write(txt)
    json.dump({"modules": list(files), "estimates": EST, "DD_digits": len(str(DD)), "Dk": Dk, "cB": str(cB), "DO": DO},
              open(os.path.join(HERE, "t1zero_c.json"), "w"), indent=1)
for mod, txt in files.items(): print(f"  {mod}: {len(txt)} bytes")
print("merge-work estimates:", EST)
