import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec4_18_33_1 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.mul (.num (77520)) (.var 14)) (.var 2)) (.mul (.mul (.num (-69768)) (.var 33)) (.var 26))) (.add (.mul (.num (-6617695968)) (.var 33)) (.mul (.mul (.num (-4474548000)) (.var 0)) (.var 33)))) (.add (.add (.mul (.mul (.num (1258138512)) (.pow (.var 0) 2)) (.var 33)) (.mul (.mul (.num (-116886816)) (.pow (.var 0) 3)) (.var 33))) (.add (.mul (.mul (.num (-632397744)) (.pow (.var 0) 4)) (.var 33)) (.mul (.mul (.num (46512)) (.var 15)) (.var 1))))) (.add (.add (.add (.mul (.mul (.num (-100776)) (.var 34)) (.var 25)) (.mul (.num (-46713008784)) (.var 34))) (.add (.mul (.mul (.num (8234207280)) (.var 0)) (.var 34)) (.mul (.mul (.num (6726730296)) (.pow (.var 0) 2)) (.var 34)))) (.add (.add (.mul (.mul (.num (-7606064544)) (.pow (.var 0) 3)) (.var 34)) (.mul (.mul (.num (869523720)) (.pow (.var 0) 4)) (.var 34))) (.add (.mul (.num (-325882908)) (.var 1)) (.mul (.mul (.num (-215053020)) (.var 0)) (.var 1)))))) (.add (.add (.add (.mul (.mul (.num (59703282)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (-4306464)) (.pow (.var 0) 3)) (.var 1))) (.add (.mul (.mul (.num (-28311786)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (-1777214400)) (.var 2)))) (.add (.add (.mul (.mul (.num (236764320)) (.var 0)) (.var 2)) (.mul (.mul (.num (221488320)) (.pow (.var 0) 2)) (.var 2))) (.add (.mul (.mul (.num (-288369840)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (29526000)) (.pow (.var 0) 4)) (.var 2))))))

theorem s_ec4_18_33_1 (ctx : Context α) (h_et_a_7_12 : et_a_7_12.denote ctx = 0) (h_et_b_12_21 : et_b_12_21.denote ctx = 0) (h_et_a_8_14 : et_a_8_14.denote ctx = 0) (h_et_b_11_19 : et_b_11_19.denote ctx = 0) :
    ec4_18_33_1.denote ctx = 0 :=
  lc_zero ctx ec4_18_33_1 [((.mul (.num (4560)) (.var 2)), et_a_7_12), ((.mul (.num (-72)) (.var 33)), et_b_12_21), ((.mul (.num (342)) (.var 1)), et_a_8_14), ((.mul (.num (-312)) (.var 34)), et_b_11_19)] (by decide +kernel) ⟨h_et_a_7_12, h_et_b_12_21, h_et_a_8_14, h_et_b_11_19, trivial⟩

end BranchC.Descent2R
