import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec4_19_35_1 : Expr :=
  (.add (.add (.add (.add (.mul (.mul (.num (62016)) (.var 15)) (.var 2)) (.mul (.mul (.num (-93024)) (.var 34)) (.var 26))) (.add (.mul (.num (-8823594624)) (.var 34)) (.mul (.mul (.num (-5966064000)) (.var 0)) (.var 34)))) (.add (.add (.mul (.mul (.num (1677518016)) (.pow (.var 0) 2)) (.var 34)) (.mul (.mul (.num (-155849088)) (.pow (.var 0) 3)) (.var 34))) (.add (.mul (.mul (.num (-843196992)) (.pow (.var 0) 4)) (.var 34)) (.mul (.num (-434510544)) (.var 2))))) (.add (.add (.mul (.mul (.num (-286737360)) (.var 0)) (.var 2)) (.mul (.mul (.num (79604376)) (.pow (.var 0) 2)) (.var 2))) (.add (.mul (.mul (.num (-5741952)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (-37749048)) (.pow (.var 0) 4)) (.var 2)))))

theorem s_ec4_19_35_1 (ctx : Context α) (h_et_a_8_14 : et_a_8_14.denote ctx = 0) (h_et_b_12_21 : et_b_12_21.denote ctx = 0) :
    ec4_19_35_1.denote ctx = 0 :=
  lc_zero ctx ec4_19_35_1 [((.mul (.num (456)) (.var 2)), et_a_8_14), ((.mul (.num (-96)) (.var 34)), et_b_12_21)] (by decide +kernel) ⟨h_et_a_8_14, h_et_b_12_21, trivial⟩

end BranchC.Descent2R
