import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec4_3_3_1 : Expr :=
  (.add (.add (.mul (.mul (.num (4)) (.var 8)) (.var 36)) (.mul (.mul (.num (-4)) (.var 28)) (.var 16))) (.add (.mul (.num (4)) (.var 28)) (.mul (.num (-4)) (.var 36))))

theorem s_ec4_3_3_1 (ctx : Context α) (h_et_a_1_0 : et_a_1_0.denote ctx = 0) (h_et_b_2_1 : et_b_2_1.denote ctx = 0) :
    ec4_3_3_1.denote ctx = 0 :=
  lc_zero ctx ec4_3_3_1 [((.mul (.num (4)) (.var 36)), et_a_1_0), ((.mul (.num (-4)) (.var 28)), et_b_2_1)] (by decide +kernel) ⟨h_et_a_1_0, h_et_b_2_1, trivial⟩

end BranchC.Descent2R
