import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec4_4_5_1 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.mul (.num (2304)) (.var 8)) (.var 37)) (.mul (.mul (.num (384)) (.var 27)) (.var 18))) (.add (.mul (.num (-7560)) (.var 27)) (.mul (.mul (.num (-33264)) (.var 0)) (.var 27)))) (.add (.add (.mul (.mul (.num (7056)) (.pow (.var 0) 2)) (.var 27)) (.mul (.mul (.num (9072)) (.pow (.var 0) 3)) (.var 27))) (.add (.mul (.mul (.num (-3528)) (.pow (.var 0) 4)) (.var 27)) (.mul (.mul (.num (768)) (.var 9)) (.var 36))))) (.add (.add (.add (.mul (.mul (.num (-1152)) (.var 28)) (.var 17)) (.mul (.num (14544)) (.var 28))) (.add (.mul (.mul (.num (5274)) (.var 0)) (.var 28)) (.mul (.mul (.num (-2334)) (.pow (.var 0) 2)) (.var 28)))) (.add (.add (.mul (.mul (.num (-306)) (.pow (.var 0) 3)) (.var 28)) (.mul (.mul (.num (294)) (.pow (.var 0) 4)) (.var 28))) (.add (.mul (.mul (.num (-768)) (.var 10)) (.var 35)) (.mul (.mul (.num (-2688)) (.var 29)) (.var 16)))))) (.add (.add (.add (.add (.mul (.num (2688)) (.var 29)) (.mul (.num (15120)) (.var 35))) (.add (.mul (.mul (.num (66528)) (.var 0)) (.var 35)) (.mul (.mul (.num (-14112)) (.pow (.var 0) 2)) (.var 35)))) (.add (.add (.mul (.mul (.num (-18144)) (.pow (.var 0) 3)) (.var 35)) (.mul (.mul (.num (7056)) (.pow (.var 0) 4)) (.var 35))) (.add (.mul (.num (-14544)) (.var 36)) (.mul (.mul (.num (-5274)) (.var 0)) (.var 36))))) (.add (.add (.mul (.mul (.num (2334)) (.pow (.var 0) 2)) (.var 36)) (.mul (.mul (.num (306)) (.pow (.var 0) 3)) (.var 36))) (.add (.mul (.mul (.num (-294)) (.pow (.var 0) 4)) (.var 36)) (.mul (.num (-2304)) (.var 37))))))

theorem s_ec4_4_5_1 (ctx : Context α) (h_et_a_1_0 : et_a_1_0.denote ctx = 0) (h_et_b_4_5 : et_b_4_5.denote ctx = 0) (h_et_a_2_2 : et_a_2_2.denote ctx = 0) (h_et_b_3_3 : et_b_3_3.denote ctx = 0) (h_et_a_3_4 : et_a_3_4.denote ctx = 0) (h_et_b_2_1 : et_b_2_1.denote ctx = 0) :
    ec4_4_5_1.denote ctx = 0 :=
  lc_zero ctx ec4_4_5_1 [((.mul (.num (2304)) (.var 37)), et_a_1_0), ((.mul (.num (24)) (.var 27)), et_b_4_5), ((.mul (.num (6)) (.var 36)), et_a_2_2), ((.mul (.num (-6)) (.var 28)), et_b_3_3), ((.mul (.num (-48)) (.var 35)), et_a_3_4), ((.mul (.num (-2688)) (.var 29)), et_b_2_1)] (by decide +kernel) ⟨h_et_a_1_0, h_et_b_4_5, h_et_a_2_2, h_et_b_3_3, h_et_a_3_4, h_et_b_2_1, trivial⟩

end BranchC.Descent2R
