import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec4_5_7_1 : Expr :=
  (.add (.add (.add (.add (.add (.add (.mul (.mul (.num (3072)) (.var 8)) (.var 38)) (.mul (.mul (.num (768)) (.var 27)) (.var 19))) (.add (.mul (.num (1092384)) (.var 27)) (.mul (.mul (.num (-404064)) (.var 0)) (.var 27)))) (.add (.add (.mul (.mul (.num (-50544)) (.pow (.var 0) 2)) (.var 27)) (.mul (.mul (.num (261504)) (.pow (.var 0) 3)) (.var 27))) (.add (.mul (.mul (.num (-54864)) (.pow (.var 0) 4)) (.var 27)) (.mul (.mul (.num (1536)) (.var 9)) (.var 37))))) (.add (.add (.add (.mul (.mul (.num (-768)) (.var 28)) (.var 18)) (.mul (.num (15120)) (.var 28))) (.add (.mul (.mul (.num (66528)) (.var 0)) (.var 28)) (.mul (.mul (.num (-14112)) (.pow (.var 0) 2)) (.var 28)))) (.add (.add (.mul (.mul (.num (-18144)) (.pow (.var 0) 3)) (.var 28)) (.mul (.mul (.num (7056)) (.pow (.var 0) 4)) (.var 28))) (.add (.mul (.mul (.num (-2304)) (.var 29)) (.var 17)) (.mul (.num (29088)) (.var 29)))))) (.add (.add (.add (.add (.mul (.mul (.num (10548)) (.var 0)) (.var 29)) (.mul (.mul (.num (-4668)) (.pow (.var 0) 2)) (.var 29))) (.add (.mul (.mul (.num (-612)) (.pow (.var 0) 3)) (.var 29)) (.mul (.mul (.num (588)) (.pow (.var 0) 4)) (.var 29)))) (.add (.add (.mul (.mul (.num (-1536)) (.var 11)) (.var 35)) (.mul (.mul (.num (-3840)) (.var 30)) (.var 16))) (.add (.mul (.num (3840)) (.var 30)) (.mul (.num (-1911672)) (.var 35))))) (.add (.add (.add (.mul (.mul (.num (707112)) (.var 0)) (.var 35)) (.mul (.mul (.num (88452)) (.pow (.var 0) 2)) (.var 35))) (.add (.mul (.mul (.num (-457632)) (.pow (.var 0) 3)) (.var 35)) (.mul (.mul (.num (96012)) (.pow (.var 0) 4)) (.var 35)))) (.add (.add (.mul (.num (-29088)) (.var 37)) (.mul (.mul (.num (-10548)) (.var 0)) (.var 37))) (.add (.mul (.mul (.num (4668)) (.pow (.var 0) 2)) (.var 37)) (.mul (.mul (.num (612)) (.pow (.var 0) 3)) (.var 37))))))) (.add (.mul (.mul (.num (-588)) (.pow (.var 0) 4)) (.var 37)) (.mul (.num (-3072)) (.var 38))))

theorem s_ec4_5_7_1 (ctx : Context α) (h_et_a_1_0 : et_a_1_0.denote ctx = 0) (h_et_b_5_7 : et_b_5_7.denote ctx = 0) (h_et_a_2_2 : et_a_2_2.denote ctx = 0) (h_et_b_4_5 : et_b_4_5.denote ctx = 0) (h_et_b_3_3 : et_b_3_3.denote ctx = 0) (h_et_a_4_6 : et_a_4_6.denote ctx = 0) (h_et_b_2_1 : et_b_2_1.denote ctx = 0) :
    ec4_5_7_1.denote ctx = 0 :=
  lc_zero ctx ec4_5_7_1 [((.mul (.num (3072)) (.var 38)), et_a_1_0), ((.mul (.num (48)) (.var 27)), et_b_5_7), ((.mul (.num (12)) (.var 37)), et_a_2_2), ((.mul (.num (-48)) (.var 28)), et_b_4_5), ((.mul (.num (-12)) (.var 29)), et_b_3_3), ((.mul (.num (-12)) (.var 35)), et_a_4_6), ((.mul (.num (-3840)) (.var 30)), et_b_2_1)] (by decide +kernel) ⟨h_et_a_1_0, h_et_b_5_7, h_et_a_2_2, h_et_b_4_5, h_et_b_3_3, h_et_a_4_6, h_et_b_2_1, trivial⟩

end BranchC.Descent2R
