import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L4.C_2_1_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er4_2_1 : Expr :=
  (.add (.mul (.num (-1)) (.var 27)) (.mul (.num (2)) (.var 35)))

theorem s_er4_2_1 (ctx : Context α) (h_eh4_2_1 : eh4_2_1.denote ctx = 0) (h_ec4_2_1_1 : ec4_2_1_1.denote ctx = 0) :
    er4_2_1.denote ctx = 0 :=
  lc_zero ctx er4_2_1 [((.num (1)), eh4_2_1), ((.num (-1)), ec4_2_1_1)] (by decide +kernel) ⟨h_eh4_2_1, h_ec4_2_1_1, trivial⟩

end BranchC.Descent2R
