import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L4.C_4_5_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er4_4_5 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num (1260)) (.var 27)) (.mul (.mul (.num (5544)) (.var 0)) (.var 27))) (.add (.mul (.mul (.num (-1176)) (.pow (.var 0) 2)) (.var 27)) (.mul (.mul (.num (-1512)) (.pow (.var 0) 3)) (.var 27)))) (.add (.add (.mul (.mul (.num (588)) (.pow (.var 0) 4)) (.var 27)) (.mul (.num (-2424)) (.var 28))) (.add (.mul (.mul (.num (-879)) (.var 0)) (.var 28)) (.mul (.mul (.num (389)) (.pow (.var 0) 2)) (.var 28))))) (.add (.add (.add (.mul (.mul (.num (51)) (.pow (.var 0) 3)) (.var 28)) (.mul (.mul (.num (-49)) (.pow (.var 0) 4)) (.var 28))) (.add (.mul (.num (-448)) (.var 29)) (.mul (.num (-2520)) (.var 35)))) (.add (.add (.mul (.mul (.num (-11088)) (.var 0)) (.var 35)) (.mul (.mul (.num (2352)) (.pow (.var 0) 2)) (.var 35))) (.add (.mul (.mul (.num (3024)) (.pow (.var 0) 3)) (.var 35)) (.mul (.mul (.num (-1176)) (.pow (.var 0) 4)) (.var 35)))))) (.add (.add (.add (.mul (.num (2424)) (.var 36)) (.mul (.mul (.num (879)) (.var 0)) (.var 36))) (.add (.mul (.mul (.num (-389)) (.pow (.var 0) 2)) (.var 36)) (.mul (.mul (.num (-51)) (.pow (.var 0) 3)) (.var 36)))) (.add (.mul (.mul (.num (49)) (.pow (.var 0) 4)) (.var 36)) (.mul (.num (384)) (.var 37)))))

theorem s_er4_4_5 (ctx : Context α) (h_eh4_4_5 : eh4_4_5.denote ctx = 0) (h_ec4_4_5_1 : ec4_4_5_1.denote ctx = 0) :
    (Expr.mul (.num 6) er4_4_5).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 6) er4_4_5) [((.num (384)), eh4_4_5), ((.num (-1)), ec4_4_5_1)] (by decide +kernel) ⟨h_eh4_4_5, h_ec4_4_5_1, trivial⟩

end BranchC.Descent2R
