import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L4.C_18_33_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er4_18_33 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num (1102949328)) (.var 33)) (.mul (.mul (.num (745758000)) (.var 0)) (.var 33))) (.add (.mul (.mul (.num (-209689752)) (.pow (.var 0) 2)) (.var 33)) (.mul (.mul (.num (19481136)) (.pow (.var 0) 3)) (.var 33)))) (.add (.add (.mul (.mul (.num (105399624)) (.pow (.var 0) 4)) (.var 33)) (.mul (.num (7785501464)) (.var 34))) (.add (.mul (.mul (.num (-1372367880)) (.var 0)) (.var 34)) (.mul (.mul (.num (-1121121716)) (.pow (.var 0) 2)) (.var 34))))) (.add (.add (.add (.mul (.mul (.num (1267677424)) (.pow (.var 0) 3)) (.var 34)) (.mul (.mul (.num (-144920620)) (.pow (.var 0) 4)) (.var 34))) (.add (.mul (.num (54313818)) (.var 1)) (.mul (.mul (.num (35842170)) (.var 0)) (.var 1)))) (.add (.add (.mul (.mul (.num (-9950547)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (717744)) (.pow (.var 0) 3)) (.var 1))) (.add (.mul (.mul (.num (4718631)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (296202400)) (.var 2)))))) (.add (.add (.mul (.mul (.num (-39460720)) (.var 0)) (.var 2)) (.mul (.mul (.num (-36914720)) (.pow (.var 0) 2)) (.var 2))) (.add (.mul (.mul (.num (48061640)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (-4921000)) (.pow (.var 0) 4)) (.var 2)))))

theorem s_er4_18_33 (ctx : Context α) (h_eh4_18_33 : eh4_18_33.denote ctx = 0) (h_ec4_18_33_1 : ec4_18_33_1.denote ctx = 0) :
    (Expr.mul (.num 6) er4_18_33).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 6) er4_18_33) [((.num (7752)), eh4_18_33), ((.num (-1)), ec4_18_33_1)] (by decide +kernel) ⟨h_eh4_18_33, h_ec4_18_33_1, trivial⟩

end BranchC.Descent2R
