import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L4.C_19_35_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er4_19_35 : Expr :=
  (.add (.add (.add (.add (.mul (.num (367649776)) (.var 34)) (.mul (.mul (.num (248586000)) (.var 0)) (.var 34))) (.add (.mul (.mul (.num (-69896584)) (.pow (.var 0) 2)) (.var 34)) (.mul (.mul (.num (6493712)) (.pow (.var 0) 3)) (.var 34)))) (.add (.add (.mul (.mul (.num (35133208)) (.pow (.var 0) 4)) (.var 34)) (.mul (.num (18104606)) (.var 2))) (.add (.mul (.mul (.num (11947390)) (.var 0)) (.var 2)) (.mul (.mul (.num (-3316849)) (.pow (.var 0) 2)) (.var 2))))) (.add (.mul (.mul (.num (239248)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (1572877)) (.pow (.var 0) 4)) (.var 2))))

theorem s_er4_19_35 (ctx : Context α) (h_eh4_19_35 : eh4_19_35.denote ctx = 0) (h_ec4_19_35_1 : ec4_19_35_1.denote ctx = 0) :
    (Expr.mul (.num 24) er4_19_35).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 24) er4_19_35) [((.num (7752)), eh4_19_35), ((.num (-1)), ec4_19_35_1)] (by decide +kernel) ⟨h_eh4_19_35, h_ec4_19_35_1, trivial⟩

end BranchC.Descent2R
