import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L4.C_5_7_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er4_5_7 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num (-91032)) (.var 27)) (.mul (.mul (.num (33672)) (.var 0)) (.var 27))) (.add (.mul (.mul (.num (4212)) (.pow (.var 0) 2)) (.var 27)) (.mul (.mul (.num (-21792)) (.pow (.var 0) 3)) (.var 27)))) (.add (.add (.mul (.mul (.num (4572)) (.pow (.var 0) 4)) (.var 27)) (.mul (.num (-1260)) (.var 28))) (.add (.mul (.mul (.num (-5544)) (.var 0)) (.var 28)) (.mul (.mul (.num (1176)) (.pow (.var 0) 2)) (.var 28))))) (.add (.add (.add (.mul (.mul (.num (1512)) (.pow (.var 0) 3)) (.var 28)) (.mul (.mul (.num (-588)) (.pow (.var 0) 4)) (.var 28))) (.add (.mul (.num (-2424)) (.var 29)) (.mul (.mul (.num (-879)) (.var 0)) (.var 29)))) (.add (.add (.mul (.mul (.num (389)) (.pow (.var 0) 2)) (.var 29)) (.mul (.mul (.num (51)) (.pow (.var 0) 3)) (.var 29))) (.add (.mul (.mul (.num (-49)) (.pow (.var 0) 4)) (.var 29)) (.mul (.num (-320)) (.var 30)))))) (.add (.add (.add (.add (.mul (.num (159306)) (.var 35)) (.mul (.mul (.num (-58926)) (.var 0)) (.var 35))) (.add (.mul (.mul (.num (-7371)) (.pow (.var 0) 2)) (.var 35)) (.mul (.mul (.num (38136)) (.pow (.var 0) 3)) (.var 35)))) (.add (.add (.mul (.mul (.num (-8001)) (.pow (.var 0) 4)) (.var 35)) (.mul (.num (2424)) (.var 37))) (.add (.mul (.mul (.num (879)) (.var 0)) (.var 37)) (.mul (.mul (.num (-389)) (.pow (.var 0) 2)) (.var 37))))) (.add (.add (.mul (.mul (.num (-51)) (.pow (.var 0) 3)) (.var 37)) (.mul (.mul (.num (49)) (.pow (.var 0) 4)) (.var 37))) (.mul (.num (256)) (.var 38)))))

theorem s_er4_5_7 (ctx : Context α) (h_eh4_5_7 : eh4_5_7.denote ctx = 0) (h_ec4_5_7_1 : ec4_5_7_1.denote ctx = 0) :
    (Expr.mul (.num 12) er4_5_7).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 12) er4_5_7) [((.num (384)), eh4_5_7), ((.num (-1)), ec4_5_7_1)] (by decide +kernel) ⟨h_eh4_5_7, h_ec4_5_7_1, trivial⟩

end BranchC.Descent2R
