import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L4.C_17_31_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er4_17_31 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num (735299552)) (.var 32)) (.mul (.mul (.num (497172000)) (.var 0)) (.var 32))) (.add (.mul (.mul (.num (-139793168)) (.pow (.var 0) 2)) (.var 32)) (.mul (.mul (.num (12987424)) (.pow (.var 0) 3)) (.var 32)))) (.add (.add (.mul (.mul (.num (70266416)) (.pow (.var 0) 4)) (.var 32)) (.mul (.num (5988847280)) (.var 33))) (.add (.mul (.mul (.num (-1055667600)) (.var 0)) (.var 33)) (.mul (.mul (.num (-862401320)) (.pow (.var 0) 2)) (.var 33))))) (.add (.add (.add (.mul (.mul (.num (975136480)) (.pow (.var 0) 3)) (.var 33)) (.mul (.mul (.num (-111477400)) (.pow (.var 0) 4)) (.var 33))) (.add (.mul (.num (-324624272)) (.var 34)) (.mul (.mul (.num (-6154246224)) (.var 0)) (.var 34)))) (.add (.add (.mul (.mul (.num (328068440)) (.pow (.var 0) 2)) (.var 34)) (.mul (.mul (.num (1011446912)) (.pow (.var 0) 3)) (.var 34))) (.add (.mul (.mul (.num (-802278344)) (.pow (.var 0) 4)) (.var 34)) (.mul (.num (36209212)) (.var 43)))))) (.add (.add (.add (.add (.mul (.mul (.num (23894780)) (.var 0)) (.var 43)) (.mul (.mul (.num (-6633698)) (.pow (.var 0) 2)) (.var 43))) (.add (.mul (.mul (.num (478496)) (.pow (.var 0) 3)) (.var 43)) (.mul (.mul (.num (3145754)) (.pow (.var 0) 4)) (.var 43)))) (.add (.add (.mul (.num (236961920)) (.var 1)) (.mul (.mul (.num (-31568576)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-29531776)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (38449312)) (.pow (.var 0) 3)) (.var 1))))) (.add (.add (.add (.mul (.mul (.num (-3936800)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (-17064090)) (.var 2))) (.add (.mul (.mul (.num (-149158170)) (.var 0)) (.var 2)) (.mul (.mul (.num (11165787)) (.pow (.var 0) 2)) (.var 2)))) (.add (.mul (.mul (.num (26849052)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (-18003051)) (.pow (.var 0) 4)) (.var 2))))))

theorem s_er4_17_31 (ctx : Context α) (h_eh4_17_31 : eh4_17_31.denote ctx = 0) (h_ec4_17_31_1 : ec4_17_31_1.denote ctx = 0) :
    (Expr.mul (.num 12) er4_17_31).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 12) er4_17_31) [((.num (15504)), eh4_17_31), ((.num (-1)), ec4_17_31_1)] (by decide +kernel) ⟨h_eh4_17_31, h_ec4_17_31_1, trivial⟩

end BranchC.Descent2R
