import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.L4.P_a_1_1_1
import Jacobian.BranchC.Descent2R.L4.P_a_2_3_1
import Jacobian.BranchC.Descent2R.L4.P_a_3_5_1
import Jacobian.BranchC.Descent2R.L4.P_a_4_7_1
import Jacobian.BranchC.Descent2R.L4.P_a_5_9_1
import Jacobian.BranchC.Descent2R.L4.P_a_6_11_1
import Jacobian.BranchC.Descent2R.L4.P_a_7_13_1
import Jacobian.BranchC.Descent2R.L4.P_a_8_15_1
import Jacobian.BranchC.Descent2R.L4.P_b_10_18_1
import Jacobian.BranchC.Descent2R.L4.P_b_2_2_1
import Jacobian.BranchC.Descent2R.L4.P_b_3_4_1
import Jacobian.BranchC.Descent2R.L4.P_b_4_6_1
import Jacobian.BranchC.Descent2R.L4.P_b_5_8_1
import Jacobian.BranchC.Descent2R.L4.P_b_6_10_1
import Jacobian.BranchC.Descent2R.L4.P_b_7_12_1
import Jacobian.BranchC.Descent2R.L4.P_b_8_14_1
import Jacobian.BranchC.Descent2R.L4.P_b_9_16_1
import Jacobian.BranchC.Descent2R.Vals_L4

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

theorem s_ev_a_1_1 (ctx : Context α) (h_ep4_a_1_1_1 : ep4_a_1_1_1.denote ctx = 0) :
    (Expr.mul (.num 132950063396482588975212123372054352370459601838080) ev_a_1_1).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 132950063396482588975212123372054352370459601838080) ev_a_1_1) [((.num (1)), ep4_a_1_1_1)] (by decide +kernel) ⟨h_ep4_a_1_1_1, trivial⟩

theorem s_ev_a_2_3 (ctx : Context α) (h_ep4_a_2_3_1 : ep4_a_2_3_1.denote ctx = 0) :
    (Expr.mul (.num 620433629183585415217656575736253644395478141911040) ev_a_2_3).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 620433629183585415217656575736253644395478141911040) ev_a_2_3) [((.num (1)), ep4_a_2_3_1)] (by decide +kernel) ⟨h_ep4_a_2_3_1, trivial⟩

theorem s_ev_a_3_5 (ctx : Context α) (h_ep4_a_3_5_1 : ep4_a_3_5_1.denote ctx = 0) :
    (Expr.mul (.num 155108407295896353804414143934063411098869535477760) ev_a_3_5).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 155108407295896353804414143934063411098869535477760) ev_a_3_5) [((.num (1)), ep4_a_3_5_1)] (by decide +kernel) ⟨h_ep4_a_3_5_1, trivial⟩

theorem s_ev_a_4_7 (ctx : Context α) (h_ep4_a_4_7_1 : ep4_a_4_7_1.denote ctx = 0) :
    (Expr.mul (.num 44316687798827529658404041124018117456819867279360) ev_a_4_7).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 44316687798827529658404041124018117456819867279360) ev_a_4_7) [((.num (1)), ep4_a_4_7_1)] (by decide +kernel) ⟨h_ep4_a_4_7_1, trivial⟩

theorem s_ev_a_5_9 (ctx : Context α) (h_ep4_a_5_9_1 : ep4_a_5_9_1.denote ctx = 0) :
    (Expr.mul (.num 44316687798827529658404041124018117456819867279360) ev_a_5_9).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 44316687798827529658404041124018117456819867279360) ev_a_5_9) [((.num (1)), ep4_a_5_9_1)] (by decide +kernel) ⟨h_ep4_a_5_9_1, trivial⟩

theorem s_ev_a_6_11 (ctx : Context α) (h_ep4_a_6_11_1 : ep4_a_6_11_1.denote ctx = 0) :
    (Expr.mul (.num 9384710357398770986485561649792071932032442482688) ev_a_6_11).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 9384710357398770986485561649792071932032442482688) ev_a_6_11) [((.num (1)), ep4_a_6_11_1)] (by decide +kernel) ⟨h_ep4_a_6_11_1, trivial⟩

theorem s_ev_a_7_13 (ctx : Context α) (h_ep4_a_7_13_1 : ep4_a_7_13_1.denote ctx = 0) :
    (Expr.mul (.num 28927578443514083742695864887271664) ev_a_7_13).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 28927578443514083742695864887271664) ev_a_7_13) [((.num (1)), ep4_a_7_13_1)] (by decide +kernel) ⟨h_ep4_a_7_13_1, trivial⟩

theorem s_ev_a_8_15 (ctx : Context α) (h_ep4_a_8_15_1 : ep4_a_8_15_1.denote ctx = 0) :
    (Expr.mul (.num 3214175382612675971410651654141296) ev_a_8_15).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 3214175382612675971410651654141296) ev_a_8_15) [((.num (1)), ep4_a_8_15_1)] (by decide +kernel) ⟨h_ep4_a_8_15_1, trivial⟩

theorem s_ev_b_2_2 (ctx : Context α) (h_ep4_b_2_2_1 : ep4_b_2_2_1.denote ctx = 0) :
    (Expr.mul (.num 132950063396482588975212123372054352370459601838080) ev_b_2_2).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 132950063396482588975212123372054352370459601838080) ev_b_2_2) [((.num (1)), ep4_b_2_2_1)] (by decide +kernel) ⟨h_ep4_b_2_2_1, trivial⟩

theorem s_ev_b_3_4 (ctx : Context α) (h_ep4_b_3_4_1 : ep4_b_3_4_1.denote ctx = 0) :
    (Expr.mul (.num 620433629183585415217656575736253644395478141911040) ev_b_3_4).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 620433629183585415217656575736253644395478141911040) ev_b_3_4) [((.num (1)), ep4_b_3_4_1)] (by decide +kernel) ⟨h_ep4_b_3_4_1, trivial⟩

theorem s_ev_b_4_6 (ctx : Context α) (h_ep4_b_4_6_1 : ep4_b_4_6_1.denote ctx = 0) :
    (Expr.mul (.num 22158343899413764829202020562009058728409933639680) ev_b_4_6).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 22158343899413764829202020562009058728409933639680) ev_b_4_6) [((.num (1)), ep4_b_4_6_1)] (by decide +kernel) ⟨h_ep4_b_4_6_1, trivial⟩

theorem s_ev_b_5_8 (ctx : Context α) (h_ep4_b_5_8_1 : ep4_b_5_8_1.denote ctx = 0) :
    (Expr.mul (.num 177266751195310118633616164496072469827279469117440) ev_b_5_8).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 177266751195310118633616164496072469827279469117440) ev_b_5_8) [((.num (1)), ep4_b_5_8_1)] (by decide +kernel) ⟨h_ep4_b_5_8_1, trivial⟩

theorem s_ev_b_6_10 (ctx : Context α) (h_ep4_b_6_10_1 : ep4_b_6_10_1.denote ctx = 0) :
    (Expr.mul (.num 22158343899413764829202020562009058728409933639680) ev_b_6_10).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 22158343899413764829202020562009058728409933639680) ev_b_6_10) [((.num (1)), ep4_b_6_10_1)] (by decide +kernel) ⟨h_ep4_b_6_10_1, trivial⟩

theorem s_ev_b_7_12 (ctx : Context α) (h_ep4_b_7_12_1 : ep4_b_7_12_1.denote ctx = 0) :
    (Expr.mul (.num 5213727976332650548047534249884484406684690268160) ev_b_7_12).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 5213727976332650548047534249884484406684690268160) ev_b_7_12) [((.num (1)), ep4_b_7_12_1)] (by decide +kernel) ⟨h_ep4_b_7_12_1, trivial⟩

theorem s_ev_b_8_14 (ctx : Context α) (h_ep4_b_8_14_1 : ep4_b_8_14_1.denote ctx = 0) :
    (Expr.mul (.num 1303431994083162637011883562471121101671172567040) ev_b_8_14).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 1303431994083162637011883562471121101671172567040) ev_b_8_14) [((.num (1)), ep4_b_8_14_1)] (by decide +kernel) ⟨h_ep4_b_8_14_1, trivial⟩

theorem s_ev_b_9_16 (ctx : Context α) (h_ep4_b_9_16_1 : ep4_b_9_16_1.denote ctx = 0) :
    (Expr.mul (.num 265900126792965177950424246744108704740919203676160) ev_b_9_16).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 265900126792965177950424246744108704740919203676160) ev_b_9_16) [((.num (1)), ep4_b_9_16_1)] (by decide +kernel) ⟨h_ep4_b_9_16_1, trivial⟩

theorem s_ev_b_10_18 (ctx : Context α) (h_ep4_b_10_18_1 : ep4_b_10_18_1.denote ctx = 0) :
    (Expr.mul (.num 301353477032027201677147479643323198706375097499648) ev_b_10_18).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 301353477032027201677147479643323198706375097499648) ev_b_10_18) [((.num (1)), ep4_b_10_18_1)] (by decide +kernel) ⟨h_ep4_b_10_18_1, trivial⟩

end BranchC.Descent2R
