import Jacobian.BranchAbFinal

/-! Generated by gen_sharp.py.  Consistency of the hard-coded top layer (E5 holds) and sharpness of
`layers_K5` (only the vertex condition `b₁₂,₂₄ ≠ 0` is contradicted). -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false
set_option linter.unnecessarySeqFocus false

open BranchAb

namespace BranchAb

/-- The rescaled K₅ top layer solves the top-layer equation E5: `2 A₂ B₃' − 3 A₂' B₃ = x²`. -/
theorem top_layer_E5 {L : Type*} [Field L] [CharZero L] (w : L)
    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) (A₂ B₃ : Polynomial L)
    (sA₂ : ∀ i, A₂.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8) (sB₃ : ∀ i, B₃.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12)
    (tA1 : A₂.coeff 1 = ((1 : L)))
    (tA2 : A₂.coeff 2 = (((303) / 16 : L) + ((879) / 128 : L) * w + ((-389) / 128 : L) * w ^ (2 : ℕ) + ((-51) / 128 : L) * w ^ (3 : ℕ) + ((49) / 128 : L) * w ^ (4 : ℕ)))
    (tA3 : A₂.coeff 3 = (((315) / 16 : L) + ((693) / 8 : L) * w + ((-147) / 8 : L) * w ^ (2 : ℕ) + ((-189) / 8 : L) * w ^ (3 : ℕ) + ((147) / 16 : L) * w ^ (4 : ℕ)))
    (tA4 : A₂.coeff 4 = (((-79653) / 64 : L) + ((29463) / 64 : L) * w + ((7371) / 128 : L) * w ^ (2 : ℕ) + ((-4767) / 16 : L) * w ^ (3 : ℕ) + ((8001) / 128 : L) * w ^ (4 : ℕ)))
    (tA5 : A₂.coeff 5 = (((-33519) / 4 : L) + ((-6843) / 4 : L) * w + ((8181) / 8 : L) * w ^ (2 : ℕ) + ((-1713) / 2 : L) * w ^ (3 : ℕ) + ((-1305) / 8 : L) * w ^ (4 : ℕ)))
    (tA6 : A₂.coeff 6 = (((-8805) / 8 : L) + ((-76965) / 8 : L) * w + ((11523) / 16 : L) * w ^ (2 : ℕ) + ((6927) / 4 : L) * w ^ (3 : ℕ) + ((-18579) / 16 : L) * w ^ (4 : ℕ)))
    (tA7 : A₂.coeff 7 = (((389740) / 17 : L) + ((-51922) / 17 : L) * w + ((-48572) / 17 : L) * w ^ (2 : ℕ) + ((63239) / 17 : L) * w ^ (3 : ℕ) + ((-6475) / 17 : L) * w ^ (4 : ℕ)))
    (tA8 : A₂.coeff 8 = (((476437) / 68 : L) + ((314405) / 68 : L) * w + ((-174571) / 136 : L) * w ^ (2 : ℕ) + ((1574) / 17 : L) * w ^ (3 : ℕ) + ((82783) / 136 : L) * w ^ (4 : ℕ)))
    (tB2 : B₃.coeff 2 = ((1 : L)))
    (tB3 : B₃.coeff 3 = (((101) / 8 : L) + ((293) / 64 : L) * w + ((-389) / 192 : L) * w ^ (2 : ℕ) + ((-17) / 64 : L) * w ^ (3 : ℕ) + ((49) / 192 : L) * w ^ (4 : ℕ)))
    (tB4 : B₃.coeff 4 = (((315) / 16 : L) + ((693) / 8 : L) * w + ((-147) / 8 : L) * w ^ (2 : ℕ) + ((-189) / 8 : L) * w ^ (3 : ℕ) + ((147) / 16 : L) * w ^ (4 : ℕ)))
    (tB5 : B₃.coeff 5 = (((-11379) / 8 : L) + ((4209) / 8 : L) * w + ((1053) / 16 : L) * w ^ (2 : ℕ) + ((-681) / 2 : L) * w ^ (3 : ℕ) + ((1143) / 16 : L) * w ^ (4 : ℕ)))
    (tB6 : B₃.coeff 6 = (((-695299) / 48 : L) + ((-48367) / 48 : L) * w + ((52679) / 32 : L) * w ^ (2 : ℕ) + ((-45661) / 24 : L) * w ^ (3 : ℕ) + ((-2211) / 32 : L) * w ^ (4 : ℕ)))
    (tB7 : B₃.coeff 7 = (((-309895) / 8 : L) + ((-251275) / 8 : L) * w + ((101481) / 16 : L) * w ^ (2 : ℕ) + ((1811) / 4 : L) * w ^ (3 : ℕ) + ((-60489) / 16 : L) * w ^ (4 : ℕ)))
    (tB8 : B₃.coeff 8 = (((1733348) / 13 : L) + ((-2368725) / 26 : L) * w + ((-184976) / 13 : L) * w ^ (2 : ℕ) + ((1819939) / 52 : L) * w ^ (3 : ℕ) + ((-569071) / 52 : L) * w ^ (4 : ℕ)))
    (tB9 : B₃.coeff 9 = (((18736247) / 39 : L) + ((1087133) / 13 : L) * w + ((-5656777) / 78 : L) * w ^ (2 : ℕ) + ((1993384) / 39 : L) * w ^ (3 : ℕ) + ((971365) / 78 : L) * w ^ (4 : ℕ)))
    (tB10 : B₃.coeff 10 = (((305098) / 17 : L) + ((5784066) / 17 : L) * w + ((-308335) / 17 : L) * w ^ (2 : ℕ) + ((-950608) / 17 : L) * w ^ (3 : ℕ) + ((754021) / 17 : L) * w ^ (4 : ℕ)))
    (tB11 : B₃.coeff 11 = (((-149721182) / 323 : L) + ((26391690) / 323 : L) * w + ((21560033) / 323 : L) * w ^ (2 : ℕ) + ((-24378412) / 323 : L) * w ^ (3 : ℕ) + ((2786935) / 323 : L) * w ^ (4 : ℕ)))
    (tB12 : B₃.coeff 12 = (((-91912444) / 969 : L) + ((-20715500) / 323 : L) * w + ((17474146) / 969 : L) * w ^ (2 : ℕ) + ((-1623428) / 969 : L) * w ^ (3 : ℕ) + ((-8783302) / 969 : L) * w ^ (4 : ℕ)))
    : layerTerm 2 3 A₂ B₃ = Polynomial.C 1 * Polynomial.X ^ 2 := by
  have hw5 : w ^ (5 : ℕ) = ((-26 : L) + (-3 : L) * w ^ (2 : ℕ) + (-3 : L) * w ^ (3 : ℕ) + (1 : L) * w ^ (4 : ℕ)) := by linear_combination ((1 : L) * w ^ (0 : ℕ)) * hw
  have hw6 : w ^ (6 : ℕ) = ((-26 : L) + (-26 : L) * w + (-3 : L) * w ^ (2 : ℕ) + (-6 : L) * w ^ (3 : ℕ) + (-2 : L) * w ^ (4 : ℕ)) := by linear_combination ((1 : L) * w ^ (0 : ℕ) + (1 : L) * w ^ (1 : ℕ)) * hw
  have hw7 : w ^ (7 : ℕ) = ((52 : L) + (-26 : L) * w + (-20 : L) * w ^ (2 : ℕ) + (3 : L) * w ^ (3 : ℕ) + (-8 : L) * w ^ (4 : ℕ)) := by linear_combination ((-2 : L) * w ^ (0 : ℕ) + (1 : L) * w ^ (1 : ℕ) + (1 : L) * w ^ (2 : ℕ)) * hw
  have hw8 : w ^ (8 : ℕ) = ((208 : L) + (52 : L) * w + (-2 : L) * w ^ (2 : ℕ) + (4 : L) * w ^ (3 : ℕ) + (-5 : L) * w ^ (4 : ℕ)) := by linear_combination ((-8 : L) * w ^ (0 : ℕ) + (-2 : L) * w ^ (1 : ℕ) + (1 : L) * w ^ (2 : ℕ) + (1 : L) * w ^ (3 : ℕ)) * hw
  have zA0 : A₂.coeff 0 = 0 := coeff_zero_of_support _ 1 8 sA₂ 0 (by omega)
  have zA9 : A₂.coeff 9 = 0 := coeff_zero_of_support _ 1 8 sA₂ 9 (by omega)
  have zA10 : A₂.coeff 10 = 0 := coeff_zero_of_support _ 1 8 sA₂ 10 (by omega)
  have zA11 : A₂.coeff 11 = 0 := coeff_zero_of_support _ 1 8 sA₂ 11 (by omega)
  have zA12 : A₂.coeff 12 = 0 := coeff_zero_of_support _ 1 8 sA₂ 12 (by omega)
  have zA13 : A₂.coeff 13 = 0 := coeff_zero_of_support _ 1 8 sA₂ 13 (by omega)
  have zA14 : A₂.coeff 14 = 0 := coeff_zero_of_support _ 1 8 sA₂ 14 (by omega)
  have zA15 : A₂.coeff 15 = 0 := coeff_zero_of_support _ 1 8 sA₂ 15 (by omega)
  have zA16 : A₂.coeff 16 = 0 := coeff_zero_of_support _ 1 8 sA₂ 16 (by omega)
  have zA17 : A₂.coeff 17 = 0 := coeff_zero_of_support _ 1 8 sA₂ 17 (by omega)
  have zA18 : A₂.coeff 18 = 0 := coeff_zero_of_support _ 1 8 sA₂ 18 (by omega)
  have zA19 : A₂.coeff 19 = 0 := coeff_zero_of_support _ 1 8 sA₂ 19 (by omega)
  have zA20 : A₂.coeff 20 = 0 := coeff_zero_of_support _ 1 8 sA₂ 20 (by omega)
  have zA21 : A₂.coeff 21 = 0 := coeff_zero_of_support _ 1 8 sA₂ 21 (by omega)
  have zA22 : A₂.coeff 22 = 0 := coeff_zero_of_support _ 1 8 sA₂ 22 (by omega)
  have zB0 : B₃.coeff 0 = 0 := coeff_zero_of_support _ 2 12 sB₃ 0 (by omega)
  have zB1 : B₃.coeff 1 = 0 := coeff_zero_of_support _ 2 12 sB₃ 1 (by omega)
  have zB13 : B₃.coeff 13 = 0 := coeff_zero_of_support _ 2 12 sB₃ 13 (by omega)
  have zB14 : B₃.coeff 14 = 0 := coeff_zero_of_support _ 2 12 sB₃ 14 (by omega)
  have zB15 : B₃.coeff 15 = 0 := coeff_zero_of_support _ 2 12 sB₃ 15 (by omega)
  have zB16 : B₃.coeff 16 = 0 := coeff_zero_of_support _ 2 12 sB₃ 16 (by omega)
  have zB17 : B₃.coeff 17 = 0 := coeff_zero_of_support _ 2 12 sB₃ 17 (by omega)
  have zB18 : B₃.coeff 18 = 0 := coeff_zero_of_support _ 2 12 sB₃ 18 (by omega)
  have zB19 : B₃.coeff 19 = 0 := coeff_zero_of_support _ 2 12 sB₃ 19 (by omega)
  have zB20 : B₃.coeff 20 = 0 := coeff_zero_of_support _ 2 12 sB₃ 20 (by omega)
  have zB21 : B₃.coeff 21 = 0 := coeff_zero_of_support _ 2 12 sB₃ 21 (by omega)
  have zB22 : B₃.coeff 22 = 0 := coeff_zero_of_support _ 2 12 sB₃ 22 (by omega)
  ext n
  by_cases hn : n ≤ 21
  · interval_cases n <;>
      (simp only [coeff_layerTerm, Finset.sum_range_succ, Finset.sum_range_zero, Nat.cast_ofNat, Nat.cast_zero, Nat.cast_one, zero_add, zA0, zA9, zA10, zA11, zA12, zA13, zA14, zA15, zA16, zA17, zA18, zA19, zA20, zA21, zA22, zB0, zB1, zB13, zB14, zB15, zB16, zB17, zB18, zB19, zB20, zB21, zB22, tA1, tA2, tA3, tA4, tA5, tA6, tA7, tA8, tB2, tB3, tB4, tB5, tB6, tB7, tB8, tB9, tB10, tB11, tB12, mul_zero, zero_mul, add_zero, sub_zero, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, one_mul] <;> (try norm_num) <;> (try ring_nf) <;> (try simp only [hw5, hw6, hw7, hw8]) <;> (try ring_nf))
  · rw [coeff_layerTerm, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow]
    split_ifs with h2
    · omega
    rw [mul_zero]
    refine Finset.sum_eq_zero (fun i hi => ?_)
    by_cases hi8 : i ≤ 8
    · rw [coeff_zero_of_support B₃ 2 12 sB₃ (n + 1 - i) (by omega), mul_zero]
    · rw [coeff_zero_of_support A₂ 1 8 sA₂ i (by omega), mul_zero, zero_mul]

/-- The rescaled K₅ top-layer coefficients of `topA`. -/
noncomputable def topA {L : Type*} [Field L] (w : L) : ℕ → L
  | 1 => ((1 : L))
  | 2 => (((303) / 16 : L) + ((879) / 128 : L) * w + ((-389) / 128 : L) * w ^ (2 : ℕ) + ((-51) / 128 : L) * w ^ (3 : ℕ) + ((49) / 128 : L) * w ^ (4 : ℕ))
  | 3 => (((315) / 16 : L) + ((693) / 8 : L) * w + ((-147) / 8 : L) * w ^ (2 : ℕ) + ((-189) / 8 : L) * w ^ (3 : ℕ) + ((147) / 16 : L) * w ^ (4 : ℕ))
  | 4 => (((-79653) / 64 : L) + ((29463) / 64 : L) * w + ((7371) / 128 : L) * w ^ (2 : ℕ) + ((-4767) / 16 : L) * w ^ (3 : ℕ) + ((8001) / 128 : L) * w ^ (4 : ℕ))
  | 5 => (((-33519) / 4 : L) + ((-6843) / 4 : L) * w + ((8181) / 8 : L) * w ^ (2 : ℕ) + ((-1713) / 2 : L) * w ^ (3 : ℕ) + ((-1305) / 8 : L) * w ^ (4 : ℕ))
  | 6 => (((-8805) / 8 : L) + ((-76965) / 8 : L) * w + ((11523) / 16 : L) * w ^ (2 : ℕ) + ((6927) / 4 : L) * w ^ (3 : ℕ) + ((-18579) / 16 : L) * w ^ (4 : ℕ))
  | 7 => (((389740) / 17 : L) + ((-51922) / 17 : L) * w + ((-48572) / 17 : L) * w ^ (2 : ℕ) + ((63239) / 17 : L) * w ^ (3 : ℕ) + ((-6475) / 17 : L) * w ^ (4 : ℕ))
  | 8 => (((476437) / 68 : L) + ((314405) / 68 : L) * w + ((-174571) / 136 : L) * w ^ (2 : ℕ) + ((1574) / 17 : L) * w ^ (3 : ℕ) + ((82783) / 136 : L) * w ^ (4 : ℕ))
  | _ => 0

/-- The rescaled K₅ top-layer coefficients of `topB`. -/
noncomputable def topB {L : Type*} [Field L] (w : L) : ℕ → L
  | 2 => ((1 : L))
  | 3 => (((101) / 8 : L) + ((293) / 64 : L) * w + ((-389) / 192 : L) * w ^ (2 : ℕ) + ((-17) / 64 : L) * w ^ (3 : ℕ) + ((49) / 192 : L) * w ^ (4 : ℕ))
  | 4 => (((315) / 16 : L) + ((693) / 8 : L) * w + ((-147) / 8 : L) * w ^ (2 : ℕ) + ((-189) / 8 : L) * w ^ (3 : ℕ) + ((147) / 16 : L) * w ^ (4 : ℕ))
  | 5 => (((-11379) / 8 : L) + ((4209) / 8 : L) * w + ((1053) / 16 : L) * w ^ (2 : ℕ) + ((-681) / 2 : L) * w ^ (3 : ℕ) + ((1143) / 16 : L) * w ^ (4 : ℕ))
  | 6 => (((-695299) / 48 : L) + ((-48367) / 48 : L) * w + ((52679) / 32 : L) * w ^ (2 : ℕ) + ((-45661) / 24 : L) * w ^ (3 : ℕ) + ((-2211) / 32 : L) * w ^ (4 : ℕ))
  | 7 => (((-309895) / 8 : L) + ((-251275) / 8 : L) * w + ((101481) / 16 : L) * w ^ (2 : ℕ) + ((1811) / 4 : L) * w ^ (3 : ℕ) + ((-60489) / 16 : L) * w ^ (4 : ℕ))
  | 8 => (((1733348) / 13 : L) + ((-2368725) / 26 : L) * w + ((-184976) / 13 : L) * w ^ (2 : ℕ) + ((1819939) / 52 : L) * w ^ (3 : ℕ) + ((-569071) / 52 : L) * w ^ (4 : ℕ))
  | 9 => (((18736247) / 39 : L) + ((1087133) / 13 : L) * w + ((-5656777) / 78 : L) * w ^ (2 : ℕ) + ((1993384) / 39 : L) * w ^ (3 : ℕ) + ((971365) / 78 : L) * w ^ (4 : ℕ))
  | 10 => (((305098) / 17 : L) + ((5784066) / 17 : L) * w + ((-308335) / 17 : L) * w ^ (2 : ℕ) + ((-950608) / 17 : L) * w ^ (3 : ℕ) + ((754021) / 17 : L) * w ^ (4 : ℕ))
  | 11 => (((-149721182) / 323 : L) + ((26391690) / 323 : L) * w + ((21560033) / 323 : L) * w ^ (2 : ℕ) + ((-24378412) / 323 : L) * w ^ (3 : ℕ) + ((2786935) / 323 : L) * w ^ (4 : ℕ))
  | 12 => (((-91912444) / 969 : L) + ((-20715500) / 323 : L) * w + ((17474146) / 969 : L) * w ^ (2 : ℕ) + ((-1623428) / 969 : L) * w ^ (3 : ℕ) + ((-8783302) / 969 : L) * w ^ (4 : ℕ))
  | _ => 0

lemma coeff_sum_C_mul_X_pow {L : Type*} [Field L] (f : ℕ → L) (N i : ℕ) :
    (∑ j ∈ Finset.range N, Polynomial.C (f j) * Polynomial.X ^ j).coeff i = if i < N then f i else 0 := by
  rw [Polynomial.finsetSum_coeff]
  simp only [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, mul_ite, mul_one, mul_zero]
  rw [Finset.sum_ite_eq]; simp [Finset.mem_range]

/-- **Sharpness.**  The lower-edge partial solution (`A₀ = B₀ = 1`, `A₁ = B₁ = B₂ = 0`, top layer the
rescaled K₅ point) satisfies E5, E4, E3, E2, the Newton-polygon supports and the top-layer values of
`layers_K5`, with `b₁₂,₂₄ = 0`.  So `layers_K5` is not vacuous: its content is exactly `b₁₂,₂₄ = 0`. -/
theorem layers_K5_sharp {L : Type*} [Field L] [CharZero L] (w : L)
    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) :
    ∃ A₀ A₁ A₂ B₀ B₁ B₂ B₃ : Polynomial L,
      layerTerm 2 3 A₂ B₃ = Polynomial.C 1 * Polynomial.X ^ 2 ∧
      layerTerm 2 2 A₂ B₂ + layerTerm 1 3 A₁ B₃ = 0 ∧
      layerTerm 2 1 A₂ B₁ + layerTerm 1 2 A₁ B₂ + layerTerm 0 3 A₀ B₃ = 0 ∧
      layerTerm 2 0 A₂ B₀ + layerTerm 1 1 A₁ B₁ + layerTerm 0 2 A₀ B₂ = 0 ∧
      (∀ i, A₀.coeff i ≠ 0 → 0 ≤ i ∧ i ≤ 8) ∧ (∀ i, A₁.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8) ∧
      (∀ i, A₂.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8) ∧ (∀ i, B₀.coeff i ≠ 0 → 0 ≤ i ∧ i ≤ 12) ∧
      (∀ i, B₁.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 12) ∧ (∀ i, B₂.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12) ∧
      (∀ i, B₃.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12) ∧
      (∀ i, A₂.coeff i = topA w i) ∧ (∀ k, B₃.coeff k = topB w k) ∧ B₀.coeff 12 = 0 := by
  set A₂ : Polynomial L := ∑ j ∈ Finset.range 9, Polynomial.C (topA w j) * Polynomial.X ^ j with hA₂
  set B₃ : Polynomial L := ∑ j ∈ Finset.range 13, Polynomial.C (topB w j) * Polynomial.X ^ j with hB₃
  have cA : ∀ i, A₂.coeff i = topA w i := by
    intro i; rw [hA₂, coeff_sum_C_mul_X_pow]; split_ifs with h
    · rfl
    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 9 := ⟨i - 9, by omega⟩; rfl
  have cB : ∀ i, B₃.coeff i = topB w i := by
    intro i; rw [hB₃, coeff_sum_C_mul_X_pow]; split_ifs with h
    · rfl
    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 13 := ⟨i - 13, by omega⟩; rfl
  have sA : ∀ i, A₂.coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8 := by
    intro i h; rw [cA] at h; by_contra hc; apply h
    rcases Nat.lt_or_ge i 1 with h0 | h9
    · obtain rfl : i = 0 := by omega
      rfl
    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 9 := ⟨i - 9, by omega⟩; rfl
  have sB : ∀ i, B₃.coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12 := by
    intro i h; rw [cB] at h; by_contra hc; apply h
    rcases Nat.lt_or_ge i 2 with h0 | h9
    · interval_cases i <;> rfl
    · obtain ⟨k, rfl⟩ : ∃ k, i = k + 13 := ⟨i - 13, by omega⟩; rfl
  refine ⟨Polynomial.C 1, 0, A₂, Polynomial.C 1, 0, 0, B₃, ?_, ?_, ?_, ?_, ?_, ?_, sA, ?_, ?_, ?_, sB, cA, cB, ?_⟩
  · exact top_layer_E5 w hw A₂ B₃ sA sB (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cA]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl) (by rw [cB]; rfl)
  · simp [layerTerm]
  · simp [layerTerm]
  · simp [layerTerm]
  · intro i h; rw [Polynomial.coeff_C] at h; split_ifs at h with h0
    · omega
    · exact absurd rfl h
  · intro i h; simp at h
  · intro i h; rw [Polynomial.coeff_C] at h; split_ifs at h with h0
    · omega
    · exact absurd rfl h
  · intro i h; simp at h
  · intro i h; simp at h
  · rw [Polynomial.coeff_C]; simp

end BranchAb
