import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.Vals_L4

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec3_19_36_1 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.mul (.num (4465152)) (.var 15)) (.var 4)) (.mul (.mul (.num (-1116288)) (.var 34)) (.var 2))) (.add (.mul (.mul (.num (-6697728)) (.var 51)) (.var 26)) (.mul (.num (-635298812928)) (.var 51)))) (.add (.add (.mul (.mul (.num (-429556608000)) (.var 0)) (.var 51)) (.mul (.mul (.num (120781297152)) (.pow (.var 0) 2)) (.var 51))) (.add (.mul (.mul (.num (-11221134336)) (.pow (.var 0) 3)) (.var 51)) (.mul (.mul (.num (-60710183424)) (.pow (.var 0) 4)) (.var 51))))) (.add (.add (.add (.mul (.num (2644496)) (.pow (.var 2) 2)) (.mul (.mul (.num (-1629668)) (.var 0)) (.pow (.var 2) 2))) (.add (.mul (.mul (.num (1300056)) (.pow (.var 0) 2)) (.pow (.var 2) 2)) (.mul (.mul (.num (-462004)) (.pow (.var 0) 3)) (.pow (.var 2) 2)))) (.add (.add (.mul (.mul (.num (177232)) (.pow (.var 0) 4)) (.pow (.var 2) 2)) (.mul (.num (-31284759168)) (.var 4))) (.add (.mul (.mul (.num (-20645089920)) (.var 0)) (.var 4)) (.mul (.mul (.num (5731515072)) (.pow (.var 0) 2)) (.var 4)))))) (.add (.mul (.mul (.num (-413420544)) (.pow (.var 0) 3)) (.var 4)) (.mul (.mul (.num (-2717931456)) (.pow (.var 0) 4)) (.var 4))))

theorem s_ec3_19_36_1 (ctx : Context α) (h_et_a_8_14 : et_a_8_14.denote ctx = 0) (h_ev_a_8_15 : ev_a_8_15.denote ctx = 0) (h_et_b_12_21 : et_b_12_21.denote ctx = 0) :
    ec3_19_36_1.denote ctx = 0 :=
  lc_zero ctx ec3_19_36_1 [((.mul (.num (32832)) (.var 4)), et_a_8_14), ((.mul (.num (-76)) (.var 2)), ev_a_8_15), ((.mul (.num (-6912)) (.var 51)), et_b_12_21)] (by decide +kernel) ⟨h_et_a_8_14, h_ev_a_8_15, h_et_b_12_21, trivial⟩

end BranchC.Descent2R
