import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec3_1_0_1 : Expr :=
  (.add (.mul (.mul (.num (1)) (.var 8)) (.var 52)) (.mul (.num (-1)) (.var 52)))

theorem s_ec3_1_0_1 (ctx : Context α) (h_et_a_1_0 : et_a_1_0.denote ctx = 0) :
    ec3_1_0_1.denote ctx = 0 :=
  lc_zero ctx ec3_1_0_1 [((.mul (.num (1)) (.var 52)), et_a_1_0)] (by decide +kernel) ⟨h_et_a_1_0, trivial⟩

end BranchC.Descent2R
