import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L3.C_1_0_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er3_1_0 : Expr :=
  (.mul (.num (1)) (.var 52))

theorem s_er3_1_0 (ctx : Context α) (h_eh3_1_0 : eh3_1_0.denote ctx = 0) (h_ec3_1_0_1 : ec3_1_0_1.denote ctx = 0) :
    er3_1_0.denote ctx = 0 :=
  lc_zero ctx er3_1_0 [((.num (1)), eh3_1_0), ((.num (-1)), ec3_1_0_1)] (by decide +kernel) ⟨h_eh3_1_0, h_ec3_1_0_1, trivial⟩

end BranchC.Descent2R
