import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L3.C_3_4_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er3_3_4 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num (-2424)) (.var 44)) (.mul (.mul (.num (-879)) (.var 0)) (.var 44))) (.add (.mul (.mul (.num (389)) (.pow (.var 0) 2)) (.var 44)) (.mul (.mul (.num (51)) (.pow (.var 0) 3)) (.var 44)))) (.add (.add (.mul (.mul (.num (-49)) (.pow (.var 0) 4)) (.var 44)) (.mul (.num (-384)) (.var 45))) (.add (.mul (.num (-1260)) (.var 52)) (.mul (.mul (.num (-5544)) (.var 0)) (.var 52))))) (.add (.add (.add (.mul (.mul (.num (1176)) (.pow (.var 0) 2)) (.var 52)) (.mul (.mul (.num (1512)) (.pow (.var 0) 3)) (.var 52))) (.add (.mul (.mul (.num (-588)) (.pow (.var 0) 4)) (.var 52)) (.mul (.num (2424)) (.var 53)))) (.add (.add (.mul (.mul (.num (879)) (.var 0)) (.var 53)) (.mul (.mul (.num (-389)) (.pow (.var 0) 2)) (.var 53))) (.add (.mul (.mul (.num (-51)) (.pow (.var 0) 3)) (.var 53)) (.mul (.mul (.num (49)) (.pow (.var 0) 4)) (.var 53)))))) (.mul (.num (320)) (.var 54)))

theorem s_er3_3_4 (ctx : Context α) (h_eh3_3_4 : eh3_3_4.denote ctx = 0) (h_ec3_3_4_1 : ec3_3_4_1.denote ctx = 0) :
    (Expr.mul (.num 37114818351679372240355328) er3_3_4).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 37114818351679372240355328) er3_3_4) [((.num (2375348374507479823382740992)), eh3_3_4), ((.num (-1)), ec3_3_4_1)] (by decide +kernel) ⟨h_eh3_3_4, h_ec3_3_4_1, trivial⟩

end BranchC.Descent2R
