import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L3.C_19_36_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er3_19_36 : Expr :=
  (.add (.add (.add (.add (.mul (.num (158824703232)) (.var 51)) (.mul (.mul (.num (107389152000)) (.var 0)) (.var 51))) (.add (.mul (.mul (.num (-30195324288)) (.pow (.var 0) 2)) (.var 51)) (.mul (.mul (.num (2805283584)) (.pow (.var 0) 3)) (.var 51)))) (.add (.add (.mul (.mul (.num (15177545856)) (.pow (.var 0) 4)) (.var 51)) (.mul (.num (-661124)) (.pow (.var 2) 2))) (.add (.mul (.mul (.num (407417)) (.var 0)) (.pow (.var 2) 2)) (.mul (.mul (.num (-325014)) (.pow (.var 0) 2)) (.pow (.var 2) 2))))) (.add (.add (.add (.mul (.mul (.num (115501)) (.pow (.var 0) 3)) (.pow (.var 2) 2)) (.mul (.mul (.num (-44308)) (.pow (.var 0) 4)) (.pow (.var 2) 2))) (.add (.mul (.num (7821189792)) (.var 4)) (.mul (.mul (.num (5161272480)) (.var 0)) (.var 4)))) (.add (.add (.mul (.mul (.num (-1432878768)) (.pow (.var 0) 2)) (.var 4)) (.mul (.mul (.num (103355136)) (.pow (.var 0) 3)) (.var 4))) (.mul (.mul (.num (679482864)) (.pow (.var 0) 4)) (.var 4)))))

theorem s_er3_19_36 (ctx : Context α) (h_eh3_19_36 : eh3_19_36.denote ctx = 0) (h_ec3_19_36_1 : ec3_19_36_1.denote ctx = 0) :
    (Expr.mul (.num 4) er3_19_36).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 4) er3_19_36) [((.num (279072)), eh3_19_36), ((.num (-1)), ec3_19_36_1)] (by decide +kernel) ⟨h_eh3_19_36, h_ec3_19_36_1, trivial⟩

end BranchC.Descent2R
