import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L3.C_18_34_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er3_18_34 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num (7226523997056)) (.var 50)) (.mul (.mul (.num (4886206416000)) (.var 0)) (.var 50))) (.add (.mul (.mul (.num (-1373887255104)) (.pow (.var 0) 2)) (.var 50)) (.mul (.mul (.num (127640403072)) (.pow (.var 0) 3)) (.var 50)))) (.add (.add (.mul (.mul (.num (690578336448)) (.pow (.var 0) 4)) (.var 50)) (.mul (.num (40360039589376)) (.var 51))) (.add (.mul (.mul (.num (-7114355089920)) (.var 0)) (.var 51)) (.mul (.mul (.num (-5811894975744)) (.pow (.var 0) 2)) (.var 51))))) (.add (.add (.add (.mul (.mul (.num (6571639766016)) (.pow (.var 0) 3)) (.var 51)) (.mul (.mul (.num (-751268494080)) (.pow (.var 0) 4)) (.var 51))) (.add (.mul (.mul (.num (-60162284)) (.var 1)) (.var 2)) (.mul (.mul (.mul (.num (37074947)) (.var 0)) (.var 1)) (.var 2)))) (.add (.add (.mul (.mul (.mul (.num (-29576274)) (.pow (.var 0) 2)) (.var 1)) (.var 2)) (.mul (.mul (.mul (.num (10510591)) (.pow (.var 0) 3)) (.var 1)) (.var 2))) (.add (.mul (.mul (.mul (.num (-4032028)) (.pow (.var 0) 4)) (.var 1)) (.var 2)) (.mul (.num (355864135536)) (.var 3)))))) (.add (.add (.add (.add (.mul (.mul (.num (234837897840)) (.var 0)) (.var 3)) (.mul (.mul (.num (-65195983944)) (.pow (.var 0) 2)) (.var 3))) (.add (.mul (.mul (.num (4702658688)) (.pow (.var 0) 3)) (.var 3)) (.mul (.mul (.num (30916470312)) (.pow (.var 0) 4)) (.var 3)))) (.add (.add (.mul (.num (43692381)) (.pow (.var 2) 2)) (.mul (.mul (.num (-26773128)) (.var 0)) (.pow (.var 2) 2))) (.add (.mul (.mul (.num (20994126)) (.pow (.var 0) 2)) (.pow (.var 2) 2)) (.mul (.mul (.num (-7644840)) (.pow (.var 0) 3)) (.pow (.var 2) 2))))) (.add (.add (.add (.mul (.mul (.num (2852565)) (.pow (.var 0) 4)) (.pow (.var 2) 2)) (.mul (.num (1413951776640)) (.var 4))) (.add (.mul (.mul (.num (-188369692992)) (.var 0)) (.var 4)) (.mul (.mul (.num (-176216107392)) (.pow (.var 0) 2)) (.var 4)))) (.add (.mul (.mul (.num (229427044704)) (.pow (.var 0) 3)) (.var 4)) (.mul (.mul (.num (-23490885600)) (.pow (.var 0) 4)) (.var 4))))))

theorem s_er3_18_34 (ctx : Context α) (h_eh3_18_34 : eh3_18_34.denote ctx = 0) (h_ec3_18_34_1 : ec3_18_34_1.denote ctx = 0) :
    (Expr.mul (.num 2) er3_18_34).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 2) er3_18_34) [((.num (7255872)), eh3_18_34), ((.num (-1)), ec3_18_34_1)] (by decide +kernel) ⟨h_eh3_18_34, h_ec3_18_34_1, trivial⟩

end BranchC.Descent2R
