import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L3.C_2_2_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er3_2_2 : Expr :=
  (.add (.mul (.num (-3)) (.var 44)) (.mul (.num (3)) (.var 53)))

theorem s_er3_2_2 (ctx : Context α) (h_eh3_2_2 : eh3_2_2.denote ctx = 0) (h_ec3_2_2_1 : ec3_2_2_1.denote ctx = 0) :
    er3_2_2.denote ctx = 0 :=
  lc_zero ctx er3_2_2 [((.num (1)), eh3_2_2), ((.num (-1)), ec3_2_2_1)] (by decide +kernel) ⟨h_eh3_2_2, h_ec3_2_2_1, trivial⟩

end BranchC.Descent2R
