import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.L3.P_a_1_2_1
import Jacobian.BranchC.Descent2R.L3.P_a_2_4_1
import Jacobian.BranchC.Descent2R.L3.P_a_3_6_1
import Jacobian.BranchC.Descent2R.L3.P_a_4_8_1
import Jacobian.BranchC.Descent2R.L3.P_a_5_10_1
import Jacobian.BranchC.Descent2R.L3.P_a_6_12_1
import Jacobian.BranchC.Descent2R.L3.P_a_7_14_1
import Jacobian.BranchC.Descent2R.L3.P_a_8_16_1
import Jacobian.BranchC.Descent2R.L3.P_b_10_19_1
import Jacobian.BranchC.Descent2R.L3.P_b_1_1_1
import Jacobian.BranchC.Descent2R.L3.P_b_2_3_1
import Jacobian.BranchC.Descent2R.L3.P_b_3_5_1
import Jacobian.BranchC.Descent2R.L3.P_b_4_7_1
import Jacobian.BranchC.Descent2R.L3.P_b_5_9_1
import Jacobian.BranchC.Descent2R.L3.P_b_6_11_1
import Jacobian.BranchC.Descent2R.L3.P_b_7_13_1
import Jacobian.BranchC.Descent2R.L3.P_b_8_15_1
import Jacobian.BranchC.Descent2R.L3.P_b_9_17_1
import Jacobian.BranchC.Descent2R.Vals_L3

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

theorem s_ev_a_1_2 (ctx : Context α) (h_ep3_a_1_2_1 : ep3_a_1_2_1.denote ctx = 0) :
    (Expr.mul (.num 13782499462986249697179844318926931145897323289491598819401428320256) ev_a_1_2).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 13782499462986249697179844318926931145897323289491598819401428320256) ev_a_1_2) [((.num (1)), ep3_a_1_2_1)] (by decide +kernel) ⟨h_ep3_a_1_2_1, trivial⟩

theorem s_ev_a_2_4 (ctx : Context α) (h_ep3_a_2_4_1 : ep3_a_2_4_1.denote ctx = 0) :
    (Expr.mul (.num 2297083243831041616196640719821155190982887214915266469900238053376) ev_a_2_4).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 2297083243831041616196640719821155190982887214915266469900238053376) ev_a_2_4) [((.num (1)), ep3_a_2_4_1)] (by decide +kernel) ⟨h_ep3_a_2_4_1, trivial⟩

theorem s_ev_a_3_6 (ctx : Context α) (h_ep3_a_3_6_1 : ep3_a_3_6_1.denote ctx = 0) :
    (Expr.mul (.num 13782499462986249697179844318926931145897323289491598819401428320256) ev_a_3_6).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 13782499462986249697179844318926931145897323289491598819401428320256) ev_a_3_6) [((.num (1)), ep3_a_3_6_1)] (by decide +kernel) ⟨h_ep3_a_3_6_1, trivial⟩

theorem s_ev_a_4_8 (ctx : Context α) (h_ep3_a_4_8_1 : ep3_a_4_8_1.denote ctx = 0) :
    (Expr.mul (.num 5906785484136964155934218993825827633955995695496399494029183565824) ev_a_4_8).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 5906785484136964155934218993825827633955995695496399494029183565824) ev_a_4_8) [((.num (1)), ep3_a_4_8_1)] (by decide +kernel) ⟨h_ep3_a_4_8_1, trivial⟩

theorem s_ev_a_5_10 (ctx : Context α) (h_ep3_a_5_10_1 : ep3_a_5_10_1.denote ctx = 0) :
    (Expr.mul (.num 1505651201838834000532251900386975671400547922381435165144693850112) ev_a_5_10).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 1505651201838834000532251900386975671400547922381435165144693850112) ev_a_5_10) [((.num (1)), ep3_a_5_10_1)] (by decide +kernel) ⟨h_ep3_a_5_10_1, trivial⟩

theorem s_ev_a_6_12 (ctx : Context α) (h_ep3_a_6_12_1 : ep3_a_6_12_1.denote ctx = 0) :
    (Expr.mul (.num 94856025715846542033531869724379467298234519110030415404115712557056) ev_a_6_12).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 94856025715846542033531869724379467298234519110030415404115712557056) ev_a_6_12) [((.num (1)), ep3_a_6_12_1)] (by decide +kernel) ⟨h_ep3_a_6_12_1, trivial⟩

theorem s_ev_a_7_14 (ctx : Context α) (h_ep3_a_7_14_1 : ep3_a_7_14_1.denote ctx = 0) :
    (Expr.mul (.num 5161971560528027957994485098833802782169487367097248318239204) ev_a_7_14).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 5161971560528027957994485098833802782169487367097248318239204) ev_a_7_14) [((.num (1)), ep3_a_7_14_1)] (by decide +kernel) ⟨h_ep3_a_7_14_1, trivial⟩

theorem s_ev_a_8_16 (ctx : Context α) (h_ep3_a_8_16_1 : ep3_a_8_16_1.denote ctx = 0) :
    (Expr.mul (.num 9586518612409194779132615183548490881171905110323461162444236) ev_a_8_16).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 9586518612409194779132615183548490881171905110323461162444236) ev_a_8_16) [((.num (1)), ep3_a_8_16_1)] (by decide +kernel) ⟨h_ep3_a_8_16_1, trivial⟩

theorem s_ev_b_1_1 (ctx : Context α) (h_ep3_b_1_1_1 : ep3_b_1_1_1.denote ctx = 0) :
    ev_b_1_1.denote ctx = 0 :=
  lc_zero ctx ev_b_1_1 [((.num (1)), ep3_b_1_1_1)] (by decide +kernel) ⟨h_ep3_b_1_1_1, trivial⟩

theorem s_ev_b_2_3 (ctx : Context α) (h_ep3_b_2_3_1 : ep3_b_2_3_1.denote ctx = 0) :
    (Expr.mul (.num 13782499462986249697179844318926931145897323289491598819401428320256) ev_b_2_3).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 13782499462986249697179844318926931145897323289491598819401428320256) ev_b_2_3) [((.num (1)), ep3_b_2_3_1)] (by decide +kernel) ⟨h_ep3_b_2_3_1, trivial⟩

theorem s_ev_b_3_5 (ctx : Context α) (h_ep3_b_3_5_1 : ep3_b_3_5_1.denote ctx = 0) :
    (Expr.mul (.num 2297083243831041616196640719821155190982887214915266469900238053376) ev_b_3_5).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 2297083243831041616196640719821155190982887214915266469900238053376) ev_b_3_5) [((.num (1)), ep3_b_3_5_1)] (by decide +kernel) ⟨h_ep3_b_3_5_1, trivial⟩

theorem s_ev_b_4_7 (ctx : Context α) (h_ep3_b_4_7_1 : ep3_b_4_7_1.denote ctx = 0) :
    (Expr.mul (.num 1968928494712321385311406331275275877985331898498799831343061188608) ev_b_4_7).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 1968928494712321385311406331275275877985331898498799831343061188608) ev_b_4_7) [((.num (1)), ep3_b_4_7_1)] (by decide +kernel) ⟨h_ep3_b_4_7_1, trivial⟩

theorem s_ev_b_5_9 (ctx : Context α) (h_ep3_b_5_9_1 : ep3_b_5_9_1.denote ctx = 0) :
    (Expr.mul (.num 11813570968273928311868437987651655267911991390992798988058367131648) ev_b_5_9).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 11813570968273928311868437987651655267911991390992798988058367131648) ev_b_5_9) [((.num (1)), ep3_b_5_9_1)] (by decide +kernel) ⟨h_ep3_b_5_9_1, trivial⟩

theorem s_ev_b_6_11 (ctx : Context α) (h_ep3_b_6_11_1 : ep3_b_6_11_1.denote ctx = 0) :
    (Expr.mul (.num 13898318786204621543374632926649006197543519283520939985951020154880) ev_b_6_11).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 13898318786204621543374632926649006197543519283520939985951020154880) ev_b_6_11) [((.num (1)), ep3_b_6_11_1)] (by decide +kernel) ⟨h_ep3_b_6_11_1, trivial⟩

theorem s_ev_b_7_13 (ctx : Context α) (h_ep3_b_7_13_1 : ep3_b_7_13_1.denote ctx = 0) :
    (Expr.mul (.num 14593234725514852620543364572981456507420695247696986985248571162624) ev_b_7_13).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 14593234725514852620543364572981456507420695247696986985248571162624) ev_b_7_13) [((.num (1)), ep3_b_7_13_1)] (by decide +kernel) ⟨h_ep3_b_7_13_1, trivial⟩

theorem s_ev_b_8_15 (ctx : Context α) (h_ep3_b_8_15_1 : ep3_b_8_15_1.denote ctx = 0) :
    (Expr.mul (.num 243915494697891108086224807862690058766888763425792496753440403718144) ev_b_8_15).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 243915494697891108086224807862690058766888763425792496753440403718144) ev_b_8_15) [((.num (1)), ep3_b_8_15_1)] (by decide +kernel) ⟨h_ep3_b_8_15_1, trivial⟩

theorem s_ev_b_9_17 (ctx : Context α) (h_ep3_b_9_17_1 : ep3_b_9_17_1.denote ctx = 0) :
    (Expr.mul (.num 845898935612286362843027633667809123803570231560648378740931320094523392) ev_b_9_17).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 845898935612286362843027633667809123803570231560648378740931320094523392) ev_b_9_17) [((.num (1)), ep3_b_9_17_1)] (by decide +kernel) ⟨h_ep3_b_9_17_1, trivial⟩

theorem s_ev_b_10_19 (ctx : Context α) (h_ep3_b_10_19_1 : ep3_b_10_19_1.denote ctx = 0) :
    (Expr.mul (.num 5921292549286004539901193435674663866624991620924538651186519240661663744) ev_b_10_19).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 5921292549286004539901193435674663866624991620924538651186519240661663744) ev_b_10_19) [((.num (1)), ep3_b_10_19_1)] (by decide +kernel) ⟨h_ep3_b_10_19_1, trivial⟩

end BranchC.Descent2R
