"""
gen_final.py -- emit Jacobian/BranchAbFinal.lean: the end-to-end statement

  no_completion_K5 : layer decomposition of (P, Q) + J(P, Q) = C λ x² + Newton-polygon supports
                     + top layer = rescaled K5 point (any root w of R, any char-0 field) + b_{12,24} ≠ 0
                     → False

Proof: layers_of_jac gives E4, E3, E2 as polynomial identities; coeff_layerTerm turns each coefficient
into the scalar bracket equation used by descent_K5 (variables a_i_j := A_{2i-j}.coeff i,
b_k_l := B_{2k-l}.coeff k); descent_K5 closes.
"""
import json, os, sys
from fractions import Fraction
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_system import lattice_points, NP_VERTS, NQ_VERTS

cert = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "cert.json")))
KEY = lambda v: (v[0], int(v.split('_')[1]), int(v.split('_')[2]))
def q(s):
    f = Fraction(s)
    if f.denominator == 1: return f"({f.numerator} : L)"
    return f"(({f.numerator}) / {f.denominator} : L)"
def kel(c):
    terms = []
    for i, s in enumerate(c):
        if Fraction(s) == 0: continue
        terms.append(q(s) + ("" if i == 0 else (" * w" if i == 1 else f" * w ^ ({i} : ℕ)")))
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"

top = cert["top"]; TOPV = sorted(top, key=KEY)
Z, X, B0 = cert["Z"], cert["X"], cert["B0"]
eqs = cert["eqs"]
LP, LQ = lattice_points(NP_VERTS), lattice_points(NQ_VERTS)
# layer supports from the lattice points
supA = {a: sorted(i for (i, j) in LP if j == 2 * i - a) for a in range(3)}
supB = {b: sorted(k for (k, l) in LQ if l == 2 * k - b) for b in range(4)}
for d in (supA, supB):
    for k, s in d.items(): assert s == list(range(s[0], s[-1] + 1)), (k, s)   # contiguous
assert all(j - 2 * i in (0, -1, -2) for i, j in LP) and all(l - 2 * k in (0, -1, -2, -3) for k, l in LQ)
PA = {0: "A₀", 1: "A₁", 2: "A₂"}; PB = {0: "B₀", 1: "B₁", 2: "B₂", 3: "B₃"}
def cf(v):
    _, i, j = v.split('_'); i, j = int(i), int(j)
    return f"({PA[2*i-j]}.coeff {i})" if v[0] == 'a' else f"({PB[2*i-j]}.coeff {i})"
def eq_expr(terms):
    return " + ".join(f"{c} * {cf(pv)} * {cf(qv)}" if c >= 0 else f"({c}) * {cf(pv)} * {cf(qv)}" for c, pv, qv in terms)

HI = 26
L = []
L.append("""import Jacobian.BranchAbLayers
import Jacobian.BranchAbTorus
import Jacobian.Descent.Main

/-! Generated by gen_final.py.  End-to-end form of the exact K₅ descent (branch (a,b), degree
pair (72,108)).

* `layers_K5`: the layer identities E4, E3, E2 with Newton-polygon supports and top layer equal to the
  rescaled K₅ point contradict `b₁₂,₂₄ ≠ 0` (coefficients via `coeff_layerTerm`, then `descent_K5`).
* `no_completion_K5`: from `J(P, Q) = λ x²` (via `layers_of_jac`) with the top layer anywhere in the
  torus orbit `A₂.coeff i = ρ εⁱ⁻¹ Tᵢ(w)`, `B₃.coeff k = σ εᵏ⁻² Tₖ(w)` (via `layers_transport`). -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false
set_option linter.unnecessarySeqFocus false

open MvPolynomial BranchAb

namespace BranchAb

lemma coeff_zero_of_support {K : Type*} [Field K] (A : Polynomial K) (lo hi : ℕ)
    (h : ∀ i, A.coeff i ≠ 0 → lo ≤ i ∧ i ≤ hi) (i : ℕ) (hi' : i < lo ∨ hi < i) : A.coeff i = 0 := by
  by_contra hne; have := h i hne; omega
""")
SUPP = []
for a in range(3):
    SUPP.append((PA[a], supA[a][0], supA[a][-1]))
for b in range(4):
    SUPP.append((PB[b], supB[b][0], supB[b][-1]))
# ---------------- layers_K5
L.append("""/-- The layer identities with the rescaled K₅ top layer contradict `b₁₂,₂₄ ≠ 0`. -/""")
L.append("theorem layers_K5 {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)")
L.append("    (A₀ A₁ A₂ B₀ B₁ B₂ B₃ : Polynomial L)")
L.append("    (E4 : layerTerm 2 2 A₂ B₂ + layerTerm 1 3 A₁ B₃ = 0)")
L.append("    (E3 : layerTerm 2 1 A₂ B₁ + layerTerm 1 2 A₁ B₂ + layerTerm 0 3 A₀ B₃ = 0)")
L.append("    (E2 : layerTerm 2 0 A₂ B₀ + layerTerm 1 1 A₁ B₁ + layerTerm 0 2 A₀ B₂ = 0)")
for P_, lo, hi in SUPP:
    L.append(f"    (s{P_} : ∀ i, {P_}.coeff i ≠ 0 → {lo} ≤ i ∧ i ≤ {hi})")
for v in TOPV:
    L.append(f"    (t_{v} : {cf(v)} = {kel(top[v])})")
L.append("    (hv : B₀.coeff 12 ≠ 0) : False := by")
ZN = []
for P_, lo, hi in SUPP:
    for i in list(range(0, lo)) + list(range(hi + 1, HI)):
        n = f"z{P_}_{i}"; ZN.append(n)
        L.append(f"  have {n} : {P_}.coeff {i} = 0 := coeff_zero_of_support _ {lo} {hi} s{P_} {i} (by omega)")
SIMP = ("Polynomial.coeff_add, coeff_layerTerm, Polynomial.coeff_zero, Finset.sum_range_succ, "
        "Finset.sum_range_zero, Nat.cast_ofNat, Nat.cast_zero, Nat.cast_one, zero_add, " + ", ".join(ZN) +
        ", mul_zero, zero_mul, add_zero, sub_zero")
HN = []
for W, tag, E in (("-3", 4, "E4"), ("-2", 3, "E3"), ("-1", 2, "E2")):
    for k, terms in eqs[W]:
        n = f"h{tag}_{k[0]}_{k[1]}"; HN.append(n)
        L.append(f"  have {n} : {eq_expr(terms)} = 0 := by")
        L.append(f"    have e := congrArg (fun F => Polynomial.coeff F {k[0]}) {E}")
        L.append(f"    simp only [{SIMP}] at e")
        L.append(f"    linear_combination e")
args = ["w", "hw"] + [cf(v) for v in TOPV] + [f"t_{v}" for v in TOPV] + [cf(v) for v in Z + X + B0] + HN + ["hv"]
L.append("  exact Descent.descent_K5 " + " ".join(args))
L.append("")
# ---------------- no_completion_K5 (torus orbit, from the Jacobian)
def texp(v):
    i = int(v.split('_')[1]); return i - 1 if v[0] == 'a' else i - 2
L.append("""/-- **No completion of the K₅ top layer (any point of its torus orbit).**  Let `L` be a field of
characteristic zero, `w ∈ L` a root of `w⁵ − w⁴ + 3w³ + 3w² + 26`, and `P = p₀ + p₁ + p₂`,
`Q = q₀ + q₁ + q₂ + q₃` with `yᵃ pₐ = Aₐ(x y²)`, `yᵇ q_b = B_b(x y²)`.  Suppose `J(P, Q) = λ x²`, the
layer coefficients are supported on the lattice points of `N(P) = conv{(0,0),(1,0),(8,14),(8,16)}` and
`N(Q) = conv{(0,0),(2,1),(12,21),(12,24)}`, and the top layer is a torus image of the rescaled K₅ point:
`A₂.coeff i = ρ εⁱ⁻¹ Tᵢ(w)`, `B₃.coeff k = σ εᵏ⁻² Tₖ(w)` with `ρ σ ε ≠ 0`.  Then `b₁₂,₂₄ = B₀.coeff 12 = 0`. -/""")
L.append("theorem no_completion_K5 {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) (lam : L)")
L.append("    (A₀ A₁ A₂ B₀ B₁ B₂ B₃ : Polynomial L) (p₀ p₁ p₂ q₀ q₁ q₂ q₃ : MvPolynomial (Fin 2) L)")
L.append("    (hp₀ : X 1 ^ 0 * p₀ = evH A₀) (hp₁ : X 1 ^ 1 * p₁ = evH A₁) (hp₂ : X 1 ^ 2 * p₂ = evH A₂)")
L.append("    (hq₀ : X 1 ^ 0 * q₀ = evH B₀) (hq₁ : X 1 ^ 1 * q₁ = evH B₁) (hq₂ : X 1 ^ 2 * q₂ = evH B₂)")
L.append("    (hq₃ : X 1 ^ 3 * q₃ = evH B₃)")
L.append("    (hJ : jac (p₀ + p₁ + p₂) (q₀ + q₁ + q₂ + q₃) = C lam * X 0 ^ 2)")
for P_, lo, hi in SUPP:
    L.append(f"    (s{P_} : ∀ i, {P_}.coeff i ≠ 0 → {lo} ≤ i ∧ i ≤ {hi})")
L.append("    (ρ σ ε : L) (hρ : ρ ≠ 0) (hσ : σ ≠ 0) (hε : ε ≠ 0)")
for v in TOPV:
    sc_ = "ρ" if v[0] == 'a' else "σ"
    L.append(f"    (t_{v} : {cf(v)} = {sc_} * ε ^ ({texp(v)} : ℕ) * {kel(top[v])})")
L.append("    (hv : B₀.coeff 12 ≠ 0) : False := by")
L.append("  obtain ⟨-, E4, E3, E2, -⟩ := layers_of_jac lam A₀ A₁ A₂ B₀ B₁ B₂ B₃ p₀ p₁ p₂ q₀ q₁ q₂ q₃")
L.append("    hp₀ hp₁ hp₂ hq₀ hq₁ hq₂ hq₃ hJ")
L.append("  -- rescale: Ãₐ = (ε/ρ) Aₐ(u/ε), B̃_b = (ε²/σ) B_b(u/ε)")
L.append("  obtain ⟨E4', E3', E2'⟩ := layers_transport (ε / ρ) (ε ^ 2 / σ) ε⁻¹ A₀ A₁ A₂ B₀ B₁ B₂ B₃ E4 E3 E2")
L.append("  have cA : ∀ (F : Polynomial L) (i : ℕ), (Polynomial.C (ε / ρ) * sc ε⁻¹ F).coeff i = ε / ρ * ε⁻¹ ^ i * F.coeff i := by")
L.append("    intro F i; rw [Polynomial.coeff_C_mul, coeff_sc]; ring")
L.append("  have cB : ∀ (F : Polynomial L) (i : ℕ), (Polynomial.C (ε ^ 2 / σ) * sc ε⁻¹ F).coeff i = ε ^ 2 / σ * ε⁻¹ ^ i * F.coeff i := by")
L.append("    intro F i; rw [Polynomial.coeff_C_mul, coeff_sc]; ring")
L.append("  have nA : ε / ρ ≠ 0 := div_ne_zero hε hρ")
L.append("  have nB : ε ^ 2 / σ ≠ 0 := div_ne_zero (pow_ne_zero 2 hε) hσ")
L.append("  have nI : ∀ i : ℕ, ε⁻¹ ^ i ≠ 0 := fun i => pow_ne_zero i (inv_ne_zero hε)")
for P_, lo, hi in SUPP:
    c = "cA" if P_.startswith("A") else "cB"; nn = "nA" if P_.startswith("A") else "nB"
    L.append(f"  have s{P_}' : ∀ i, (Polynomial.C {'(ε / ρ)' if P_.startswith('A') else '(ε ^ 2 / σ)'} * sc ε⁻¹ {P_}).coeff i ≠ 0 → {lo} ≤ i ∧ i ≤ {hi} := by")
    L.append(f"    intro i h; rw [{c}] at h; exact s{P_} i (right_ne_zero_of_mul h)")
for v in TOPV:
    P_ = cf(v).split('.')[0].strip('(')
    c = "cA" if v[0] == 'a' else "cB"
    Sexp = '(ε / ρ)' if v[0] == 'a' else '(ε ^ 2 / σ)'
    i = int(v.split('_')[1])
    L.append(f"  have t'_{v} : (Polynomial.C {Sexp} * sc ε⁻¹ {P_}).coeff {i} = {kel(top[v])} := by")
    L.append(f"    rw [{c}, t_{v}]; field_simp")
L.append("  have hv' : (Polynomial.C (ε ^ 2 / σ) * sc ε⁻¹ B₀).coeff 12 ≠ 0 := by")
L.append("    rw [cB]; exact mul_ne_zero (mul_ne_zero nB (nI 12)) hv")
tops = " ".join(f"t'_{v}" for v in TOPV)
sups = " ".join(f"s{P_}'" for P_, _, _ in SUPP)
L.append("  exact layers_K5 w hw _ _ _ _ _ _ _ E4' E3' E2' " + sups + " " + tops + " hv'")
L.append("\nend BranchAb\n")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Jacobian", "BranchAbFinal.lean"), "w").write("\n".join(L))
print("supports A:", {a: (s[0], s[-1]) for a, s in supA.items()}, " B:", {b: (s[0], s[-1]) for b, s in supB.items()})
print("zero facts:", len(ZN), " scalar equations:", len(HN))
