import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L0.C_0_1_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er0_0_1 : Expr :=
  (.mul (.num (2)) (.var 104))

theorem s_er0_0_1 (ctx : Context α) (h_eh0_0_1 : eh0_0_1.denote ctx = 0) (h_ec0_0_1_1 : ec0_0_1_1.denote ctx = 0) :
    (Expr.mul (.num 3365058013342595506719702823416543313920) er0_0_1).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 3365058013342595506719702823416543313920) er0_0_1) [((.num (3365058013342595506719702823416543313920)), eh0_0_1), ((.num (-1)), ec0_0_1_1)] (by decide +kernel) ⟨h_eh0_0_1, h_ec0_0_1_1, trivial⟩

end BranchC.Descent2R
