import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.Vals_L2c
import Jacobian.BranchC.Descent2R.Vals_L3
import Jacobian.BranchC.Descent2R.Vals_L4

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec1_19_38_1 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.mul (.num (191721621655388575236096)) (.var 34)) (.var 73)) (.mul (.mul (.num (-127814414436925716824064)) (.var 51)) (.var 4))) (.add (.mul (.mul (.num (-87974250484797445827981312)) (.pow (.var 2) 2)) (.var 4)) (.mul (.mul (.mul (.num (52842570243724429793703936)) (.var 0)) (.pow (.var 2) 2)) (.var 4)))) (.add (.add (.mul (.mul (.mul (.num (-41891267271012142061684736)) (.pow (.var 0) 2)) (.pow (.var 2) 2)) (.var 4)) (.mul (.mul (.mul (.num (15011513154834151503734784)) (.pow (.var 0) 3)) (.pow (.var 2) 2)) (.var 4))) (.add (.mul (.mul (.mul (.num (-5633183076079136632104960)) (.pow (.var 0) 4)) (.pow (.var 2) 2)) (.var 4)) (.mul (.num (6240197679371043914739945192)) (.pow (.var 2) 4))))) (.add (.add (.add (.mul (.mul (.num (-3748234084612236715738138860)) (.var 0)) (.pow (.var 2) 4)) (.mul (.mul (.num (2971435260320322482058568212)) (.pow (.var 0) 2)) (.pow (.var 2) 4))) (.add (.mul (.mul (.num (-1064798040311083681943113284)) (.pow (.var 0) 3)) (.pow (.var 2) 4)) (.mul (.mul (.num (399573466809239690437872564)) (.pow (.var 0) 4)) (.pow (.var 2) 4)))) (.add (.add (.mul (.num (302793461652183227301888)) (.pow (.var 4) 2)) (.mul (.mul (.num (-186596166174496061128704)) (.var 0)) (.pow (.var 4) 2))) (.add (.mul (.mul (.num (148855757990063406317568)) (.pow (.var 0) 2)) (.pow (.var 4) 2)) (.mul (.mul (.num (-52899225582929699930112)) (.pow (.var 0) 3)) (.pow (.var 4) 2)))))) (.mul (.mul (.num (20292974841156779114496)) (.pow (.var 0) 4)) (.pow (.var 4) 2)))

theorem s_ec1_19_38_1 (ctx : Context α) (h_ev_a_8_15 : ev_a_8_15.denote ctx = 0) (h_ev_b_12_24 : ev_b_12_24.denote ctx = 0) (h_ev_a_8_16 : ev_a_8_16.denote ctx = 0) (h_eR : eR.denote ctx = 0) :
    ec1_19_38_1.denote ctx = 0 :=
  lc_zero ctx ec1_19_38_1 [((.mul (.num (13052942650829832192)) (.var 73)), ev_a_8_15), ((.add (.add (.add (.mul (.num (417552)) (.var 2)) (.mul (.mul (.num (-257316)) (.var 0)) (.var 2))) (.add (.mul (.mul (.num (205272)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-72948)) (.pow (.var 0) 3)) (.var 2)))) (.mul (.mul (.num (27984)) (.pow (.var 0) 4)) (.var 2))), ev_b_12_24), ((.mul (.num (-5109391872)) (.var 4)), ev_a_8_16), ((.add (.add (.add (.mul (.mul (.num (-1998873039507836305282560)) (.pow (.var 2) 2)) (.var 4)) (.mul (.mul (.mul (.num (868578908140178722027008)) (.var 0)) (.pow (.var 2) 2)) (.var 4))) (.add (.mul (.mul (.mul (.num (-256819076928292569739776)) (.pow (.var 0) 2)) (.pow (.var 2) 2)) (.var 4)) (.mul (.mul (.mul (.num (60122312255797622138880)) (.pow (.var 0) 3)) (.pow (.var 2) 2)) (.var 4)))) (.add (.add (.mul (.num (189045649383260247033269916)) (.pow (.var 2) 4)) (.mul (.mul (.num (-82146814565884477140261492)) (.var 0)) (.pow (.var 2) 4))) (.add (.mul (.mul (.num (24288949557587248010795412)) (.pow (.var 0) 2)) (.pow (.var 2) 4)) (.mul (.mul (.num (-5686131964624900955156496)) (.pow (.var 0) 3)) (.pow (.var 2) 4))))), eR)] (by decide +kernel) ⟨h_ev_a_8_15, h_ev_b_12_24, h_ev_a_8_16, h_eR, trivial⟩

end BranchC.Descent2R
