import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.L1.Red_0_0

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ep1_b_0_1_1 : Expr :=
  (.mul (.num (1)) (.var 87))

theorem s_ep1_b_0_1_1 (ctx : Context α) (h_er1_0_0 : er1_0_0.denote ctx = 0) :
    ep1_b_0_1_1.denote ctx = 0 :=
  lc_zero ctx ep1_b_0_1_1 [((.num (1)), er1_0_0)] (by decide +kernel) ⟨h_er1_0_0, trivial⟩

end BranchC.Descent2R
