import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L1.C_1_2_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er1_1_2 : Expr :=
  (.add (.add (.add (.mul (.num (-256)) (.var 80)) (.mul (.num (2424)) (.var 87))) (.add (.mul (.mul (.num (879)) (.var 0)) (.var 87)) (.mul (.mul (.num (-389)) (.pow (.var 0) 2)) (.var 87)))) (.add (.add (.mul (.mul (.num (-51)) (.pow (.var 0) 3)) (.var 87)) (.mul (.mul (.num (49)) (.pow (.var 0) 4)) (.var 87))) (.mul (.num (192)) (.var 88))))

theorem s_er1_1_2 (ctx : Context α) (h_eh1_1_2 : eh1_1_2.denote ctx = 0) (h_ec1_1_2_1 : ec1_1_2_1.denote ctx = 0) :
    (Expr.mul (.num 13559861515706847276355166586042790849093607652065280) er1_1_2).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 13559861515706847276355166586042790849093607652065280) er1_1_2) [((.num (867831137005238225686730661506738614341990889732177920)), eh1_1_2), ((.num (-1)), ec1_1_2_1)] (by decide +kernel) ⟨h_eh1_1_2, h_ec1_1_2_1, trivial⟩

end BranchC.Descent2R
