import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L1.C_19_38_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er1_19_38 : Expr :=
  (.add (.add (.add (.add (.mul (.mul (.num (7331187540399787152331776)) (.pow (.var 2) 2)) (.var 4)) (.mul (.mul (.mul (.num (-4403547520310369149475328)) (.var 0)) (.pow (.var 2) 2)) (.var 4))) (.add (.mul (.mul (.mul (.num (3490938939251011838473728)) (.pow (.var 0) 2)) (.pow (.var 2) 2)) (.var 4)) (.mul (.mul (.mul (.num (-1250959429569512625311232)) (.pow (.var 0) 3)) (.pow (.var 2) 2)) (.var 4)))) (.add (.add (.mul (.mul (.mul (.num (469431923006594719342080)) (.pow (.var 0) 4)) (.pow (.var 2) 2)) (.var 4)) (.mul (.num (-520016473280920326228328766)) (.pow (.var 2) 4))) (.add (.mul (.mul (.num (312352840384353059644844905)) (.var 0)) (.pow (.var 2) 4)) (.mul (.mul (.num (-247619605026693540171547351)) (.pow (.var 0) 2)) (.pow (.var 2) 4))))) (.add (.add (.add (.mul (.mul (.num (88733170025923640161926107)) (.pow (.var 0) 3)) (.pow (.var 2) 4)) (.mul (.mul (.num (-33297788900769974203156047)) (.pow (.var 0) 4)) (.pow (.var 2) 4))) (.add (.mul (.num (-25232788471015268941824)) (.pow (.var 4) 2)) (.mul (.mul (.num (15549680514541338427392)) (.var 0)) (.pow (.var 4) 2)))) (.add (.add (.mul (.mul (.num (-12404646499171950526464)) (.pow (.var 0) 2)) (.pow (.var 4) 2)) (.mul (.mul (.num (4408268798577474994176)) (.pow (.var 0) 3)) (.pow (.var 4) 2))) (.mul (.mul (.num (-1691081236763064926208)) (.pow (.var 0) 4)) (.pow (.var 4) 2)))))

theorem s_er1_19_38 (ctx : Context α) (h_eh1_19_38 : eh1_19_38.denote ctx = 0) (h_ec1_19_38_1 : ec1_19_38_1.denote ctx = 0) :
    (Expr.mul (.num 12) er1_19_38).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 12) er1_19_38) [((.num (15976801804615714603008)), eh1_19_38), ((.num (-1)), ec1_19_38_1)] (by decide +kernel) ⟨h_eh1_19_38, h_ec1_19_38_1, trivial⟩

end BranchC.Descent2R
