import Jacobian.BranchC.Edge19
import Jacobian.BranchC.OmegaSquare

/-!
# Branch (c): the `E₁` obstruction `Ω` is the `x¹⁹` vertex–edge condition

The pipeline's `Ω(t₂, s₂) = c₁ s₂² + c₂ t₂² s₂ + c₃ t₂⁴` (`branch_c/scripts/branch_c_stage6e_patch101.py`,
normalization `a_{1,0} = a_{2,2} = b_{2,1} = 1`) is `c₁ (s₂ − κ t₂²)²` (`Omega.omega_square`), and its double
root is exactly the vertex–edge ratio of `Jacobian/BranchC/Edge19.lean`:

  `κ = 1 / (3 b_{12,21})`  (`Omega.kappa_mul_three_beta`; modulo `101`: `3 · 70 · 38 = 1`).

Hence (`omega_of_jac`): for every field `L` of characteristic `0`, every root `w` of `R`, and all
`P, Q ∈ L[x,y]` supported in the branch-(c) polygons with `a_{8,14} ≠ 0`, `b_{12,21} = β(w)` (the pipeline
normalization) and `J(P,Q) = λx²`, the pipeline's `Ω` vanishes at `(t₂, s₂) = (b_{12,22}, b_{12,23})`.

This derives the `E₁` obstruction from four scalar equations (the `u¹⁹` coefficients of `E₄ … E₁`),
without the `E₂`/`E₁` operator certificates. `betaPipe` is `b_{12,21}` of `certgen/e5_exact_K5.json`;
the cofactor is generated by `certgen_c/gen_omega_edge.py`.

No `sorry`, no new axioms.
-/

namespace BranchC.Omega

variable {L : Type*} [Field L]

/-- `b_{12,21}` of the pipeline's top layer (`certgen/e5_exact_K5.json`), exactly in `K₅ = ℚ[w]/(R)`. -/
def betaPipe (w : L) : L := (((573851721948116355241672935369602597327152194164581440195249936454122833415815174050176788864172483566403584) / 790567233615950191854469231113826231261835815084276816987295358031942042382579721418103740698963572468680848281013681 : L) + ((-113438292365192333860834729979534340932253367583019385974573392358352834048450804968401494886487337395093504) / 263522411205316730618156410371275410420611938361425605662431786010647347460859907139367913566321190822893616093671227 : L) * w + ((256120780695561636589893456404025750005480465233934270704735691098098700217347775014513930581112001300955136) / 790567233615950191854469231113826231261835815084276816987295358031942042382579721418103740698963572468680848281013681 : L) * w ^ 2 + ((-91836663610400490147469257554991658453429770070611174186898732517171451342701365229455395034337726322507776) / 790567233615950191854469231113826231261835815084276816987295358031942042382579721418103740698963572468680848281013681 : L) * w ^ 3 + ((32561889229743333020733567439963572243524554712145824967381320527221634335827083935607647650558097898201088) / 790567233615950191854469231113826231261835815084276816987295358031942042382579721418103740698963572468680848281013681 : L) * w ^ 4)

variable [CharZero L]

/-- `κ · 3β = 1` in `K₅`: the double root of `Ω` is `1/(3 b_{12,21})`. -/
theorem kappa_mul_three_beta (w : L) (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) :
    kappa w * (3 * betaPipe w) = 1 := by
  unfold kappa betaPipe
  linear_combination (((51959138870472861947700605457022792702977936832624118182437011485888114503035839930669206635215375843624893468433682756505466603803138571355) / 505318614682878669477462752790788234435320322863098947126354113340292863279157563791282165360655336363702607616540226423076632307928349540352 : L) + ((54958869911691472088008361927393583069346896111873241118103018067901784297774873673273042329681570029508390330303481037230429094026269257863) / 505318614682878669477462752790788234435320322863098947126354113340292863279157563791282165360655336363702607616540226423076632307928349540352 : L) * w + ((-57272004732977834768345392253844265958453397314775702239676240909650523210101018449014034311191207242321295265409707165570196784923939398461) / 1010637229365757338954925505581576468870640645726197894252708226680585726558315127582564330721310672727405215233080452846153264615856699080704 : L) * w ^ 2 + ((7019462482478665891726446172830815224467601354093356576201525827669237520897894431826537351141879084641939664853317730644150654871039089769) / 505318614682878669477462752790788234435320322863098947126354113340292863279157563791282165360655336363702607616540226423076632307928349540352 : L) * w ^ 3) * hw

/-- The vertex–edge condition `3β s₂ = t₂²` gives `Ω(t₂, s₂) = 0`. -/
theorem omega_of_edge (w t s : L) (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)
    (h : 3 * betaPipe w * s = t ^ 2) : c1 w * s ^ 2 + c2 w * t ^ 2 * s + c3 w * t ^ 4 = 0 := by
  rw [omega_square w t s hw]
  have hk : s - kappa w * t ^ 2 = 0 := by
    rw [← h]
    linear_combination (-s) * kappa_mul_three_beta w hw
  rw [hk]
  ring

/-- Conversely `Ω = 0` gives the edge condition (`c₁ ≠ 0`, `κ · 3β = 1`). -/
theorem edge_of_omega (w t s : L) (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)
    (h : c1 w * s ^ 2 + c2 w * t ^ 2 * s + c3 w * t ^ 4 = 0) : 3 * betaPipe w * s = t ^ 2 := by
  have hs := (omega_eq_zero_iff w t s hw).mp h
  rw [hs]
  linear_combination t ^ 2 * kappa_mul_three_beta w hw

/-- `betaPipe(9)` is `101`-integral and reduces to `70`; and `3 · 70 · 38 = 1` in `𝔽₁₀₁` (`κ ≡ 38`). -/
theorem betaPipe_at9_mod101 :
    ∃ n d : ℤ, betaPipe (9 : ℚ) = n / d ∧ (d : ZMod 101) ≠ 0 ∧ (n : ZMod 101) = 70 * d :=
  ⟨9702731089928968619782844259450608212930266472840290916159119252694573287073236215607515179957562605897965568, 46503954918585305403204072418460366544813871475545695116899726943055414257798807142241396511703739556981226369471393, by norm_num [betaPipe], by decide, by decide⟩

theorem three_mul_70_mul_38_mod101 : (3 * 70 * 38 : ZMod 101) = 1 := by decide

end BranchC.Omega

namespace BranchC

open MvPolynomial BranchAb

/-- **`Ω` from `J(P,Q) = λx²`.** In the pipeline normalization (`b_{12,21} = β(w)`), every branch-(c) pair
with `a_{8,14} ≠ 0` and `J(P,Q) = λx²` has `Ω(b_{12,22}, b_{12,23}) = 0`. -/
theorem omega_of_jac {L : Type*} [Field L] [CharZero L] (w : L)
    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) (lam : L) (P Q : MvPolynomial (Fin 2) L)
    (hP : ∀ m ∈ P.support, inNPc m) (hQ : ∀ m ∈ Q.support, inNQc m)
    (hJ : jac P Q = C lam * X 0 ^ 2) (hα : P.coeff (mono 8 14) ≠ 0)
    (hβ : Q.coeff (mono 12 21) = Omega.betaPipe w) :
    Omega.c1 w * Q.coeff (mono 12 23) ^ 2 + Omega.c2 w * Q.coeff (mono 12 22) ^ 2 * Q.coeff (mono 12 23) +
      Omega.c3 w * Q.coeff (mono 12 22) ^ 4 = 0 := by
  have h := (edge19_rigidity_of_jac lam P Q hP hQ hJ hα).1
  rw [hβ] at h
  exact Omega.omega_of_edge w _ _ hw h

end BranchC
