import Jacobian.BranchAbFinal
import Jacobian.BranchAbNewton
import Jacobian.BranchAbClassification

/-! Generated by gen_main.py.  The paper's Main Theorem 1.1 in Lean, conditional only on the top-layer
classification `TopLayerClassification` (Proposition 6.1), which is stated but not proved. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false

open MvPolynomial

noncomputable section

namespace BranchAb

/-- Layer data of `P` (weights 0, 1, 2) and `Q` (weights 0, …, 3) from the Newton-polygon supports. -/
theorem layers_of_support {K : Type*} [Field K] (P Q : MvPolynomial (Fin 2) K)
    (hP : ∀ m ∈ P.support, inNP m) (hQ : ∀ m ∈ Q.support, inNQ m) :
    P = layerPiece P 0 + layerPiece P 1 + layerPiece P 2 ∧
    Q = layerPiece Q 0 + layerPiece Q 1 + layerPiece Q 2 + layerPiece Q 3 := by
  constructor
  · have h := eq_sum_layerPiece P 2 (fun m hm => by have := hP m hm; unfold inNP at this; omega)
    simpa [Finset.sum_range_succ] using h
  · have h := eq_sum_layerPiece Q 3 (fun m hm => by have := hQ m hm; unfold inNQ at this; omega)
    simpa [Finset.sum_range_succ] using h

/-- **No completion of the K₅ orbit, at the level of `P` and `Q`.** -/
theorem no_completion_K5_PQ {L : Type*} [Field L] [CharZero L] (w : L)
    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) (lam : L) (P Q : MvPolynomial (Fin 2) L)
    (hP : ∀ m ∈ P.support, inNP m) (hQ : ∀ m ∈ Q.support, inNQ m)
    (hJ : jac P Q = C lam * X 0 ^ 2) (ρ σ ε : L) (hρ : ρ ≠ 0) (hσ : σ ≠ 0) (hε : ε ≠ 0)
    (tP : ∀ i, 1 ≤ i → i ≤ 8 → P.coeff (mono i (2 * i - 2)) = ρ * ε ^ (i - 1) * topA w i)
    (tQ : ∀ k, 2 ≤ k → k ≤ 12 → Q.coeff (mono k (2 * k - 3)) = σ * ε ^ (k - 2) * topB w k)
    (hv : Q.coeff (mono 12 24) ≠ 0) : False := by
  obtain ⟨hPs, hQs⟩ := layers_of_support P Q hP hQ
  have hJ' : jac (layerPiece P 0 + layerPiece P 1 + layerPiece P 2)
      (layerPiece Q 0 + layerPiece Q 1 + layerPiece Q 2 + layerPiece Q 3) = C lam * X 0 ^ 2 := by
    rw [← hPs, ← hQs]; exact hJ
  have sA₀ : ∀ i, (layerPoly P 0).coeff i ≠ 0 → 0 ≤ i ∧ i ≤ 8 :=
    layerPoly_support P 0 inNP hP 0 8 (fun i ha h => by unfold inNP at h; simp at h; omega)
  have sA₁ : ∀ i, (layerPoly P 1).coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8 :=
    layerPoly_support P 1 inNP hP 1 8 (fun i ha h => by unfold inNP at h; simp at h; omega)
  have sA₂ : ∀ i, (layerPoly P 2).coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8 :=
    layerPoly_support P 2 inNP hP 1 8 (fun i ha h => by unfold inNP at h; simp at h; omega)
  have sB₀ : ∀ i, (layerPoly Q 0).coeff i ≠ 0 → 0 ≤ i ∧ i ≤ 12 :=
    layerPoly_support Q 0 inNQ hQ 0 12 (fun i ha h => by unfold inNQ at h; simp at h; omega)
  have sB₁ : ∀ i, (layerPoly Q 1).coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 12 :=
    layerPoly_support Q 1 inNQ hQ 1 12 (fun i ha h => by unfold inNQ at h; simp at h; omega)
  have sB₂ : ∀ i, (layerPoly Q 2).coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12 :=
    layerPoly_support Q 2 inNQ hQ 2 12 (fun i ha h => by unfold inNQ at h; simp at h; omega)
  have sB₃ : ∀ i, (layerPoly Q 3).coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12 :=
    layerPoly_support Q 3 inNQ hQ 2 12 (fun i ha h => by unfold inNQ at h; simp at h; omega)
  have t_a_1_0 := by
    have h := tP 1 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 1 (by norm_num)] at h
    exact h
  have t_a_2_2 := by
    have h := tP 2 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 2 (by norm_num)] at h
    exact h
  have t_a_3_4 := by
    have h := tP 3 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 3 (by norm_num)] at h
    exact h
  have t_a_4_6 := by
    have h := tP 4 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 4 (by norm_num)] at h
    exact h
  have t_a_5_8 := by
    have h := tP 5 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 5 (by norm_num)] at h
    exact h
  have t_a_6_10 := by
    have h := tP 6 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 6 (by norm_num)] at h
    exact h
  have t_a_7_12 := by
    have h := tP 7 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 7 (by norm_num)] at h
    exact h
  have t_a_8_14 := by
    have h := tP 8 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le P 2 8 (by norm_num)] at h
    exact h
  have t_b_2_1 := by
    have h := tQ 2 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 2 (by norm_num)] at h
    exact h
  have t_b_3_3 := by
    have h := tQ 3 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 3 (by norm_num)] at h
    exact h
  have t_b_4_5 := by
    have h := tQ 4 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 4 (by norm_num)] at h
    exact h
  have t_b_5_7 := by
    have h := tQ 5 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 5 (by norm_num)] at h
    exact h
  have t_b_6_9 := by
    have h := tQ 6 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 6 (by norm_num)] at h
    exact h
  have t_b_7_11 := by
    have h := tQ 7 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 7 (by norm_num)] at h
    exact h
  have t_b_8_13 := by
    have h := tQ 8 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 8 (by norm_num)] at h
    exact h
  have t_b_9_15 := by
    have h := tQ 9 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 9 (by norm_num)] at h
    exact h
  have t_b_10_17 := by
    have h := tQ 10 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 10 (by norm_num)] at h
    exact h
  have t_b_11_19 := by
    have h := tQ 11 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 11 (by norm_num)] at h
    exact h
  have t_b_12_21 := by
    have h := tQ 12 (by norm_num) (by norm_num)
    rw [← coeff_layerPoly_of_le Q 3 12 (by norm_num)] at h
    exact h
  have hv' : (layerPoly Q 0).coeff 12 ≠ 0 := by
    rw [coeff_layerPoly_of_le Q 0 12 (by norm_num)]; exact hv
  refine no_completion_K5 w hw lam (layerPoly P 0) (layerPoly P 1) (layerPoly P 2) (layerPoly Q 0) (layerPoly Q 1) (layerPoly Q 2) (layerPoly Q 3) (layerPiece P 0) (layerPiece P 1) (layerPiece P 2) (layerPiece Q 0) (layerPiece Q 1) (layerPiece Q 2) (layerPiece Q 3) (X1_pow_mul_layerPiece P 0) (X1_pow_mul_layerPiece P 1) (X1_pow_mul_layerPiece P 2) (X1_pow_mul_layerPiece Q 0) (X1_pow_mul_layerPiece Q 1) (X1_pow_mul_layerPiece Q 2) (X1_pow_mul_layerPiece Q 3) hJ' sA₀ sA₁ sA₂ sB₀ sB₁ sB₂ sB₃ ρ σ ε hρ hσ hε ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  ?_  hv'
  · exact t_a_1_0
  · exact t_a_2_2
  · exact t_a_3_4
  · exact t_a_4_6
  · exact t_a_5_8
  · exact t_a_6_10
  · exact t_a_7_12
  · exact t_a_8_14
  · exact t_b_2_1
  · exact t_b_3_3
  · exact t_b_4_5
  · exact t_b_5_7
  · exact t_b_6_9
  · exact t_b_7_11
  · exact t_b_8_13
  · exact t_b_9_15
  · exact t_b_10_17
  · exact t_b_11_19
  · exact t_b_12_21

/-- **Main Theorem 1.1 of the paper, conditional on the top-layer classification.**  Over a field of
characteristic zero in which `TopLayerClassification` holds (for `ℂ`, this is the paper's
Proposition 6.1), there are no `P, Q` with the normal-form-(2) Newton polygons
`N(P) = conv{(0,0),(1,0),(8,14),(8,16)}` and `N(Q) = conv{(0,0),(2,1),(12,21),(12,24)}` and
`[P, Q] = λ x²` with `λ ≠ 0`.  GGHV Proposition 4.3, which reduces a (72,108) counterexample to the
normal forms, is not part of this statement. -/
theorem main_theorem_of_classification {L : Type*} [Field L] [CharZero L]
    (hcl : TopLayerClassification L) :
    ¬ ∃ (P Q : MvPolynomial (Fin 2) L) (lam : L), lam ≠ 0 ∧ NewtonNF2 P Q ∧ jac P Q = C lam * X 0 ^ 2 := by
  rintro ⟨P, Q, lam, -, ⟨hP, hQ, -, v10, v814, -, -, w21, w1221, w1224⟩, hJ⟩
  obtain ⟨hPs, hQs⟩ := layers_of_support P Q hP hQ
  have hJ' : jac (layerPiece P 0 + layerPiece P 1 + layerPiece P 2)
      (layerPiece Q 0 + layerPiece Q 1 + layerPiece Q 2 + layerPiece Q 3) = C lam * X 0 ^ 2 := by
    rw [← hPs, ← hQs]; exact hJ
  obtain ⟨E5, -, -, -, -⟩ := layers_of_jac lam _ _ _ _ _ _ _ _ _ _ _ _ _ _
    (X1_pow_mul_layerPiece P 0) (X1_pow_mul_layerPiece P 1) (X1_pow_mul_layerPiece P 2)
    (X1_pow_mul_layerPiece Q 0) (X1_pow_mul_layerPiece Q 1) (X1_pow_mul_layerPiece Q 2)
    (X1_pow_mul_layerPiece Q 3) hJ'
  have sA₂ : ∀ i, (layerPoly P 2).coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8 :=
    layerPoly_support P 2 inNP hP 1 8 (fun i ha h => by unfold inNP at h; simp at h; omega)
  have sB₃ : ∀ i, (layerPoly Q 3).coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12 :=
    layerPoly_support Q 3 inNQ hQ 2 12 (fun i ha h => by unfold inNQ at h; simp at h; omega)
  have a1 : (layerPoly P 2).coeff 1 ≠ 0 := by rw [coeff_layerPoly_of_le P 2 1 (by norm_num)]; exact v10
  have a8 : (layerPoly P 2).coeff 8 ≠ 0 := by rw [coeff_layerPoly_of_le P 2 8 (by norm_num)]; exact v814
  have b2 : (layerPoly Q 3).coeff 2 ≠ 0 := by rw [coeff_layerPoly_of_le Q 3 2 (by norm_num)]; exact w21
  have b12 : (layerPoly Q 3).coeff 12 ≠ 0 := by rw [coeff_layerPoly_of_le Q 3 12 (by norm_num)]; exact w1221
  obtain ⟨w, ρ, σ, ε, hw, hρ, hσ, hε, hA, hB⟩ := hcl _ _ lam sA₂ sB₃ a1 a8 b2 b12 E5
  refine no_completion_K5_PQ w hw lam P Q hP hQ hJ ρ σ ε hρ hσ hε ?_ ?_ w1224
  · intro i hi1 hi8
    rw [← coeff_layerPoly_of_le P 2 i (by omega)]; exact hA i
  · intro k hk2 hk12
    rw [← coeff_layerPoly_of_le Q 3 k (by omega)]; exact hB k

end BranchAb
