"""gen_lean.py -- Lean modules that let the kernel check C * M_S = I (mod p), C = M_S^{-1}, in packed form.

Encoding (README.md, "Why packed"): a vector v in F_p^n (n = 3199) is the natural number  sum_k v_k 2^(40 k)
(40-bit slots).  Cpk_i packs column i of C.  For every pivot column j of M_S, with entries (i_t, v_t):
    slot_i : slotOK Cpk_i = true          every slot of Cpk_i is < 2^15, and Cpk_i < 2^(40 n)
    col_j  : colOK j (v_1 * Cpk_{i_1} + ... + v_m * Cpk_{i_m}) = true
             the sum X equals p * Q + 2^(40 j) with every slot of Q < 2^22.
No slot can carry (m <= 52, v_t < p < 2^15: m * 2^30 < 2^36 < 2^40; p * (2^22 - 1) + 1 < 2^40), so base-2^40 digits
give  sum_t v_t C[k, i_t] = p Q_k + delta_kj  for every k, i.e. (C M_S)[k, j] = delta_kj mod p.  That implication is
pen and paper (step A1 of the grade-A plan formalizes it); the Lean theorems are the natural-number identities.
Files written to OUTDIR:
  RCCommon.lean               definitions (ofChunks, maskQ, maskC, colOK, slotOK)
  RCData00..RCData{K-1}.lean  the packed columns of C, each literal written as 8192-bit chunks (ofChunks)
  RCCheck00..RCCheck{K-1}.lean  slot_i and col_j for i, j in the module's range, and two #print axioms
  RCControls.lean, RCControls.expect.json   five perturbed statements that must fail, one that must pass
  MANIFEST.sha256             sha256 of every generated file
usage: python3 gen_lean.py INVERSE.pkl OUTDIR [K]      (K modules of each kind, default 8)
"""
import sys, os, pickle, hashlib, json
import numpy as np

d = pickle.load(open(sys.argv[1], "rb"))
OUT = sys.argv[2]
K = int(sys.argv[3]) if len(sys.argv) > 3 else 8
p, C, colv = d["p"], d["C"], d["colv"]
n = C.shape[0]
S_, B_, T_, CH = 40, 15, 22, 8192                 # slot width, slot bound of C and of the coefficients, of Q; chunk
m_max = max(len(c) for c in colv)
assert p < 2 ** B_ and int(C.max()) < p and min(v for c in colv for _, v in c) > 0
assert all(v < p for c in colv for _, v in c)
assert m_max * 2 ** (2 * B_) < 2 ** S_, "a slot of X could carry"
assert p * (2 ** T_ - 1) + 1 < 2 ** S_, "a slot of p Q + E could carry"
assert m_max * 2 ** (2 * B_) // p < 2 ** T_, "a correct certificate would fail the Q mask"
os.makedirs(OUT, exist_ok=True)
NB = (n * S_ + 7) // 8                            # bytes of one packed column
digest = hashlib.sha256()


def packed_bytes(i):
    """column i of C as n 40-bit little-endian slots"""
    b = C[:, i].astype("<u8").view(np.uint8).reshape(n, 8)[:, :S_ // 8].tobytes()
    assert len(b) == NB
    return b


def chunks_be(b):
    """big-endian list of CH-bit chunks of the little-endian byte string b"""
    cb = CH // 8
    return [int.from_bytes(b[t * cb:(t + 1) * cb], "little") for t in range((len(b) + cb - 1) // cb)][::-1]


written = []


def write(name, text):
    path = os.path.join(OUT, name)
    with open(path, "w") as fh:
        fh.write(text)
    written.append(path)


NS = "BranchC.RankCheck"
write("RCCommon.lean", f"""/-!
# Branch (c): packed kernel check of C * M_S = I (mod {p}), C = M_S⁻¹

Generated by `branch_c/rank_lemma_check/gen_lean.py`. A vector `v ∈ 𝔽_p^{n}` is packed into `∑ k, v k * 2 ^ ({S_} * k)`.
`Cpk_i` packs column `i` of `C`. `slotOK x`: every slot of `x` is `< 2 ^ {B_}` and `x < 2 ^ ({S_} * {n})`.
`colOK j X`: `X = {p} * Q + 2 ^ ({S_} * j)` with every slot of `Q` `< 2 ^ {T_}`.
With at most {m_max} terms and coefficients `< {p}`, no slot carries, so `colOK j (∑ t, v t * Cpk (i t))` and `slotOK` of
each `Cpk (i t)` give `∑ t, v t * C[k, i t] ≡ δ k j [MOD {p}]` for every `k`. That implication is not formalized here;
the theorems are identities between natural numbers, checked by the kernel (`decide +kernel`, no `native_decide`).
-/

namespace {NS}

/-- big-endian chunks of {CH} bits -/
def ofChunks (l : List Nat) : Nat := l.foldl (fun acc c => (acc <<< {CH}) ||| c) 0

/-- bits {T_}..{S_ - 1} of every slot -/
def maskQ : Nat := (2 ^ {S_} - 2 ^ {T_}) * ((2 ^ ({S_} * {n}) - 1) / (2 ^ {S_} - 1))

/-- bits {B_}..{S_ - 1} of every slot -/
def maskC : Nat := (2 ^ {S_} - 2 ^ {B_}) * ((2 ^ ({S_} * {n}) - 1) / (2 ^ {S_} - 1))

/-- `X = {p} * Q + 2 ^ ({S_} * j)` with every slot of `Q` below `2 ^ {T_}` -/
def colOK (j X : Nat) : Bool :=
  let E := 2 ^ ({S_} * j)
  let Q := (X - E) / {p}
  ({p} * Q + E == X) && (Q &&& maskQ == 0)

/-- every slot below `2 ^ {B_}`, and no slot beyond the {n}th -/
def slotOK (x : Nat) : Bool := (x &&& maskC == 0) && (x >>> ({S_} * {n}) == 0)

end {NS}
""")
blk = (n + K - 1) // K
for k in range(K):
    lines = ["import RCCommon", "", f"/-! packed columns {k * blk}..{min(n, (k + 1) * blk) - 1} of C -/", "",
             f"namespace {NS}", ""]
    for i in range(k * blk, min(n, (k + 1) * blk)):
        b = packed_bytes(i)
        digest.update(b)
        lines.append(f"noncomputable def Cpk_{i} : Nat := ofChunks [" +
                     ", ".join(f"0x{c:x}" for c in chunks_be(b)) + "]")
    lines += ["", f"end {NS}", ""]
    write(f"RCData{k:02d}.lean", "\n".join(lines))
imports = [f"import RCData{t:02d}" for t in range(K)]


def col_term(j, drop_last=False, bump=None, coeff_plus=False):
    terms = []
    entries = colv[j][:-1] if drop_last else colv[j]
    for t, (i, v) in enumerate(entries):
        x = f"Cpk_{i}" if (bump is None or t != 0) else f"(Cpk_{i} + 2 ^ ({S_} * {bump}))"
        vv = v + 1 if (coeff_plus and t == 0) else v
        terms.append(f"{vv} * {x}")
    return " + ".join(terms)


ntheorems = 0
for k in range(K):
    lo, hi = k * blk, min(n, (k + 1) * blk)
    lines = imports + ["", "set_option maxRecDepth 100000", "", f"namespace {NS}", ""]
    for i in range(lo, hi):
        lines.append(f"theorem slot_{i} : slotOK Cpk_{i} = true := by decide +kernel")
    for j in range(lo, hi):
        lines.append(f"theorem col_{j} : colOK {j} ({col_term(j)}) = true := by decide +kernel")
    ntheorems += 2 * (hi - lo)
    lines += ["", f"#print axioms col_{lo}", f"#print axioms slot_{lo}", "", f"end {NS}", ""]
    write(f"RCCheck{k:02d}.lean", "\n".join(lines))
# controls: one column with the largest support
jc = next(j for j in range(n - 1) if len(colv[j]) == m_max)
i0 = colv[jc][0][0]
lines = imports + ["", "set_option maxRecDepth 100000", "",
                   "/-! negative controls: each `ctrl_fail_*` must be rejected by the kernel; `ctrl_pass` must pass -/",
                   "", f"namespace {NS}", ""]
expect = {"pass": {}, "fail": {}}
ctrl = [("ctrl_pass", "pass", f"colOK {jc} ({col_term(jc)})"),
        ("ctrl_fail_entry", "fail", f"colOK {jc} ({col_term(jc, bump=7)})"),
        ("ctrl_fail_coeff", "fail", f"colOK {jc} ({col_term(jc, coeff_plus=True)})"),
        ("ctrl_fail_index", "fail", f"colOK {jc + 1} ({col_term(jc)})"),
        ("ctrl_fail_drop", "fail", f"colOK {jc} ({col_term(jc, drop_last=True)})"),
        ("ctrl_fail_slot", "fail", f"slotOK (Cpk_{i0} + 2 ^ {B_} * 2 ^ ({S_} * 5))")]
for name, kind, stmt in ctrl:
    lines.append(f"theorem {name} : {stmt} = true := by decide +kernel")
    expect[kind][str(len(lines))] = name
lines += ["", "#print axioms ctrl_pass", "", f"end {NS}", ""]
write("RCControls.lean", "\n".join(lines))
write("RCControls.expect.json", json.dumps({"column": jc, "entry": i0, **expect}, indent=1) + "\n")
with open(os.path.join(OUT, "MANIFEST.sha256"), "w") as fh:
    for path in sorted(written):
        fh.write(hashlib.sha256(open(path, "rb").read()).hexdigest() + "  " + os.path.basename(path) + "\n")
size = sum(os.path.getsize(x) for x in written)
print(f"n = {n}, p = {p}, at most {m_max} terms per column; {K} data + {K} check modules, {ntheorems} theorems, "
      f"{size / 1e6:.1f} MB of Lean; sha256 of the packed columns {digest.hexdigest()}")
print(f"controls on column {jc} (entry Cpk_{i0}): {len(expect['fail'])} must fail, {len(expect['pass'])} must pass")
