import Jacobian.ChartProof.Reflect

/-! Generated by `gen_v2.py`: Proposition 6.1 (`ChartClassification`), reflected polynomials of the base facts
Every polynomial identity is checked by the Lean kernel (`decide +kernel` on `toPolyK`, see `Reflect.lean`);
every certificate was also verified by exact SymPy expansion before emission. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false

namespace BranchAb.ChartProof
open Lean.Grind.CommRing

variable {α : Type*} [CommRing α]

/-- fact `E1` -/
noncomputable def e_E1 : Expr :=
  (.add (.mul (.num 3) (.var 8)) (.mul (.mul (.num (-2)) (.var 0)) (.var 7)))

/-- fact `E2` -/
noncomputable def e_E2 : Expr :=
  (.add (.mul (.num 5) (.var 9)) (.mul (.mul (.num (-5)) (.var 1)) (.var 7)))

/-- fact `E3` -/
noncomputable def e_E3 : Expr :=
  (.add (.add (.add (.mul (.num 7) (.var 10)) (.mul (.mul (.num 2) (.var 0)) (.var 9))) (.mul (.mul (.num (-3)) (.var 1)) (.var 8))) (.mul (.mul (.num (-8)) (.var 2)) (.var 7)))

/-- fact `E4` -/
noncomputable def e_E4 : Expr :=
  (.add (.add (.add (.add (.mul (.num 9) (.var 11)) (.mul (.mul (.num 4) (.var 0)) (.var 10))) (.mul (.mul (.num (-1)) (.var 1)) (.var 9))) (.mul (.mul (.num (-6)) (.var 2)) (.var 8))) (.mul (.mul (.num (-11)) (.var 3)) (.var 7)))

/-- fact `E5` -/
noncomputable def e_E5 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.num 11) (.var 12)) (.mul (.mul (.num 6) (.var 0)) (.var 11))) (.mul (.mul (.num 1) (.var 1)) (.var 10))) (.mul (.mul (.num (-4)) (.var 2)) (.var 9))) (.mul (.mul (.num (-9)) (.var 3)) (.var 8))) (.mul (.mul (.num (-14)) (.var 4)) (.var 7)))

/-- fact `E6` -/
noncomputable def e_E6 : Expr :=
  (.add (.add (.add (.add (.add (.add (.mul (.num 13) (.var 13)) (.mul (.mul (.num 8) (.var 0)) (.var 12))) (.mul (.mul (.num 3) (.var 1)) (.var 11))) (.mul (.mul (.num (-2)) (.var 2)) (.var 10))) (.mul (.mul (.num (-7)) (.var 3)) (.var 9))) (.mul (.mul (.num (-12)) (.var 4)) (.var 8))) (.mul (.mul (.num (-17)) (.var 5)) (.var 7)))

/-- fact `E7` -/
noncomputable def e_E7 : Expr :=
  (.add (.add (.add (.add (.add (.add (.mul (.num 15) (.var 14)) (.mul (.mul (.num 10) (.var 0)) (.var 13))) (.mul (.mul (.num 5) (.var 1)) (.var 12))) (.mul (.mul (.num (-5)) (.var 3)) (.var 10))) (.mul (.mul (.num (-10)) (.var 4)) (.var 9))) (.mul (.mul (.num (-15)) (.var 5)) (.var 8))) (.mul (.mul (.num (-20)) (.var 6)) (.var 7)))

/-- fact `E8` -/
noncomputable def e_E8 : Expr :=
  (.add (.add (.add (.add (.add (.add (.add (.mul (.num 17) (.var 15)) (.mul (.mul (.num 12) (.var 0)) (.var 14))) (.mul (.mul (.num 7) (.var 1)) (.var 13))) (.mul (.mul (.num 2) (.var 2)) (.var 12))) (.mul (.mul (.num (-3)) (.var 3)) (.var 11))) (.mul (.mul (.num (-8)) (.var 4)) (.var 10))) (.mul (.mul (.num (-13)) (.var 5)) (.var 9))) (.mul (.mul (.num (-18)) (.var 6)) (.var 8)))

/-- fact `E9` -/
noncomputable def e_E9 : Expr :=
  (.add (.add (.add (.add (.add (.add (.add (.mul (.num 19) (.var 16)) (.mul (.mul (.num 14) (.var 0)) (.var 15))) (.mul (.mul (.num 9) (.var 1)) (.var 14))) (.mul (.mul (.num 4) (.var 2)) (.var 13))) (.mul (.mul (.num (-1)) (.var 3)) (.var 12))) (.mul (.mul (.num (-6)) (.var 4)) (.var 11))) (.mul (.mul (.num (-11)) (.var 5)) (.var 10))) (.mul (.mul (.num (-16)) (.var 6)) (.var 9)))

/-- fact `E10` -/
noncomputable def e_E10 : Expr :=
  (.add (.add (.add (.add (.add (.add (.add (.num 21) (.mul (.mul (.num 16) (.var 0)) (.var 16))) (.mul (.mul (.num 11) (.var 1)) (.var 15))) (.mul (.mul (.num 6) (.var 2)) (.var 14))) (.mul (.mul (.num 1) (.var 3)) (.var 13))) (.mul (.mul (.num (-4)) (.var 4)) (.var 12))) (.mul (.mul (.num (-9)) (.var 5)) (.var 11))) (.mul (.mul (.num (-14)) (.var 6)) (.var 10)))

/-- fact `E11` -/
noncomputable def e_E11 : Expr :=
  (.add (.add (.add (.add (.add (.add (.mul (.num 18) (.var 0)) (.mul (.mul (.num 13) (.var 1)) (.var 16))) (.mul (.mul (.num 8) (.var 2)) (.var 15))) (.mul (.mul (.num 3) (.var 3)) (.var 14))) (.mul (.mul (.num (-2)) (.var 4)) (.var 13))) (.mul (.mul (.num (-7)) (.var 5)) (.var 12))) (.mul (.mul (.num (-12)) (.var 6)) (.var 11)))

/-- fact `E12` -/
noncomputable def e_E12 : Expr :=
  (.add (.add (.add (.add (.mul (.num 15) (.var 1)) (.mul (.mul (.num 10) (.var 2)) (.var 16))) (.mul (.mul (.num 5) (.var 3)) (.var 15))) (.mul (.mul (.num (-5)) (.var 5)) (.var 13))) (.mul (.mul (.num (-10)) (.var 6)) (.var 12)))

/-- fact `E13` -/
noncomputable def e_E13 : Expr :=
  (.add (.add (.add (.add (.mul (.num 12) (.var 2)) (.mul (.mul (.num 7) (.var 3)) (.var 16))) (.mul (.mul (.num 2) (.var 4)) (.var 15))) (.mul (.mul (.num (-3)) (.var 5)) (.var 14))) (.mul (.mul (.num (-8)) (.var 6)) (.var 13)))

/-- fact `E14` -/
noncomputable def e_E14 : Expr :=
  (.add (.add (.add (.mul (.num 9) (.var 3)) (.mul (.mul (.num 4) (.var 4)) (.var 16))) (.mul (.mul (.num (-1)) (.var 5)) (.var 15))) (.mul (.mul (.num (-6)) (.var 6)) (.var 14)))

/-- fact `E15` -/
noncomputable def e_E15 : Expr :=
  (.add (.add (.mul (.num 6) (.var 4)) (.mul (.mul (.num 1) (.var 5)) (.var 16))) (.mul (.mul (.num (-4)) (.var 6)) (.var 15)))

/-- fact `E16` -/
noncomputable def e_E16 : Expr :=
  (.add (.mul (.num 3) (.var 5)) (.mul (.mul (.num (-2)) (.var 6)) (.var 16)))

/-- fact `hc` -/
noncomputable def e_hc : Expr :=
  (.sub (.mul (.pow (.var 6) 3) (.pow (.var 7) 2)) (.num 1))

/-- fact `h7` -/
noncomputable def e_h7 : Expr :=
  (.sub (.mul (.var 6) (.var 23)) (.num 1))

/-- fact `hy1` -/
noncomputable def e_hy1 : Expr :=
  (.sub (.var 17) (.mul (.var 5) (.var 23)))

/-- fact `hy2` -/
noncomputable def e_hy2 : Expr :=
  (.sub (.var 18) (.mul (.var 4) (.var 23)))

/-- fact `hy3` -/
noncomputable def e_hy3 : Expr :=
  (.sub (.var 19) (.mul (.var 3) (.var 23)))

/-- fact `hy4` -/
noncomputable def e_hy4 : Expr :=
  (.sub (.var 20) (.mul (.var 2) (.var 23)))

/-- fact `hy5` -/
noncomputable def e_hy5 : Expr :=
  (.sub (.var 21) (.mul (.var 1) (.var 23)))

/-- fact `hy6` -/
noncomputable def e_hy6 : Expr :=
  (.sub (.var 22) (.mul (.var 0) (.var 23)))

/-- fact `hz` -/
noncomputable def e_hz : Expr :=
  (.sub (.mul (.var 17) (.var 24)) (.num 1))

/-- fact `ht` -/
noncomputable def e_ht : Expr :=
  (.sub (.var 25) (.mul (.var 18) (.pow (.var 24) 2)))

/-- fact `hs` -/
noncomputable def e_hs : Expr :=
  (.sub (.var 26) (.mul (.var 19) (.pow (.var 24) 3)))

/-- fact `hw` -/
noncomputable def e_hw : Expr :=
  (.add (.add (.mul (.num (-31642107907812730546074660864)) (.pow (.var 25) 4)) (.add (.mul (.num 63153326468921041008545036544) (.pow (.var 25) 3)) (.mul (.num (-45353901565403156624748102720)) (.pow (.var 25) 2)))) (.add (.mul (.num 14083731851483710942235733124) (.var 25)) (.add (.mul (.num 26932788405521129134848) (.var 27)) (.num (-1608567198961093006910097135)))))

end BranchAb.ChartProof
