import Jacobian.BranchC.Descent2R.Bridge
import Jacobian.BranchC.T1Zero.Main

/-! Generated by certgen_c/gen_t1zero_combine.py.  **The stratum `b₁₁,₂₀ = 0` of the branch-(c) chart statement.**

`ChartEmptyC` (Bridge.lean) splits along `b₁₁,₂₀ = 0`.  That stratum is `T1Zero.chartEmpty_t1_zero`, checked by the
kernel from the exact slice certificate of step 1.  What remains is `ChartEmptyC_T1ne0`: the same statement with the
extra hypothesis `b₁₁,₂₀ ≠ 0`.  It is NOT proved in Lean.  The evidence for it is modular certificates only: 𝔽₁₀₁,
𝔽₁₀₀₀₀₀₃, 𝔽_{109⁵}; see BRANCH_C_LEAN_STATUS.md.  No `sorry`, no new axioms. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false

open MvPolynomial

noncomputable section

namespace BranchC

open BranchAb

/-- **What remains of the branch-(c) chart statement** (open): `ChartEmptyC` restricted to `b₁₁,₂₀ ≠ 0`. -/
def ChartEmptyC_T1ne0 (L : Type*) [Field L] : Prop :=
  ∀ (w : L), w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0 →
  ∀ (b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 : L), b_12_22 = 1 → b_11_20 ≠ 0 →
    cond_Omega w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Psi w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Phi1 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Phi2 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Theta1 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Theta2 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Theta3 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_E0pure_18_37 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Em1pure_17_36 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Em1pure_18_38 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Em2pure_16_35 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 →
    cond_Em2pure_17_37 w b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 = 0 → False

/-- `ChartEmptyC` from its `b₁₁,₂₀ ≠ 0` part; the stratum `b₁₁,₂₀ = 0` is `T1Zero.chartEmpty_t1_zero`. -/
theorem chartEmptyC_of_T1ne0 (L : Type*) [Field L] [CharZero L] (h : ChartEmptyC_T1ne0 L) : ChartEmptyC L := by
  intro w hw b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 ht2 c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11
  by_cases ht1 : b_11_20 = 0
  · exact T1Zero.chartEmpty_t1_zero w hw b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 ht1 ht2 c0 c1 c2 c3 c4 c5 c6
  · exact h w hw b_11_20 b_12_22 b_11_21 b_12_23 a_6_13 a_7_15 b_10_21 ht2 ht1 c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11

/-- **`DescentClaimC` modulo `ChartEmptyC_T1ne0`.** -/
theorem descentClaimC_of_chartEmpty_T1ne0 (L : Type*) [Field L] [CharZero L] (h : ChartEmptyC_T1ne0 L) :
    DescentClaimC L :=
  descentClaimC_of_chartEmpty L (chartEmptyC_of_T1ne0 L h)

/-- **Branch (c) of the Jacobian conjecture (GGHV Prop. 4.3 case (1)), modulo `ChartEmptyC_T1ne0`.** -/
theorem main_theorem_c_of_chartEmpty_T1ne0 {L : Type*} [Field L] [CharZero L] (h : ChartEmptyC_T1ne0 L) :
    ¬ ∃ (P Q : MvPolynomial (Fin 2) L) (lam : L), lam ≠ 0 ∧ NewtonNFc P Q ∧ jac P Q = C lam * X 0 ^ 2 :=
  main_theorem_c_of_claim (descentClaimC_of_chartEmpty_T1ne0 L h)

end BranchC
