"""
mk_singular.py -- write a Singular script for the system of gen_system.py

usage: python3 mk_singular.py CHAR NORMALIZE ZVERTS OUT.sing
  CHAR       : 0 or a prime
  NORMALIZE  : comma list of variables set to 1 (torus normalisation), or 'none'
  ZVERTS     : comma list of vertex variables v for which z_v*v-1 is added, or 'none'
The ideal is written as 'I'; nothing is computed here.
"""
import sys
from gen_system import build


def polys_for(norm, zv, lamname="lam"):
    LP, LQ, eqs, tgt = build()
    avars = [f"a_{i}_{j}" for (i, j) in LP if (i, j) != (0, 0)]
    bvars = [f"b_{i}_{j}" for (i, j) in LQ if (i, j) != (0, 0)]
    allv = [v for v in avars + bvars if v not in norm] + [lamname] + [f"z_{v}" for v in zv]
    tok = lambda v: "1" if v in norm else v
    polys = []
    for key in sorted(eqs):
        terms = [f"({c})*{tok(p)}*{tok(q)}" for c, p, q in eqs[key]]
        s = "+".join(terms) if terms else "0"
        if key == tgt:
            s += f"-{lamname}"
        polys.append(s)
    for v in zv:
        polys.append(f"z_{v}*{tok(v)}-1")
    return allv, polys


if __name__ == "__main__":
    char = int(sys.argv[1])
    norm = [] if sys.argv[2] == "none" else sys.argv[2].split(",")
    zv = [] if sys.argv[3] == "none" else sys.argv[3].split(",")
    out = sys.argv[4]
    allv, polys = polys_for(norm, zv)
    with open(out, "w") as f:
        f.write(f"// generated by mk_singular.py char={char} norm={norm} z={zv}\n")
        f.write(f"ring R = {char}, ({','.join(allv)}), dp;\n")
        f.write("ideal I =\n  " + ",\n  ".join(polys) + ";\n")
