"""gen_b26_lean.py -- writes B26.lean: the m = 3 and m = 5 top-layer chart systems (B2.6), classified over any field
of characteristic 0, with every step a `linear_combination` whose cofactors are explicit (Singular lift, checked in
Singular's own ring and again here with sympy before they are written).

Inputs (this directory): lift_S_to_J.txt, lift_J_to_S.txt (m = 5), m3_lift_S_to_J.txt, m3_lift_J_to_S.txt (m = 3),
the residuals r0..r3 copied from the repository's scripts/b26_m5_eliminant/m5_b2_6_eliminate_basis.sing (A816 env var
not needed).  usage: python3 gen_b26_lean.py RESIDUALS.sing OUT.lean"""
import sys, re
import sympy as sp
from chart_small import chart_residuals

sys.set_int_max_str_digits(0)
res_sing, out = sys.argv[1], sys.argv[2]


def lean_coef(c):
    c = sp.Rational(c)
    if c.q == 1:
        return f"({c.p})" if c.p < 0 else f"{c.p}"
    return f"({c.p}/{c.q})"


def lean_poly(e, gens):
    e = sp.expand(e)
    if e == 0:
        return "0"
    P = sp.Poly(e, *gens)
    parts = []
    for mon, c in P.terms():
        fs = []
        for v, k in zip(gens, mon):
            if k == 1:
                fs.append(str(v))
            elif k > 1:
                fs.append(f"{v}^{k}")
        if not fs:
            parts.append(lean_coef(c))
        elif c == 1:
            parts.append(" * ".join(fs))
        else:
            parts.append(lean_coef(c) + " * " + " * ".join(fs))
    return " + ".join(parts)


def read_lift(fn, gens):
    loc = {str(g): g for g in gens}
    d = {}
    for line in open(fn):
        j, i, p = line.rstrip("\n").split("|", 2)
        d[(int(j), int(i))] = sp.expand(sp.sympify(p.replace("^", "**"), locals=loc))
    return d


def chart_data(m):
    """E_N (N = 1 .. n+m) as bilinear expressions in a_1..a_{m-1}, b_1..b_n; B_k(a); residual polynomials."""
    n = (3 * m - 1) // 2
    a, A, Bk, R = chart_residuals(m)
    b = sp.symbols(f"b1:{n + 1}")
    beta = [sp.Integer(1)] + list(b)
    E = {}
    for N in range(1, n + m + 1):
        E[N] = sp.expand(sum((1 + 2 * k - 3 * (N - k)) * A[N - k] * beta[k] for k in range(0, n + 1) if 0 <= N - k <= m))
    return a, b, A, Bk, R, E, n


L = []
w = L.append
w("""import Mathlib

/-!
# The `m = 3` and `m = 5` top-layer chart systems (B2.6), classified in characteristic 0

Generated by `gen_b26_lean.py` (repository `scripts/b26_m5_eliminant/lean_certificates/`).  This file replaces the
2026-10-05 skeleton `B26.lean`, whose statements were over `ℚ`, where the eliminant has no root, so they would have
been vacuous; it also did not compile (`QQ` is not a Mathlib name).

The top-layer equation `E₅` of the paper (eq. `e5`) is `α β + u (2 α β' - 3 α' β) = 1` with `deg α = m`,
`deg β = n = (3m - 1)/2`.  In the chart `α₀ = α_m = 1`, `β₀ = 1` (paper, proof of Proposition `prop:top-class`)
write `α = 1 + a₁ u + ⋯ + a_{m-1} u^{m-1} + u^m` and `β = 1 + b₁ u + ⋯ + b_n u^n`.  The coefficient of `u^N` is
`E_N = Σ_{i+k=N} (1 + 2k - 3i) α_i β_k`; `E₀ = 1` holds automatically, and `m5Chart`/`m3Chart` below are the
equations `E_N = 0` for `N = 1, …, n + m` (the last one is identically zero because `1 + 2n - 3m = 0`).

Main results, over any field `L` of characteristic 0:
* `m5_chart_iff`: the `m = 5` chart system holds iff `T₅(a₄) = 0`, `a₁, a₂, a₃` are the explicit functions of `a₄`
  (`362 a₄ a₁ = 3 a₄⁵ + 13078`, `181 a₄² a₂ = 15 a₄⁵ + 32448`, `2172 a₄³ a₃ = 861 a₄⁵ + 492128`), and
  `b₁, …, b₇` are the explicit polynomials `m5B1 … m5B7` in `a₁, …, a₄`.
* `m5_residual_iff`: CAIC's residuals `r₀, …, r₃` (`r_k = 3003 · E_{8+k}` once `β` is eliminated) cut out exactly
  the same set as `T₅(a₄)` and the three back-substitution relations (an equality of ideals, both inclusions
  certified).
* `m5_T_ne_zero_at_zero`, `m5_a4_ne_zero`, `m5_T_squarefree`: `T₅(0) ≠ 0`, so `a₄ ≠ 0`; `T₅` and `T₅'` have no
  common root.  Hence over an algebraically closed field the chart system has exactly `10` solutions, one for each
  of the `10` distinct roots of `T₅` (the count is this bijection plus `deg T₅ = 10`; it is not restated as a
  separate Lean theorem).
* the same for `m = 3` with `T₃(a₂) = 3 a₂³ - 32` and `8 a₁ = 5 a₂²` (`m3_chart_iff`, `m3_residual_iff`,
  `m3_a2_ne_zero`, `m3_T_squarefree`).
The irreducibility of `T₅` and `T₃` over `ℚ` is not used and is not formalized here.
-/

set_option maxHeartbeats 0
set_option linter.unusedVariables false

namespace BranchAb.TopLayerSmall

variable {L : Type*} [Field L] [CharZero L]
""")

# ---------------------------------------------------------------- m = 5
a5, b5, A5, B5, R5, E5, n5 = chart_data(5)
a1, a2, a3, a4 = a5
src = open(res_sing).read()
loc = {str(g): g for g in a5}
r = [sp.expand(sp.sympify(re.search(rf"poly r{k} = (.*?);", src).group(1).replace("^", "**"), locals=loc)) for k in range(4)]
for k in range(4):
    assert sp.expand(r[k] - 3003 * R5[8 + k]) == 0, k
T5 = 9 * a4**10 + 37200 * a4**5 + 95051008
Jrel = [T5, 362 * a4 * a1 - 3 * a4**5 - 13078, 181 * a4**2 * a2 - 15 * a4**5 - 32448, 2172 * a4**3 * a3 - 861 * a4**5 - 492128]
CJ = read_lift("lift_S_to_J.txt", a5)      # J[j] = sum_i r[i] * CJ[j, i]
CS = read_lift("lift_J_to_S.txt", a5)      # r[j] = sum_i J[i] * CS[j, i]
for j in range(1, 5):
    assert sp.expand(sum(r[i - 1] * CJ[(j, i)] for i in range(1, 5)) - Jrel[j - 1]) == 0, ("S->J", j)
    assert sp.expand(sum(Jrel[i - 1] * CS[(j, i)] for i in range(1, 5)) - r[j - 1]) == 0, ("J->S", j)
args4 = "(a1 a2 a3 a4 : L)"
use4 = "a1 a2 a3 a4"
w("/-! ## `m = 5` -/\n")
w(f"/-- The `m = 5` eliminant `T₅(x) = 9 x¹⁰ + 37200 x⁵ + 95051008`. -/\ndef m5T (x : L) : L := 9 * x^10 + 37200 * x^5 + 95051008\n")
for k in range(4):
    w(f"/-- CAIC's residual `r{k}` (`= 3003 · E_{8 + k}` after eliminating `β`; repository file "
      f"`scripts/b26_m5_eliminant/m5_b2_6_eliminate_basis.sing`). -/\n"
      f"def m5r{k} {args4} : L :=\n  {lean_poly(r[k], a5)}\n")
for k in range(1, n5 + 1):
    w(f"/-- `b{k}` in terms of `a₁, …, a₄` (solved from `E_{k}`). -/\ndef m5B{k} {args4} : L :=\n  {lean_poly(B5[k], a5)}\n")
bargs = " ".join(str(x) for x in b5)
chart_eqs = " ∧\n    ".join(f"{lean_poly(E5[N], list(a5) + list(b5))} = 0" for N in range(1, n5 + 5 + 1))
w(f"/-- The `m = 5` chart system: `E_N = 0` for `N = 1, …, 12`. -/\n"
  f"def m5Chart (a1 a2 a3 a4 {bargs} : L) : Prop :=\n    {chart_eqs}\n")
names = ["m5T a4", "362 * a4 * a1 = 3 * a4^5 + 13078", "181 * a4^2 * a2 = 15 * a4^5 + 32448", "2172 * a4^3 * a3 = 861 * a4^5 + 492128"]
hyp_r = " ".join(f"(h{k} : m5r{k} {use4} = 0)" for k in range(4))
for j, nm in enumerate(["T", "rel1", "rel2", "rel3"], 1):
    goal = "m5T a4 = 0" if j == 1 else names[j - 1]
    lc = " + ".join(f"({lean_poly(CJ[(j, i)], a5)}) * h{i - 1}" for i in range(1, 5) if CJ[(j, i)] != 0)
    w(f"theorem m5_{nm}_of_residuals {args4} {hyp_r} :\n    {goal} := by\n"
      + ("  unfold m5T\n" if j == 1 else "") + "  unfold m5r0 at h0\n  unfold m5r1 at h1\n  unfold m5r2 at h2\n  unfold m5r3 at h3\n" + f"  linear_combination {lc}\n")
hyp_J = "(hT : m5T a4 = 0) (h1 : 362 * a4 * a1 = 3 * a4^5 + 13078) (h2 : 181 * a4^2 * a2 = 15 * a4^5 + 32448) (h3 : 2172 * a4^3 * a3 = 861 * a4^5 + 492128)"
hn = ["hT", "h1", "h2", "h3"]
for j in range(1, 5):
    lc = " + ".join(f"({lean_poly(CS[(j, i)], a5)}) * {hn[i - 1]}" for i in range(1, 5) if CS[(j, i)] != 0)
    w(f"theorem m5_residual{j - 1}_of_solution {args4} {hyp_J} :\n    m5r{j - 1} {use4} = 0 := by\n"
      f"  unfold m5r{j - 1}\n  unfold m5T at hT\n  linear_combination {lc}\n")
w(f"""/-- The four residuals cut out exactly `T₅(a₄) = 0` plus the back-substitution relations (ideal equality). -/
theorem m5_residual_iff {args4} :
    (m5r0 {use4} = 0 ∧ m5r1 {use4} = 0 ∧ m5r2 {use4} = 0 ∧ m5r3 {use4} = 0) ↔
    (m5T a4 = 0 ∧ 362 * a4 * a1 = 3 * a4^5 + 13078 ∧ 181 * a4^2 * a2 = 15 * a4^5 + 32448 ∧
      2172 * a4^3 * a3 = 861 * a4^5 + 492128) := by
  constructor
  · rintro ⟨h0, h1, h2, h3⟩
    exact ⟨m5_T_of_residuals {use4} h0 h1 h2 h3, m5_rel1_of_residuals {use4} h0 h1 h2 h3,
      m5_rel2_of_residuals {use4} h0 h1 h2 h3, m5_rel3_of_residuals {use4} h0 h1 h2 h3⟩
  · rintro ⟨hT, h1, h2, h3⟩
    exact ⟨m5_residual0_of_solution {use4} hT h1 h2 h3, m5_residual1_of_solution {use4} hT h1 h2 h3,
      m5_residual2_of_solution {use4} hT h1 h2 h3, m5_residual3_of_solution {use4} hT h1 h2 h3⟩
""")
# chart iff
solve_b = []
for k in range(1, n5 + 1):
    coef = sp.Rational(1, 1 + 2 * k)
    solve_b.append(f"    have hb{k} : b{k} = {lean_poly(B5[k], a5)} := by linear_combination {lean_coef(coef)} * e{k}\n    subst b{k}")
res_from_e = ", ".join(f"by unfold m5r{k}; linear_combination 3003 * e{8 + k}" for k in range(4))
ev = ", ".join(f"e{N}" for N in range(1, n5 + 5 + 1))
w(f"""/-- **`m = 5` classification.**  The chart system holds iff `T₅(a₄) = 0`, `a₁, a₂, a₃` satisfy the three
back-substitution relations, and `b₁, …, b₇` are the polynomials `m5B1, …, m5B7` in `a₁, …, a₄`. -/
theorem m5_chart_iff (a1 a2 a3 a4 {bargs} : L) :
    m5Chart a1 a2 a3 a4 {bargs} ↔
    (m5T a4 = 0 ∧ 362 * a4 * a1 = 3 * a4^5 + 13078 ∧ 181 * a4^2 * a2 = 15 * a4^5 + 32448 ∧
      2172 * a4^3 * a3 = 861 * a4^5 + 492128 ∧ {' ∧ '.join(f'b{k} = m5B{k} {use4}' for k in range(1, n5 + 1))}) := by
  constructor
  · rintro ⟨{ev}⟩
{chr(10).join(solve_b)}
    have hr := (m5_residual_iff {use4}).mp ⟨{res_from_e}⟩
    exact ⟨hr.1, hr.2.1, hr.2.2.1, hr.2.2.2, {', '.join(f'by unfold m5B{k}; ring' for k in range(1, n5 + 1))}⟩
  · rintro ⟨hT, h1, h2, h3, {', '.join(f'hb{k}' for k in range(1, n5 + 1))}⟩
    subst {' '.join(f'b{k}' for k in range(1, n5 + 1))}
    obtain ⟨r0, r1, r2, r3⟩ := (m5_residual_iff {use4}).mpr ⟨hT, h1, h2, h3⟩
    unfold m5Chart m5B1 m5B2 m5B3 m5B4 m5B5 m5B6 m5B7
    unfold m5r0 at r0
    unfold m5r1 at r1
    unfold m5r2 at r2
    unfold m5r3 at r3
    refine ⟨{', '.join(['by ring'] * n5)}, {', '.join(f'by linear_combination (1/3003 : L) * r{k}' for k in range(4))}, by ring⟩
""")
w("""theorem m5_T_ne_zero_at_zero : m5T (0 : L) ≠ 0 := by
  unfold m5T; norm_num

theorem m5_a4_ne_zero (a4 : L) (h : m5T a4 = 0) : a4 ≠ 0 := by
  rintro rfl; exact m5_T_ne_zero_at_zero h
""")
x = sp.Symbol("x")
T5x = sp.Poly(9 * x**10 + 37200 * x**5 + 95051008, x, domain="QQ")
g, u, v = None, None, None
s_, t_, g_ = sp.gcdex(T5x.as_expr(), sp.diff(T5x.as_expr(), x), x)
assert sp.simplify(g_ - 1) == 0, g_
assert sp.expand(s_ * T5x.as_expr() + t_ * sp.diff(T5x.as_expr(), x) - 1) == 0
w(f"""/-- `T₅` and `T₅' = 90 x⁹ + 186000 x⁴` have no common root (Bezout identity `u T₅ + v T₅' = 1`), so `T₅` is
squarefree: over an algebraically closed field it has `10` distinct roots. -/
theorem m5_T_squarefree (x : L) (h : m5T x = 0) : 90 * x^9 + 186000 * x^4 ≠ 0 := by
  intro h'
  unfold m5T at h
  have : (1 : L) = 0 := by
    linear_combination ({lean_poly(s_, [x])}) * h + ({lean_poly(t_, [x])}) * h'
  exact one_ne_zero this
""")
w("""/-- The explicit solution: `a₁, a₂, a₃` as rational functions of the root `a₄` of `T₅`. -/
theorem m5_solution_formulas (a1 a2 a3 a4 : L) (hT : m5T a4 = 0) (h1 : 362 * a4 * a1 = 3 * a4^5 + 13078)
    (h2 : 181 * a4^2 * a2 = 15 * a4^5 + 32448) (h3 : 2172 * a4^3 * a3 = 861 * a4^5 + 492128) :
    a1 = (3 * a4^5 + 13078) / (362 * a4) ∧ a2 = 3 * (5 * a4^5 + 10816) / (181 * a4^2) ∧
      a3 = 7 * (123 * a4^5 + 70304) / (2172 * a4^3) := by
  have ha : a4 ≠ 0 := m5_a4_ne_zero a4 hT
  refine ⟨?_, ?_, ?_⟩
  · rw [eq_div_iff (mul_ne_zero (by norm_num) ha)]; linear_combination h1
  · rw [eq_div_iff (mul_ne_zero (by norm_num) (pow_ne_zero 2 ha))]; linear_combination h2
  · rw [eq_div_iff (mul_ne_zero (by norm_num) (pow_ne_zero 3 ha))]; linear_combination h3
""")

# ---------------------------------------------------------------- m = 3
a3s, b3s, A3, B3, R3, E3, n3 = chart_data(3)
p1, p2 = a3s
s0 = sp.expand(sp.Rational(21, 2) * R3[5]); s1 = sp.expand(21 * R3[6])
assert sp.expand(s0 - (-4 * p1**2 + 7 * p1 * p2**2 - 30 * p2)) == 0 and sp.expand(s1 - (-4 * p1 * p2 + 7 * p2**3 - 48)) == 0
T3 = 3 * p2**3 - 32
J3 = [T3, 8 * p1 - 5 * p2**2]
CJ3 = read_lift("m3_lift_S_to_J.txt", a3s)
CS3 = read_lift("m3_lift_J_to_S.txt", a3s)
S3 = [s0, s1]
for j in range(1, 3):
    assert sp.expand(sum(S3[i - 1] * CJ3[(j, i)] for i in range(1, 3)) - J3[j - 1]) == 0
    assert sp.expand(sum(J3[i - 1] * CS3[(j, i)] for i in range(1, 3)) - S3[j - 1]) == 0
w("/-! ## `m = 3` -/\n")
w("/-- The `m = 3` eliminant `T₃(x) = 3 x³ - 32`. -/\ndef m3T (x : L) : L := 3 * x^3 - 32\n")
w(f"/-- `(21/2) · E₅` after eliminating `β`. -/\ndef m3s0 (a1 a2 : L) : L := {lean_poly(s0, a3s)}\n")
w(f"/-- `21 · E₆` after eliminating `β`. -/\ndef m3s1 (a1 a2 : L) : L := {lean_poly(s1, a3s)}\n")
for k in range(1, n3 + 1):
    w(f"def m3B{k} (a1 a2 : L) : L := {lean_poly(B3[k], a3s)}\n")
b3args = " ".join(str(v) for v in b3s)
chart3 = " ∧\n    ".join(f"{lean_poly(E3[N], list(a3s) + list(b3s))} = 0" for N in range(1, n3 + 3 + 1))
w(f"/-- The `m = 3` chart system: `E_N = 0` for `N = 1, …, 7`. -/\ndef m3Chart (a1 a2 {b3args} : L) : Prop :=\n    {chart3}\n")
lcT = " + ".join(f"({lean_poly(CJ3[(1, i)], a3s)}) * h{i - 1}" for i in range(1, 3) if CJ3[(1, i)] != 0)
lcR = " + ".join(f"({lean_poly(CJ3[(2, i)], a3s)}) * h{i - 1}" for i in range(1, 3) if CJ3[(2, i)] != 0)
lc0 = " + ".join(f"({lean_poly(CS3[(1, i)], a3s)}) * {['hT', 'h1'][i - 1]}" for i in range(1, 3) if CS3[(1, i)] != 0)
lc1 = " + ".join(f"({lean_poly(CS3[(2, i)], a3s)}) * {['hT', 'h1'][i - 1]}" for i in range(1, 3) if CS3[(2, i)] != 0)
w(f"""theorem m3_residual_iff (a1 a2 : L) :
    (m3s0 a1 a2 = 0 ∧ m3s1 a1 a2 = 0) ↔ (m3T a2 = 0 ∧ 8 * a1 = 5 * a2^2) := by
  unfold m3s0 m3s1 m3T
  constructor
  · rintro ⟨h0, h1⟩
    exact ⟨by linear_combination {lcT}, by linear_combination {lcR}⟩
  · rintro ⟨hT, h1⟩
    exact ⟨by linear_combination {lc0}, by linear_combination {lc1}⟩
""")
solve3 = []
for k in range(1, n3 + 1):
    solve3.append(f"    have hb{k} : b{k} = {lean_poly(B3[k], a3s)} := by linear_combination {lean_coef(sp.Rational(1, 1 + 2 * k))} * e{k}\n    subst b{k}")
ev3 = ", ".join(f"e{N}" for N in range(1, n3 + 3 + 1))
w(f"""/-- **`m = 3` classification.**  The chart system holds iff `T₃(a₂) = 0`, `8 a₁ = 5 a₂²` and `b₁, …, b₄` are
the polynomials `m3B1, …, m3B4` in `a₁, a₂`. -/
theorem m3_chart_iff (a1 a2 {b3args} : L) :
    m3Chart a1 a2 {b3args} ↔
    (m3T a2 = 0 ∧ 8 * a1 = 5 * a2^2 ∧ {' ∧ '.join(f'b{k} = m3B{k} a1 a2' for k in range(1, n3 + 1))}) := by
  constructor
  · rintro ⟨{ev3}⟩
{chr(10).join(solve3)}
    have hr := (m3_residual_iff a1 a2).mp ⟨by unfold m3s0; linear_combination (21/2 : L) * e5,
      by unfold m3s1; linear_combination 21 * e6⟩
    exact ⟨hr.1, hr.2, {', '.join(f'by unfold m3B{k}; ring' for k in range(1, n3 + 1))}⟩
  · rintro ⟨hT, h1, {', '.join(f'hb{k}' for k in range(1, n3 + 1))}⟩
    subst {' '.join(f'b{k}' for k in range(1, n3 + 1))}
    obtain ⟨r0, r1⟩ := (m3_residual_iff a1 a2).mpr ⟨hT, h1⟩
    unfold m3Chart m3B1 m3B2 m3B3 m3B4
    unfold m3s0 at r0
    unfold m3s1 at r1
    refine ⟨{', '.join(['by ring'] * n3)}, by linear_combination (2/21 : L) * r0, by linear_combination (1/21 : L) * r1, by ring⟩

theorem m3_a2_ne_zero (a2 : L) (h : m3T a2 = 0) : a2 ≠ 0 := by
  rintro rfl; unfold m3T at h; norm_num at h

/-- `T₃ = 3x³ - 32` and `T₃' = 9x²` have no common root: `(-1/32) T₃ + (x/96) T₃' = 1`. -/
theorem m3_T_squarefree (x : L) (h : m3T x = 0) : 9 * x^2 ≠ 0 := by
  intro h'
  unfold m3T at h
  have : (1 : L) = 0 := by linear_combination (-1/32 : L) * h + (x/96) * h'
  exact one_ne_zero this
""")
w("end BranchAb.TopLayerSmall\n")
open(out, "w").write("\n".join(L))
print("wrote", out, sum(len(s) for s in L), "chars")
