"""split_b26.py B26.lean OUTDIR -- split the generated single file into modules so that no module needs more than
about 3.8 GB to build (the single-module build of all eight certificate proofs was killed at 5.5 GB):
  OUTDIR/Jacobian/B26/Defs.lean           the definitions (m = 5 and m = 3)
  OUTDIR/Jacobian/B26/<Name>.lean          one certificate theorem each (eight m = 5 ideal-equality steps)
  OUTDIR/Jacobian/B26.lean                 the umbrella: the module docstring, the iff theorems and the rest
The generator separates declarations by blank lines and never puts a blank line inside one."""
import os, re, sys

src, outdir = sys.argv[1], sys.argv[2]
text = open(src).read()
head_end = text.index("namespace BranchAb.TopLayerSmall")
header = text[:head_end]
body = text[head_end + len("namespace BranchAb.TopLayerSmall"):text.rindex("end BranchAb.TopLayerSmall")]
chunks = [c.strip("\n") for c in re.split(r"\n\s*\n", body) if c.strip()]


def kind(c):
    m = re.search(r"^(def|theorem) (\S+)", c, re.M)
    if m:
        return m.group(1), m.group(2)
    return ("variable", "") if c.startswith("variable") else ("header", c[:40])


cert_names = {"m5_T_of_residuals": "M5T", "m5_rel1_of_residuals": "M5Rel1", "m5_rel2_of_residuals": "M5Rel2",
              "m5_rel3_of_residuals": "M5Rel3", "m5_residual0_of_solution": "M5Res0", "m5_residual1_of_solution": "M5Res1",
              "m5_residual2_of_solution": "M5Res2", "m5_residual3_of_solution": "M5Res3"}
defs, certs, main = [], {}, []
for c in chunks:
    k, name = kind(c)
    if k == "variable":
        continue
    if k == "def" or k == "header":
        defs.append(c)
    elif name in cert_names:
        certs[cert_names[name]] = c
    else:
        main.append(c)
assert len(certs) == 8, sorted(certs)
opts = "set_option maxHeartbeats 0\nset_option linter.unusedVariables false\n"
var = "variable {L : Type*} [Field L] [CharZero L]\n"
os.makedirs(os.path.join(outdir, "Jacobian", "B26"), exist_ok=True)
open(os.path.join(outdir, "Jacobian", "B26", "Defs.lean"), "w").write(
    "import Mathlib\n\n/-! Definitions for `Jacobian.B26` (generated by `gen_b26_lean.py`, split by `split_b26.py`). -/\n\n"
    + opts + "\nnamespace BranchAb.TopLayerSmall\n\n" + var + "\n" + "\n\n".join(defs) + "\n\nend BranchAb.TopLayerSmall\n")
for nm, c in certs.items():
    open(os.path.join(outdir, "Jacobian", "B26", nm + ".lean"), "w").write(
        "import Jacobian.B26.Defs\n\n/-! One certificate step of `Jacobian.B26` (generated). -/\n\n" + opts
        + "\nnamespace BranchAb.TopLayerSmall\n\n" + var + "\n" + c + "\n\nend BranchAb.TopLayerSmall\n")
imports = "import Jacobian.B26.Defs\n" + "".join(f"import Jacobian.B26.{nm}\n" for nm in sorted(certs))
assert header.startswith("import Mathlib\n")
open(os.path.join(outdir, "Jacobian", "B26.lean"), "w").write(
    imports + header[len("import Mathlib\n"):] + "namespace BranchAb.TopLayerSmall\n\n" + var + "\n"
    + "\n\n".join(main) + "\n\nend BranchAb.TopLayerSmall\n")
print("defs:", [kind(d)[1] for d in defs])
print("certificate modules:", sorted(certs))
print("umbrella:", [kind(m)[1] for m in main])
