import Jacobian.ChartProof.Reflect

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

/-- value of `a_1_1` (layer weight -3), minimal integer scale 128947425804288 -/
noncomputable def ev_a_1_1 : Expr :=
  (.add (.add (.add (.add (.mul (.num (128947425804288)) (.var 27)) (.mul (.num (-4387589182423096)) (.var 1))) (.add (.mul (.mul (.num (2635447434997286)) (.var 0)) (.var 1)) (.mul (.mul (.num (-2089271850927170)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (748677479426578)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-280948230075006)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (30327779100755059)) (.var 2)) (.mul (.mul (.num (-18216718669040017)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (14441392827652161)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-5175003377608043)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (1941959572196840)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_2_3` (layer weight -3), minimal integer scale 9210530414592 -/
noncomputable def ev_a_2_3 : Expr :=
  (.add (.add (.add (.add (.mul (.num (9210530414592)) (.var 28)) (.mul (.num (-671612269037424)) (.var 1))) (.add (.mul (.mul (.num (403405495326912)) (.var 0)) (.var 1)) (.mul (.mul (.num (-319809056649888)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (114599131018944)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-43005443949936)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (4379826548552164)) (.var 2)) (.mul (.mul (.num (-2630827131811949)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (2085593451563615)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-747364384925047)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (280456556982849)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_3_5` (layer weight -3), minimal integer scale 255848067072 -/
noncomputable def ev_a_3_5 : Expr :=
  (.add (.add (.add (.add (.mul (.num (255848067072)) (.var 29)) (.mul (.num (-24414640747692)) (.var 1))) (.add (.mul (.mul (.num (14662435533330)) (.var 0)) (.var 1)) (.mul (.mul (.num (-11625475841382)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (4165223530182)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-1563214646214)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (150263035177871)) (.var 2)) (.mul (.mul (.num (-90262185741868)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (71557086380122)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-25641380874956)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (9623081227599)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_4_7` (layer weight -3), minimal integer scale 895468234752 -/
noncomputable def ev_a_4_7 : Expr :=
  (.add (.add (.add (.add (.mul (.num (895468234752)) (.var 30)) (.mul (.num (-57794469235776)) (.var 1))) (.add (.mul (.mul (.num (34667894519232)) (.var 0)) (.var 1)) (.mul (.mul (.num (-27496284154560)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (9848220542784)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-3694287088128)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (314408034490270)) (.var 2)) (.mul (.mul (.num (-188769775612565)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (149734534157495)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-53619326597095)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (20135494325415)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_5_9` (layer weight -3), minimal integer scale 74622352896 -/
noncomputable def ev_a_5_9 : Expr :=
  (.add (.add (.add (.add (.mul (.num (74622352896)) (.var 31)) (.mul (.num (-2631012719400)) (.var 1))) (.add (.mul (.mul (.num (1579343648610)) (.var 0)) (.var 1)) (.mul (.mul (.num (-1249304302350)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (449124515190)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-167763009570)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (13295225625549)) (.var 2)) (.mul (.mul (.num (-7955547669643)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (6317681256915)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-2259756400041)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (847822457972)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_6_11` (layer weight -3), minimal integer scale 1807094016 -/
noncomputable def ev_a_6_11 : Expr :=
  (.add (.add (.add (.add (.mul (.num (1807094016)) (.var 32)) (.mul (.num (-18654347088)) (.var 1))) (.add (.mul (.mul (.num (11430716544)) (.var 0)) (.var 1)) (.mul (.mul (.num (-8963386848)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (3263944320)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-1217895120)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (66686356380)) (.var 2)) (.mul (.mul (.num (-39912897283)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (31475486805)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-11375202657)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (4212035891)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_7_13` (layer weight -3), minimal integer scale 381888 -/
noncomputable def ev_a_7_13 : Expr :=
  (.add (.add (.add (.add (.mul (.num (381888)) (.var 33)) (.mul (.num (-904696)) (.var 1))) (.add (.mul (.mul (.num (557518)) (.var 0)) (.var 1)) (.mul (.mul (.num (-444756)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (158054)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-60632)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (2299599)) (.var 2)) (.mul (.mul (.num (-1409112)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (1104954)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-402360)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (150135)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `a_8_15` (layer weight -3), minimal integer scale 14688 -/
noncomputable def ev_a_8_15 : Expr :=
  (.add (.add (.add (.mul (.num (14688)) (.var 34)) (.mul (.num (-34796)) (.var 2))) (.add (.mul (.mul (.num (21443)) (.var 0)) (.var 2)) (.mul (.mul (.num (-17106)) (.pow (.var 0) 2)) (.var 2)))) (.add (.mul (.mul (.num (6079)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (-2332)) (.pow (.var 0) 4)) (.var 2))))

/-- value of `b_2_2` (layer weight -3), minimal integer scale 257894851608576 -/
noncomputable def ev_b_2_2 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-4387589182423096)) (.var 1)) (.mul (.mul (.num (2635447434997286)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-2089271850927170)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (748677479426578)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-280948230075006)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (30327779100755059)) (.var 2))) (.add (.mul (.mul (.num (-18216718669040017)) (.var 0)) (.var 2)) (.mul (.mul (.num (14441392827652161)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-5175003377608043)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (1941959572196840)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (257894851608576)) (.var 35))))

/-- value of `b_3_4` (layer weight -3), minimal integer scale 9210530414592 -/
noncomputable def ev_b_3_4 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-671612269037424)) (.var 1)) (.mul (.mul (.num (403405495326912)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-319809056649888)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (114599131018944)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-43005443949936)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (4379826548552164)) (.var 2))) (.add (.mul (.mul (.num (-2630827131811949)) (.var 0)) (.var 2)) (.mul (.mul (.num (2085593451563615)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-747364384925047)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (280456556982849)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (9210530414592)) (.var 36))))

/-- value of `b_4_6` (layer weight -3), minimal integer scale 1535088402432 -/
noncomputable def ev_b_4_6 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-170902485233844)) (.var 1)) (.mul (.mul (.num (102637048733310)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-81378330889674)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (29156564711274)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-10942502523498)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (1051841246245097)) (.var 2))) (.add (.mul (.mul (.num (-631835300193076)) (.var 0)) (.var 2)) (.mul (.mul (.num (500899604660854)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-179489666124692)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (67361568593193)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (1535088402432)) (.var 37))))

/-- value of `b_5_8` (layer weight -3), minimal integer scale 447734117376 -/
noncomputable def ev_b_5_8 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-54188325900540)) (.var 1)) (.mul (.mul (.num (32506434562836)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-25786940196888)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (9233552094156)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-3465235855068)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (318468454227434)) (.var 2))) (.add (.mul (.mul (.num (-191273165414065)) (.var 0)) (.var 2)) (.mul (.mul (.num (151690719994429)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-54330604979399)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (20402020143393)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (447734117376)) (.var 38))))

/-- value of `b_6_10` (layer weight -3), minimal integer scale 149244705792 -/
noncomputable def ev_b_6_10 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-13266430438248)) (.var 1)) (.mul (.mul (.num (7920335128446)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-6280842724650)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (2251824575130)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-841192977222)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (72312780920975)) (.var 2))) (.add (.mul (.mul (.num (-43238409316585)) (.var 0)) (.var 2)) (.mul (.mul (.num (34394063124085)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-12274039327235)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (4618455544920)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (149244705792)) (.var 39))))

/-- value of `b_7_12` (layer weight -3), minimal integer scale 211429999872 -/
noncomputable def ev_b_7_12 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-10771984737540)) (.var 1)) (.mul (.mul (.num (6545399239704)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-5091202360764)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (1885747797648)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-686088108888)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (56231907852372)) (.var 2))) (.add (.mul (.mul (.num (-32891233280857)) (.var 0)) (.var 2)) (.mul (.mul (.num (26269566643215)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-9364407675987)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (3484072899209)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (211429999872)) (.var 40))))

/-- value of `b_8_14` (layer weight -3), minimal integer scale 458098333056 -/
noncomputable def ev_b_8_14 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-8285954405352)) (.var 1)) (.mul (.mul (.num (6220161429846)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-4583991035052)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (1835661151038)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-668115976944)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (43612666547709)) (.var 2))) (.add (.mul (.mul (.num (-26461742241284)) (.var 0)) (.var 2)) (.mul (.mul (.num (20016599606976)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-7877244108384)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (2667654398479)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (458098333056)) (.var 41))))

/-- value of `b_9_16` (layer weight -3), minimal integer scale 57578976 -/
noncomputable def ev_b_9_16 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-289161704)) (.var 1)) (.mul (.mul (.num (269924096)) (.var 0)) (.var 1))) (.add (.mul (.mul (.num (-223025244)) (.pow (.var 0) 2)) (.var 1)) (.mul (.mul (.num (59218276)) (.pow (.var 0) 3)) (.var 1)))) (.add (.add (.mul (.mul (.num (-30361864)) (.pow (.var 0) 4)) (.var 1)) (.mul (.num (965189106)) (.var 2))) (.add (.mul (.mul (.num (-1078418502)) (.var 0)) (.var 2)) (.mul (.mul (.num (697868745)) (.pow (.var 0) 2)) (.var 2))))) (.add (.add (.mul (.mul (.num (-335384196)) (.pow (.var 0) 3)) (.var 2)) (.mul (.mul (.num (111427575)) (.pow (.var 0) 4)) (.var 2))) (.mul (.num (57578976)) (.var 42))))

/-- value of `b_10_18` (layer weight -3), minimal integer scale 1107288 -/
noncomputable def ev_b_10_18 : Expr :=
  (.add (.add (.add (.add (.mul (.num (1107288)) (.var 43)) (.mul (.num (-3988062)) (.var 1))) (.add (.mul (.mul (.num (809172)) (.var 0)) (.var 1)) (.mul (.mul (.num (-1011465)) (.pow (.var 0) 2)) (.var 1)))) (.add (.add (.mul (.mul (.num (-173394)) (.pow (.var 0) 3)) (.var 1)) (.mul (.mul (.num (-28899)) (.pow (.var 0) 4)) (.var 1))) (.add (.mul (.num (267491)) (.var 2)) (.mul (.mul (.num (-2940959)) (.var 0)) (.var 2))))) (.add (.add (.mul (.mul (.num (2366196)) (.pow (.var 0) 2)) (.var 2)) (.mul (.mul (.num (-372064)) (.pow (.var 0) 3)) (.var 2))) (.mul (.mul (.num (336406)) (.pow (.var 0) 4)) (.var 2))))

end BranchC.Descent2R
