import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.Vals_L3
import Jacobian.BranchC.Descent2R.Vals_L4

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec2c_19_37_1 : Expr :=
  (.add (.add (.add (.add (.add (.mul (.mul (.num (600373982527488)) (.var 15)) (.var 73)) (.mul (.mul (.num (100062330421248)) (.var 34)) (.var 4))) (.add (.mul (.mul (.num (-400249321684992)) (.var 51)) (.var 2)) (.mul (.mul (.num (711145598312448)) (.var 2)) (.var 4)))) (.add (.add (.mul (.mul (.mul (.num (-438242759645184)) (.var 0)) (.var 2)) (.var 4)) (.mul (.mul (.mul (.num (349605029449728)) (.pow (.var 0) 2)) (.var 2)) (.var 4))) (.add (.mul (.mul (.mul (.num (-124239972759552)) (.pow (.var 0) 3)) (.var 2)) (.var 4)) (.mul (.mul (.mul (.num (47660407382016)) (.pow (.var 0) 4)) (.var 2)) (.var 4))))) (.add (.add (.add (.mul (.num (-68872580290351584)) (.pow (.var 2) 3)) (.mul (.mul (.num (41368970372624752)) (.var 0)) (.pow (.var 2) 3))) (.add (.mul (.mul (.num (-32795501555150352)) (.pow (.var 0) 2)) (.pow (.var 2) 3)) (.mul (.mul (.num (11752093815390288)) (.pow (.var 0) 3)) (.pow (.var 2) 3)))) (.add (.add (.mul (.mul (.num (-4410061484576720)) (.pow (.var 0) 4)) (.pow (.var 2) 3)) (.mul (.num (-4206476163433070592)) (.var 73))) (.add (.mul (.mul (.num (-2775890911419924480)) (.var 0)) (.var 73)) (.mul (.mul (.num (770646224292691968)) (.pow (.var 0) 2)) (.var 73)))))) (.add (.mul (.mul (.num (-55587567558721536)) (.pow (.var 0) 3)) (.var 73)) (.mul (.mul (.num (-365446760261566464)) (.pow (.var 0) 4)) (.var 73))))

theorem s_ec2c_19_37_1 (ctx : Context α) (h_et_a_8_14 : et_a_8_14.denote ctx = 0) (h_ev_a_8_15 : ev_a_8_15.denote ctx = 0) (h_ev_a_8_16 : ev_a_8_16.denote ctx = 0) :
    ec2c_19_37_1.denote ctx = 0 :=
  lc_zero ctx ec2c_19_37_1 [((.mul (.num (4414514577408)) (.var 73)), et_a_8_14), ((.mul (.num (6812522496)) (.var 4)), ev_a_8_15), ((.mul (.num (-16)) (.var 2)), ev_a_8_16)] (by decide +kernel) ⟨h_et_a_8_14, h_ev_a_8_15, h_ev_a_8_16, trivial⟩

end BranchC.Descent2R
