import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def ec2c_1_1_1 : Expr :=
  (.add (.add (.mul (.mul (.num (-2)) (.var 74)) (.var 16)) (.mul (.num (2)) (.var 74))) (.add (.mul (.mul (.num (2)) (.var 8)) (.var 62)) (.mul (.num (-2)) (.var 62))))

theorem s_ec2c_1_1_1 (ctx : Context α) (h_et_b_2_1 : et_b_2_1.denote ctx = 0) (h_et_a_1_0 : et_a_1_0.denote ctx = 0) :
    ec2c_1_1_1.denote ctx = 0 :=
  lc_zero ctx ec2c_1_1_1 [((.mul (.num (-2)) (.var 74)), et_b_2_1), ((.mul (.num (2)) (.var 62)), et_a_1_0)] (by decide +kernel) ⟨h_et_b_2_1, h_et_a_1_0, trivial⟩

end BranchC.Descent2R
