import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L2c.C_2_3_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er2c_2_3 : Expr :=
  (.add (.add (.add (.add (.mul (.num (-2424)) (.var 74)) (.mul (.mul (.num (-879)) (.var 0)) (.var 74))) (.add (.mul (.mul (.num (389)) (.pow (.var 0) 2)) (.var 74)) (.mul (.mul (.num (51)) (.pow (.var 0) 3)) (.var 74)))) (.add (.add (.mul (.mul (.num (-49)) (.pow (.var 0) 4)) (.var 74)) (.mul (.num (-320)) (.var 75))) (.add (.mul (.num (2424)) (.var 62)) (.mul (.mul (.num (879)) (.var 0)) (.var 62))))) (.add (.add (.mul (.mul (.num (-389)) (.pow (.var 0) 2)) (.var 62)) (.mul (.mul (.num (-51)) (.pow (.var 0) 3)) (.var 62))) (.add (.mul (.mul (.num (49)) (.pow (.var 0) 4)) (.var 62)) (.mul (.num (256)) (.var 63)))))

theorem s_er2c_2_3 (ctx : Context α) (h_eh2c_2_3 : eh2c_2_3.denote ctx = 0) (h_ec2c_2_3_1 : ec2c_2_3_1.denote ctx = 0) :
    (Expr.mul (.num 747790669631687890382156182981454069760) er2c_2_3).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 747790669631687890382156182981454069760) er2c_2_3) [((.num (47858602856428024984457995710813060464640)), eh2c_2_3), ((.num (-1)), ec2c_2_3_1)] (by decide +kernel) ⟨h_eh2c_2_3, h_ec2c_2_3_1, trivial⟩

end BranchC.Descent2R
