import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.Facts
import Jacobian.BranchC.Descent2R.L2c.C_19_37_1

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

noncomputable def er2c_19_37 : Expr :=
  (.add (.add (.add (.add (.mul (.mul (.num (-44446599894528)) (.var 2)) (.var 4)) (.mul (.mul (.mul (.num (27390172477824)) (.var 0)) (.var 2)) (.var 4))) (.add (.mul (.mul (.mul (.num (-21850314340608)) (.pow (.var 0) 2)) (.var 2)) (.var 4)) (.mul (.mul (.mul (.num (7764998297472)) (.pow (.var 0) 3)) (.var 2)) (.var 4)))) (.add (.add (.mul (.mul (.mul (.num (-2978775461376)) (.pow (.var 0) 4)) (.var 2)) (.var 4)) (.mul (.num (4304536268146974)) (.pow (.var 2) 3))) (.add (.mul (.mul (.num (-2585560648289047)) (.var 0)) (.pow (.var 2) 3)) (.mul (.mul (.num (2049718847196897)) (.pow (.var 0) 2)) (.pow (.var 2) 3))))) (.add (.add (.add (.mul (.mul (.num (-734505863461893)) (.pow (.var 0) 3)) (.pow (.var 2) 3)) (.mul (.mul (.num (275628842786045)) (.pow (.var 0) 4)) (.pow (.var 2) 3))) (.add (.mul (.num (262904760214566912)) (.var 73)) (.mul (.mul (.num (173493181963745280)) (.var 0)) (.var 73)))) (.add (.add (.mul (.mul (.num (-48165389018293248)) (.pow (.var 0) 2)) (.var 73)) (.mul (.mul (.num (3474222972420096)) (.pow (.var 0) 3)) (.var 73))) (.mul (.mul (.num (22840422516347904)) (.pow (.var 0) 4)) (.var 73)))))

theorem s_er2c_19_37 (ctx : Context α) (h_eh2c_19_37 : eh2c_19_37.denote ctx = 0) (h_ec2c_19_37_1 : ec2c_19_37_1.denote ctx = 0) :
    (Expr.mul (.num 16) er2c_19_37).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 16) er2c_19_37) [((.num (25015582605312)), eh2c_19_37), ((.num (-1)), ec2c_19_37_1)] (by decide +kernel) ⟨h_eh2c_19_37, h_ec2c_19_37_1, trivial⟩

end BranchC.Descent2R
