import Jacobian.ChartProof.Reflect
import Jacobian.BranchC.Descent2R.L2c.P_a_0_1_1
import Jacobian.BranchC.Descent2R.L2c.P_a_1_3_1
import Jacobian.BranchC.Descent2R.L2c.P_a_2_5_1
import Jacobian.BranchC.Descent2R.L2c.P_a_3_7_1
import Jacobian.BranchC.Descent2R.L2c.P_a_4_9_1
import Jacobian.BranchC.Descent2R.L2c.P_a_5_11_1
import Jacobian.BranchC.Descent2R.L2c.P_b_10_20_1
import Jacobian.BranchC.Descent2R.L2c.P_b_11_22_1
import Jacobian.BranchC.Descent2R.L2c.P_b_12_24_1
import Jacobian.BranchC.Descent2R.L2c.P_b_1_2_1
import Jacobian.BranchC.Descent2R.L2c.P_b_2_4_1
import Jacobian.BranchC.Descent2R.L2c.P_b_3_6_1
import Jacobian.BranchC.Descent2R.L2c.P_b_4_8_1
import Jacobian.BranchC.Descent2R.L2c.P_b_5_10_1
import Jacobian.BranchC.Descent2R.L2c.P_b_6_12_1
import Jacobian.BranchC.Descent2R.L2c.P_b_7_14_1
import Jacobian.BranchC.Descent2R.L2c.P_b_8_16_1
import Jacobian.BranchC.Descent2R.L2c.P_b_9_18_1
import Jacobian.BranchC.Descent2R.Vals_L2c

/-! Generated by certgen_c/gen_refl_c.py -- kernel-reflected certificates (conventions of
`Jacobian/ChartProof/Reflect.lean`) for the branch-(c) eliminations E₄ … E₋₂.  Every polynomial identity is checked
by the Lean kernel (`decide +kernel`, no `native_decide`) and was re-checked in Python by exact integer arithmetic. -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false

namespace BranchC.Descent2R
open Lean.Grind.CommRing BranchAb.ChartProof

variable {α : Type*} [CommRing α]

theorem s_ev_b_1_2 (ctx : Context α) (h_ep2c_b_1_2_1 : ep2c_b_1_2_1.denote ctx = 0) :
    (Expr.mul (.num 199640144756329964970226282116866204860243612429042302028462363323827468341696512) ev_b_1_2).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 199640144756329964970226282116866204860243612429042302028462363323827468341696512) ev_b_1_2) [((.num (1)), ep2c_b_1_2_1)] (by decide +kernel) ⟨h_ep2c_b_1_2_1, trivial⟩

theorem s_ev_b_2_4 (ctx : Context α) (h_ep2c_b_2_4_1 : ep2c_b_2_4_1.denote ctx = 0) :
    (Expr.mul (.num 570400413589514185629217948905332013886410321225835148652749609496649909547704320) ev_b_2_4).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 570400413589514185629217948905332013886410321225835148652749609496649909547704320) ev_b_2_4) [((.num (1)), ep2c_b_2_4_1)] (by decide +kernel) ⟨h_ep2c_b_2_4_1, trivial⟩

theorem s_ev_b_3_6 (ctx : Context α) (h_ep2c_b_3_6_1 : ep2c_b_3_6_1.denote ctx = 0) :
    (Expr.mul (.num 1235867562777280735529972222628219363420555695989309488747624153909408137353359360) ev_b_3_6).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 1235867562777280735529972222628219363420555695989309488747624153909408137353359360) ev_b_3_6) [((.num (1)), ep2c_b_3_6_1)] (by decide +kernel) ⟨h_ep2c_b_3_6_1, trivial⟩

theorem s_ev_b_4_8 (ctx : Context α) (h_ep2c_b_4_8_1 : ep2c_b_4_8_1.denote ctx = 0) :
    (Expr.mul (.num 18252813234864453940134974364970624444365130279226724756887987503892797105526538240) ev_b_4_8).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 18252813234864453940134974364970624444365130279226724756887987503892797105526538240) ev_b_4_8) [((.num (1)), ep2c_b_4_8_1)] (by decide +kernel) ⟨h_ep2c_b_4_8_1, trivial⟩

theorem s_ev_b_5_10 (ctx : Context α) (h_ep2c_b_5_10_1 : ep2c_b_5_10_1.denote ctx = 0) :
    (Expr.mul (.num 268423724042124322649043740661332712417134268812157717013058639763129369198919680) ev_b_5_10).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 268423724042124322649043740661332712417134268812157717013058639763129369198919680) ev_b_5_10) [((.num (1)), ep2c_b_5_10_1)] (by decide +kernel) ⟨h_ep2c_b_5_10_1, trivial⟩

theorem s_ev_b_6_12 (ctx : Context α) (h_ep2c_b_6_12_1 : ep2c_b_6_12_1.denote ctx = 0) :
    (Expr.mul (.num 751586427317948103417322473851731594767975952674041607636564191336762233756975104) ev_b_6_12).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 751586427317948103417322473851731594767975952674041607636564191336762233756975104) ev_b_6_12) [((.num (1)), ep2c_b_6_12_1)] (by decide +kernel) ⟨h_ep2c_b_6_12_1, trivial⟩

theorem s_ev_b_7_14 (ctx : Context α) (h_ep2c_b_7_14_1 : ep2c_b_7_14_1.denote ctx = 0) :
    (Expr.mul (.num 251244605703428365999504941259007418822437675608179623124222886818289089570188820480) ev_b_7_14).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 251244605703428365999504941259007418822437675608179623124222886818289089570188820480) ev_b_7_14) [((.num (1)), ep2c_b_7_14_1)] (by decide +kernel) ⟨h_ep2c_b_7_14_1, trivial⟩

theorem s_ev_b_8_16 (ctx : Context α) (h_ep2c_b_8_16_1 : ep2c_b_8_16_1.denote ctx = 0) :
    (Expr.mul (.num 19326508131032951230731149327615955294033667354475355624940222062945314582322216960) ev_b_8_16).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 19326508131032951230731149327615955294033667354475355624940222062945314582322216960) ev_b_8_16) [((.num (1)), ep2c_b_8_16_1)] (by decide +kernel) ⟨h_ep2c_b_8_16_1, trivial⟩

theorem s_ev_b_9_18 (ctx : Context α) (h_ep2c_b_9_18_1 : ep2c_b_9_18_1.denote ctx = 0) :
    (Expr.mul (.num 201812229531278834989102344066297709169123062932270282274532033836790711197254170050560) ev_b_9_18).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 201812229531278834989102344066297709169123062932270282274532033836790711197254170050560) ev_b_9_18) [((.num (1)), ep2c_b_9_18_1)] (by decide +kernel) ⟨h_ep2c_b_9_18_1, trivial⟩

theorem s_ev_b_10_20 (ctx : Context α) (h_ep2c_b_10_20_1 : ep2c_b_10_20_1.denote ctx = 0) :
    (Expr.mul (.num 82288883012758059827982694554188535903337448104007397285808034418196970664960) ev_b_10_20).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 82288883012758059827982694554188535903337448104007397285808034418196970664960) ev_b_10_20) [((.num (1)), ep2c_b_10_20_1)] (by decide +kernel) ⟨h_ep2c_b_10_20_1, trivial⟩

theorem s_ev_b_11_22 (ctx : Context α) (h_ep2c_b_11_22_1 : ep2c_b_11_22_1.denote ctx = 0) :
    (Expr.mul (.num 668194946418492874705920213841800980651121252398727714789257249975614239860189675520) ev_b_11_22).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 668194946418492874705920213841800980651121252398727714789257249975614239860189675520) ev_b_11_22) [((.num (1)), ep2c_b_11_22_1)] (by decide +kernel) ⟨h_ep2c_b_11_22_1, trivial⟩

theorem s_ev_b_12_24 (ctx : Context α) (h_ep2c_b_12_24_1 : ep2c_b_12_24_1.denote ctx = 0) :
    (Expr.mul (.num 510136469092954832889119814167585875955283297967683213527289307754109853304170263183360) ev_b_12_24).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 510136469092954832889119814167585875955283297967683213527289307754109853304170263183360) ev_b_12_24) [((.num (1)), ep2c_b_12_24_1)] (by decide +kernel) ⟨h_ep2c_b_12_24_1, trivial⟩

theorem s_ev_a_0_1 (ctx : Context α) (h_ep2c_a_0_1_1 : ep2c_a_0_1_1.denote ctx = 0) :
    (Expr.mul (.num 199640144756329964970226282116866204860243612429042302028462363323827468341696512) ev_a_0_1).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 199640144756329964970226282116866204860243612429042302028462363323827468341696512) ev_a_0_1) [((.num (1)), ep2c_a_0_1_1)] (by decide +kernel) ⟨h_ep2c_a_0_1_1, trivial⟩

theorem s_ev_a_1_3 (ctx : Context α) (h_ep2c_a_1_3_1 : ep2c_a_1_3_1.denote ctx = 0) :
    (Expr.mul (.num 570400413589514185629217948905332013886410321225835148652749609496649909547704320) ev_a_1_3).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 570400413589514185629217948905332013886410321225835148652749609496649909547704320) ev_a_1_3) [((.num (1)), ep2c_a_1_3_1)] (by decide +kernel) ⟨h_ep2c_a_1_3_1, trivial⟩

theorem s_ev_a_2_5 (ctx : Context α) (h_ep2c_a_2_5_1 : ep2c_a_2_5_1.denote ctx = 0) :
    (Expr.mul (.num 1140800827179028371258435897810664027772820642451670297305499218993299819095408640) ev_a_2_5).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 1140800827179028371258435897810664027772820642451670297305499218993299819095408640) ev_a_2_5) [((.num (1)), ep2c_a_2_5_1)] (by decide +kernel) ⟨h_ep2c_a_2_5_1, trivial⟩

theorem s_ev_a_3_7 (ctx : Context α) (h_ep2c_a_3_7_1 : ep2c_a_3_7_1.denote ctx = 0) :
    (Expr.mul (.num 36505626469728907880269948729941248888730260558453449513775975007785594211053076480) ev_a_3_7).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 36505626469728907880269948729941248888730260558453449513775975007785594211053076480) ev_a_3_7) [((.num (1)), ep2c_a_3_7_1)] (by decide +kernel) ⟨h_ep2c_a_3_7_1, trivial⟩

theorem s_ev_a_4_9 (ctx : Context α) (h_ep2c_a_4_9_1 : ep2c_a_4_9_1.denote ctx = 0) :
    (Expr.mul (.num 1163169470849205398145856209532441753807581831519350107056587438973560599861985280) ev_a_4_9).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 1163169470849205398145856209532441753807581831519350107056587438973560599861985280) ev_a_4_9) [((.num (1)), ep2c_a_4_9_1)] (by decide +kernel) ⟨h_ep2c_a_4_9_1, trivial⟩

theorem s_ev_a_5_11 (ctx : Context α) (h_ep2c_a_5_11_1 : ep2c_a_5_11_1.denote ctx = 0) :
    (Expr.mul (.num 390824942205333013777007686402900429279347495390501635971013379495116361553627054080) ev_a_5_11).denote ctx = 0 :=
  lc_zero ctx (Expr.mul (.num 390824942205333013777007686402900429279347495390501635971013379495116361553627054080) ev_a_5_11) [((.num (1)), ep2c_a_5_11_1)] (by decide +kernel) ⟨h_ep2c_a_5_11_1, trivial⟩

end BranchC.Descent2R
