import Mathlib

/-! Definitions for `Jacobian.B26` (generated by `gen_b26_lean.py`, split by `split_b26.py`). -/

set_option maxHeartbeats 0
set_option linter.unusedVariables false

namespace BranchAb.TopLayerSmall

variable {L : Type*} [Field L] [CharZero L]

/-! ## `m = 5` -/

/-- The `m = 5` eliminant `T₅(x) = 9 x¹⁰ + 37200 x⁵ + 95051008`. -/
def m5T (x : L) : L := 9 * x^10 + 37200 * x^5 + 95051008

/-- CAIC's residual `r0` (`= 3003 · E_8` after eliminating `β`; repository file `scripts/b26_m5_eliminant/m5_b2_6_eliminate_basis.sing`). -/
def m5r0 (a1 a2 a3 a4 : L) : L :=
  512 * a1^5 * a3 + (-896) * a1^4 * a2^2 + (-1792) * a1^4 * a4 + 2624 * a1^3 * a2 * a3 + 4032 * a1^3 + 2128 * a1^2 * a2^3 + (-3136) * a1^2 * a2 * a4 + (-4016) * a1^2 * a3^2 + (-6536) * a1 * a2^2 * a3 + 5208 * a1 * a2 + 13572 * a1 * a3 * a4 + (-539) * a2^4 + 4389 * a2^2 * a4 + 5256 * a2 * a3^2 + (-19812) * a3 + (-11011) * a4^2

/-- CAIC's residual `r1` (`= 3003 · E_9` after eliminating `β`; repository file `scripts/b26_m5_eliminant/m5_b2_6_eliminate_basis.sing`). -/
def m5r1 (a1 a2 a3 a4 : L) : L :=
  384 * a1^4 * a2 * a3 + (-672) * a1^3 * a2^3 + (-1344) * a1^3 * a2 * a4 + (-256) * a1^3 * a3^2 + 2752 * a1^2 * a2^2 * a3 + 3024 * a1^2 * a2 + 792 * a1^2 * a3 * a4 + 1008 * a1 * a2^4 + (-3346) * a1 * a2^2 * a4 + (-4912) * a1 * a2 * a3^2 + (-872) * a1 * a3 + 364 * a1 * a4^2 + (-2648) * a2^3 * a3 + 4550 * a2^2 + 12596 * a2 * a3 * a4 + 2112 * a3^3 + (-25844) * a4

/-- CAIC's residual `r2` (`= 3003 · E_10` after eliminating `β`; repository file `scripts/b26_m5_eliminant/m5_b2_6_eliminate_basis.sing`). -/
def m5r2 (a1 a2 a3 a4 : L) : L :=
  256 * a1^4 * a3^2 + (-448) * a1^3 * a2^2 * a3 + (-960) * a1^3 * a3 * a4 + 112 * a1^2 * a2^2 * a4 + 1536 * a1^2 * a2 * a3^2 + 1600 * a1^2 * a3 + 224 * a1^2 * a4^2 + 672 * a1 * a2^3 * a3 + 728 * a1 * a2^2 + (-2788) * a1 * a2 * a3 * a4 + (-2112) * a1 * a3^3 + 952 * a1 * a4 + (-77) * a2^3 * a4 + (-1560) * a2^2 * a3^2 + 1248 * a2 * a3 + 770 * a2 * a4^2 + 7392 * a3^2 * a4 + (-15288)

/-- CAIC's residual `r3` (`= 3003 · E_11` after eliminating `β`; repository file `scripts/b26_m5_eliminant/m5_b2_6_eliminate_basis.sing`). -/
def m5r3 (a1 a2 a3 a4 : L) : L :=
  128 * a1^4 * a3 * a4 + (-224) * a1^3 * a2^2 * a4 + 128 * a1^3 * a3 + (-448) * a1^3 * a4^2 + (-224) * a1^2 * a2^2 + 768 * a1^2 * a2 * a3 * a4 + 560 * a1^2 * a4 + 336 * a1 * a2^3 * a4 + 872 * a1 * a2 * a3 + (-1176) * a1 * a2 * a4^2 + (-1056) * a1 * a3^2 * a4 + 1008 * a1 + 154 * a2^3 + (-780) * a2^2 * a3 * a4 + 644 * a2 * a4 + (-1056) * a3^2 + 3432 * a3 * a4^2

/-- `b1` in terms of `a₁, …, a₄` (solved from `E_1`). -/
def m5B1 (a1 a2 a3 a4 : L) : L :=
  (2/3) * a1

/-- `b2` in terms of `a₁, …, a₄` (solved from `E_2`). -/
def m5B2 (a1 a2 a3 a4 : L) : L :=
  a2

/-- `b3` in terms of `a₁, …, a₄` (solved from `E_3`). -/
def m5B3 (a1 a2 a3 a4 : L) : L :=
  (8/7) * a3

/-- `b4` in terms of `a₁, …, a₄` (solved from `E_4`). -/
def m5B4 (a1 a2 a3 a4 : L) : L :=
  (-4/63) * a1 * a3 + (1/9) * a2^2 + (11/9) * a4

/-- `b5` in terms of `a₁, …, a₄` (solved from `E_5`). -/
def m5B5 (a1 a2 a3 a4 : L) : L :=
  (8/231) * a1^2 * a3 + (-2/33) * a1 * a2^2 + (-4/33) * a1 * a4 + (20/77) * a2 * a3 + (14/11)

/-- `b6` in terms of `a₁, …, a₄` (solved from `E_6`). -/
def m5B6 (a1 a2 a3 a4 : L) : L :=
  (-64/3003) * a1^3 * a3 + (16/429) * a1^2 * a2^2 + (32/429) * a1^2 * a4 + (-436/3003) * a1 * a2 * a3 + (-24/143) * a1 + (-1/39) * a2^3 + (10/39) * a2 * a4 + (16/91) * a3^2

/-- `b7` in terms of `a₁, …, a₄` (solved from `E_7`). -/
def m5B7 (a1 a2 a3 a4 : L) : L :=
  (128/9009) * a1^4 * a3 + (-32/1287) * a1^3 * a2^2 + (-64/1287) * a1^3 * a4 + (256/3003) * a1^2 * a2 * a3 + (16/143) * a1^2 + (16/429) * a1 * a2^3 + (-56/429) * a1 * a2 * a4 + (-32/273) * a1 * a3^2 + (-20/231) * a2^2 * a3 + (8/33) * a2 + (8/21) * a3 * a4

/-- The `m = 5` chart system: `E_N = 0` for `N = 1, …, 12`. -/
def m5Chart (a1 a2 a3 a4 b1 b2 b3 b4 b5 b6 b7 : L) : Prop :=
    (-2) * a1 + 3 * b1 = 0 ∧
    (-5) * a2 + 5 * b2 = 0 ∧
    2 * a1 * b2 + (-3) * a2 * b1 + (-8) * a3 + 7 * b3 = 0 ∧
    4 * a1 * b3 + (-1) * a2 * b2 + (-6) * a3 * b1 + (-11) * a4 + 9 * b4 = 0 ∧
    6 * a1 * b4 + a2 * b3 + (-4) * a3 * b2 + (-9) * a4 * b1 + 11 * b5 + (-14) = 0 ∧
    8 * a1 * b5 + 3 * a2 * b4 + (-2) * a3 * b3 + (-7) * a4 * b2 + (-12) * b1 + 13 * b6 = 0 ∧
    10 * a1 * b6 + 5 * a2 * b5 + (-5) * a4 * b3 + (-10) * b2 + 15 * b7 = 0 ∧
    12 * a1 * b7 + 7 * a2 * b6 + 2 * a3 * b5 + (-3) * a4 * b4 + (-8) * b3 = 0 ∧
    9 * a2 * b7 + 4 * a3 * b6 + (-1) * a4 * b5 + (-6) * b4 = 0 ∧
    6 * a3 * b7 + a4 * b6 + (-4) * b5 = 0 ∧
    3 * a4 * b7 + (-2) * b6 = 0 ∧
    0 = 0

/-! ## `m = 3` -/

/-- The `m = 3` eliminant `T₃(x) = 3 x³ - 32`. -/
def m3T (x : L) : L := 3 * x^3 - 32

/-- `(21/2) · E₅` after eliminating `β`. -/
def m3s0 (a1 a2 : L) : L := (-4) * a1^2 + 7 * a1 * a2^2 + (-30) * a2

/-- `21 · E₆` after eliminating `β`. -/
def m3s1 (a1 a2 : L) : L := (-4) * a1 * a2 + 7 * a2^3 + (-48)

def m3B1 (a1 a2 : L) : L := (2/3) * a1

def m3B2 (a1 a2 : L) : L := a2

def m3B3 (a1 a2 : L) : L := (8/7)

def m3B4 (a1 a2 : L) : L := (-4/63) * a1 + (1/9) * a2^2

/-- The `m = 3` chart system: `E_N = 0` for `N = 1, …, 7`. -/
def m3Chart (a1 a2 b1 b2 b3 b4 : L) : Prop :=
    (-2) * a1 + 3 * b1 = 0 ∧
    (-5) * a2 + 5 * b2 = 0 ∧
    2 * a1 * b2 + (-3) * a2 * b1 + 7 * b3 + (-8) = 0 ∧
    4 * a1 * b3 + (-1) * a2 * b2 + (-6) * b1 + 9 * b4 = 0 ∧
    6 * a1 * b4 + a2 * b3 + (-4) * b2 = 0 ∧
    3 * a2 * b4 + (-2) * b3 = 0 ∧
    0 = 0

end BranchAb.TopLayerSmall
