"""
chart_cas.py -- external (non-Lean) exact check of the chart system behind `ChartClassification`.

    python3 chart_cas.py write            # writes chart_system_Q.sing and chart_system_p.sing
    Singular -q chart_system_p.sing       # mod-p Groebner basis (seconds to minutes)  -> chart_gb_p.txt
    Singular -q chart_system_Q.sing       # exact Groebner basis over Q (slow)         -> chart_gb_Q.txt
    python3 chart_cas.py verify chart_gb_Q.txt

The system is the one in `ChartClassification` (Jacobian/BranchAbChart.lean), generated from the same
formula: unknowns a1..a7, b0..b9 (a0 = b10 = 1), equations
    E_n = sum_{i+k=n} (1 + 2k - 3i) a_i b_k   (n = 1..16),   a7^3 b0^2 - 1.

`verify` checks, exactly over Q (python-flint):
  (1) every generator E_n and a7^3 b0^2 - 1 reduces to 0 modulo the basis G    (so <E> ⊆ <G>);
  (2) G is a Groebner basis (all S-polynomials reduce to 0)                    (Buchberger's criterion);
  (3) the staircase of G has exactly 5 standard monomials                        (dim_Q Q[x]/<G> = 5);
  (4) every element of G vanishes at the K5 chart point (P_j(w), Q_k(w)) of chartpoint.json, exactly
      in Q[w]/(R)                                                                  (5 conjugate zeros).
(3) and (4) give V(<G>) = the five conjugates of the chart point (the conjugates are distinct because
w itself is a Q-linear combination of the coordinates, see (5) below).
(5) exhibits psi = a Q-linear form in the coordinates with psi(P(w), Q(w)) = w, so every solution in
any field L of characteristic 0 determines its root w = psi(a, b) in L.

Fast mod-p evidence (`chart_a1_0_p.sing`, `chart_a1_1_p.sing`): the solutions of the chart system are
exactly the torus images of the solutions with a1 = 1 (rescale by kappa = 1/a1) together with those
with a1 = 0 (the torus preserves a1 = 0).  Mod 32003 the a1 = 0 system is the unit ideal and the a1 = 1
system has vdim 5.  This is evidence, not proof: a count mod p does not bound the count over Q (solutions
with p in a denominator disappear mod p).

What `verify` does NOT check: <G> ⊆ <E>, i.e. that G really lies in the ideal of the chart equations.
That inclusion is the content of the Groebner computation itself (Singular's std over Q, which only
forms Q-linear combinations of polynomial multiples of the input).  An independent check of it
needs explicit cofactors (Singular `lift`), which are too large to be practical; see
CLASSIFICATION_STATUS.md.
"""
import json, os, sys, re, itertools
import flint

HERE = os.path.dirname(os.path.abspath(__file__))
NAMES = [f"b{k}" for k in range(0, 10)] + [f"a{i}" for i in range(1, 8)]

def coef(i, k): return 1 + 2 * k - 3 * i

def equations_str():
    A = {0: None}; A.update({i: f"a{i}" for i in range(1, 8)})
    B = {10: None}; B.update({k: f"b{k}" for k in range(0, 10)})
    eqs = []
    for n in range(1, 17):
        t = []
        for i in range(0, 8):
            k = n - i
            if 0 <= k <= 10 and coef(i, k):
                parts = [f"({coef(i, k)})"] + ([A[i]] if A[i] else []) + ([B[k]] if B[k] else [])
                t.append("*".join(parts))
        eqs.append("+".join(t))
    eqs.append("a7^3*b0^2-1")
    return eqs

def split_equations_str(a1val):
    """E_1..E_16 with a0 = b10 = 1 and a1 fixed to a1val (0 or 1), no torus equation."""
    A = {0: None, 1: None if a1val == 1 else "0"}; A.update({i: f"a{i}" for i in range(2, 8)})
    B = {10: None}; B.update({k: f"b{k}" for k in range(0, 10)})
    eqs = []
    for n in range(1, 17):
        t = []
        for i in range(0, 8):
            k = n - i
            if 0 <= k <= 10 and coef(i, k):
                if i == 1 and a1val == 0: continue
                parts = [f"({coef(i, k)})"] + ([A[i]] if A[i] else []) + ([B[k]] if B[k] else [])
                t.append("*".join(parts))
        eqs.append("+".join(t) if t else "0")
    return eqs

SPLIT_NAMES = [f"b{k}" for k in range(0, 10)] + [f"a{i}" for i in range(2, 8)]

def write():
    for a1val in (0, 1):
        for tag, ch in (("p", "32003"), ("Q", "0")):
            with open(os.path.join(HERE, f"chart_a1_{a1val}_{tag}.sing"), "w") as f:
                f.write(f"// generated by chart_cas.py -- chart system with a1 = {a1val} (no torus equation)\n")
                f.write(f"ring r = {ch}, ({','.join(SPLIT_NAMES)}), dp;\noption(redSB);\n")
                f.write("ideal I = " + ",\n  ".join(split_equations_str(a1val)) + ";\n")
                f.write('int t0 = timer; ideal G = std(I);\n')
                f.write(f'print("a1 = {a1val}: time " + string(timer - t0) + "s  dim " + string(dim(G)) + "  vdim " + string(vdim(G)) + "  #G " + string(size(G)));\n')
                f.write(f'link l = ":w chart_a1_{a1val}_gb_{tag}.txt"; open(l); int i; for (i = 1; i <= size(G); i++) {{ write(l, string(G[i])); }} close(l);\n')
                f.write("quit;\n")
    eqs = equations_str()
    for tag, ch, out in (("Q", "0", "chart_gb_Q.txt"), ("p", "32003", "chart_gb_p.txt")):
        with open(os.path.join(HERE, f"chart_system_{tag}.sing"), "w") as f:
            f.write(f"// generated by chart_cas.py -- the chart system of ChartClassification\n")
            f.write(f"ring r = {ch}, ({','.join(NAMES)}), dp;\noption(redSB);\n")
            f.write("ideal I = " + ",\n  ".join(eqs) + ";\n")
            f.write('int t0 = timer; ideal G = std(I);\n')
            f.write('print("time " + string(timer - t0) + "s  dim " + string(dim(G)) + "  vdim " + string(vdim(G)) + "  #G " + string(size(G)));\n')
            f.write(f'link l = ":w {out}"; open(l);\n')
            f.write('int i; for (i = 1; i <= size(G); i++) { write(l, string(G[i])); }\nclose(l);\nquit;\n')
    print("written chart_system_{Q,p}.sing, chart_a1_{0,1}_{p,Q}.sing")

def verify(path, names=None, eqs=None, point=None, expect_std=5):
    names = names or NAMES
    R = flint.fmpq_mpoly_ctx.get(names, "degrevlex")
    gens = R.gens(); V = dict(zip(names, gens))
    def parse(s):
        return eval(s.replace("^", "**"), {"__builtins__": {}}, dict(V))
    G = [parse(l.strip()) for l in open(path) if l.strip()]
    E = [parse(e) for e in (eqs or equations_str())]
    print(f"basis: {len(G)} polynomials, {sum(len(g) for g in G)} terms, "
          f"max coefficient digits {max(max(len(str(c)) for c in g.coeffs()) for g in G)}")
    def lead(f): return f.monoms()[0]  # python-flint returns terms in decreasing order
    def reduce(f):
        f = f; r = R.from_dict({})
        while f != 0:
            m = f.monoms()[0]; c = f.coeffs()[0]
            for g in G:
                lg = lead(g)
                if all(x >= y for x, y in zip(m, lg)):
                    q = R.from_dict({tuple(x - y for x, y in zip(m, lg)): c / g.coeffs()[0]})
                    f = f - q * g; break
            else:
                t = R.from_dict({m: c}); r = r + t; f = f - t
        return r
    ok1 = all(reduce(e) == 0 for e in E)
    print("(1) generators reduce to 0 modulo G:", ok1)
    ok2 = True
    for g, h in itertools.combinations(G, 2):
        lg, lh = lead(g), lead(h)
        if all(x == 0 or y == 0 for x, y in zip(lg, lh)): continue
        L = tuple(max(x, y) for x, y in zip(lg, lh))
        s = R.from_dict({tuple(x - y for x, y in zip(L, lg)): 1 / g.coeffs()[0]}) * g \
            - R.from_dict({tuple(x - y for x, y in zip(L, lh)): 1 / h.coeffs()[0]}) * h
        if reduce(s) != 0: ok2 = False; break
    print("(2) Buchberger criterion (all S-polynomials reduce to 0):", ok2)
    leads = [lead(g) for g in G]
    std = []
    for m in itertools.product(range(4), repeat=len(names)):
        if sum(m) > 3: continue
        if not any(all(x >= y for x, y in zip(m, l)) for l in leads): std.append(m)
    print("(3) standard monomials:", len(std), [ "*".join(f"{names[i]}^{e}" if e > 1 else names[i] for i, e in enumerate(m) if e) or "1" for m in std])
    if expect_std == 0:
        return ok1 and ok2 and len(std) == 0
    # (4) vanishing at the K5 point, exactly in Q[w]/(R)
    Rw = flint.fmpq_poly([26, 0, 3, 3, -1, 1])
    cp = json.load(open(os.path.join(HERE, "chartpoint.json")))
    val = {}
    for i in range(1, 8): val[f"a{i}"] = flint.fmpq_poly([flint.fmpq(c) for c in cp["P"][str(i)]])
    for k in range(0, 10): val[f"b{k}"] = flint.fmpq_poly([flint.fmpq(c) for c in cp["Q"][str(k)]])
    if point == "a1=1":   # rescale the chart point by kappa = 1/a1 (torus weights a_i: i, b_k: k - 10)
        def inv(p):
            g, s_, t_ = p.xgcd(Rw); assert g.degree() == 0; return (s_ / g[0]) % Rw
        a1inv = inv(val["a1"])
        for i in range(2, 8): val[f"a{i}"] = (val[f"a{i}"] * a1inv ** i) % Rw
        for k in range(0, 10): val[f"b{k}"] = (val[f"b{k}"] * val["a1"] ** (10 - k)) % Rw
        del val["a1"]
    def ev(f):
        tot = flint.fmpq_poly([0])
        for m, c in zip(f.monoms(), f.coeffs()):
            t = flint.fmpq_poly([c])
            for i, e in enumerate(m):
                if e: t = (t * val[names[i]] ** e) % Rw
            tot = (tot + t) % Rw
        return tot
    ok4 = all(ev(g) == 0 for g in G) and all(ev(e) == 0 for e in E)
    print("(4) G and the chart equations vanish at the K5 chart point:", ok4)
    # (5) psi: w as a Q-linear combination of 1 and the coordinates
    cols = [[flint.fmpq(1)] + [flint.fmpq(0)] * 4] + [[val[n][j] if j <= val[n].degree() else flint.fmpq(0) for j in range(5)] for n in names]
    M = flint.fmpq_mat(5, len(cols), [cols[c][r] for r in range(5) for c in range(len(cols))])
    target = flint.fmpq_mat(5, 1, [0, 1, 0, 0, 0])
    rank = M.rank()
    print("(5) coordinates span Q[w]/(R) (rank 5, so w is a Q-linear form in them):", rank == 5)
    return ok1 and ok2 and len(std) == 5 and ok4 and rank == 5

if __name__ == "__main__":
    if sys.argv[1] == "write": write()
    elif sys.argv[1] == "verify": sys.exit(0 if verify(sys.argv[2]) else 1)
    elif sys.argv[1] == "verify_split":   # verify_split <gb of the a1 = 1 system over Q> <gb of the a1 = 0 system over Q>
        ok1 = verify(sys.argv[2], SPLIT_NAMES, split_equations_str(1), "a1=1", 5)
        ok0 = verify(sys.argv[3], SPLIT_NAMES, split_equations_str(0), None, 0)
        print("a1 = 1 system:", "PASS" if ok1 else "FAIL", "   a1 = 0 system (unit ideal):", "PASS" if ok0 else "FAIL")
        sys.exit(0 if ok1 and ok0 else 1)
