"""
gen_lean2.py -- emit the exact K5 descent as Lean 4 modules (one lemma per certificate step).

  Jacobian/Descent/E4.lean    z_p = lin(t1,t2)                      (17 lemmas, from the E4 equations)
  Jacobian/Descent/E3.lean    x_p = quad(t) + lin(s)                (18 lemmas, E3 equations + E4 facts)
  Jacobian/Descent/E2.lean    F_i(t,s) = 0  and  b_12_24 = 0 at t=0 (8 lemmas, E2 equations + facts)
  Jacobian/Descent/Span.lean  t1^5 = 0, t2^5 = 0                    (2 lemmas, from F_0..F_6)
  Jacobian/Descent/Main.lean  descent_K5 : ... → False

Each step is `linear_combination (norm := skip) Σ mult * hyp` closed by `ring_nf`, reduction of
w^k (k = 5..12) by R(w) = 0, and `ring_nf`.  All data come from cert.json (make_cert.py), whose
identities are re-verified exactly in Python before being written.
"""
import json, os
from fractions import Fraction
from flint import fmpq_poly

cert = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "cert.json")))
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Jacobian", "Descent")
os.makedirs(OUT, exist_ok=True)
Rr = fmpq_poly([26, 0, 3, 3, -1, 1])
KEY = lambda v: (v[0], int(v.split('_')[1]), int(v.split('_')[2]))

def q(s):
    f = Fraction(s)
    if f.denominator == 1: return f"({f.numerator} : L)"
    return f"(({f.numerator}) / {f.denominator} : L)"
def kel(c):
    terms = []
    for i, s in enumerate(c):
        if Fraction(s) == 0: continue
        terms.append(q(s) + ("" if i == 0 else (" * w" if i == 1 else f" * w ^ ({i} : ℕ)")))
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"
def mono(m): return " * ".join(v if e == 1 else f"{v} ^ ({e} : ℕ)" for v, e in m)
def poly(p):
    if not p: return "(0 : L)"
    return "(" + " + ".join(kel(c) + (" * " + mono(m) if m else "") for m, c in p) + ")"

top = cert["top"]; TOPV = sorted(top, key=KEY)
Z, X, B0 = cert["Z"], cert["X"], cert["B0"]
T1, T2, S1, S2 = cert["T1"], cert["T2"], cert["S1"], cert["S2"]
eqs = cert["eqs"]
HN = {"-3": [], "-2": [], "-1": []}
EQ = {}
for W, tag in (("-3", 4), ("-2", 3), ("-1", 2)):
    for k, terms in eqs[W]:
        n = f"h{tag}_{k[0]}_{k[1]}"
        HN[W].append(n)
        EQ[n] = " + ".join(f"{c} * {pv} * {qv}" if c >= 0 else f"({c}) * {pv} * {qv}" for c, pv, qv in terms)

# w^k reductions
REDL = []
for k in range(5, 13):
    wk = fmpq_poly([0] * k + [1]); qk, rk = divmod(wk, Rr)
    REDL.append((k, kel([str(rk[i]) for i in range(5)]),
                 "(" + " + ".join(f"({qk[i]} : L) * w ^ ({i} : ℕ)" for i in range(qk.degree() + 1)) + ")"))
RED = ", ".join(f"hw{k}" for k, _, _ in REDL)
CLOSE = f"ring_nf <;> (try simp only [{RED}]) <;> (try ring_nf)"
HWLEM = [f"  have hw{k} : w ^ ({k} : ℕ) = {r} := by linear_combination {qq} * hw" for k, r, qq in REDL]

def lincomb(mults, hyps):
    parts = [f"{kel(m)} * {h}" for m, h in zip(mults, hyps) if any(Fraction(x) != 0 for x in m)]
    return " + ".join(parts) if parts else "0"

HDR = """import Mathlib

/-! Generated by gen_lean2.py from cert.json -- exact K₅ descent for branch (a,b), degree pair (72,108).
  K₅ = ℚ[w]/(w⁵ − w⁴ + 3w³ + 3w² + 26); the top layer is the exactly verified point of e5_exact_K5.json
  rescaled by the torus element e = (49w⁴ − 51w³ − 389w² + 879w + 2424)/128 (a₁,₀ = b₂,₁ = 1). -/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace BranchAb.Descent
"""
FTR = "\nend BranchAb.Descent\n"

# ---------- binder blocks (strings) and argument lists (for application)
B_W = ["(w : L)", "(hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0)"]; A_W = ["w", "hw"]
B_TOP = ["(" + " ".join(TOPV) + " : L)"] + [f"(h_{v} : {v} = {kel(top[v])})" for v in TOPV]
A_TOP = TOPV + [f"h_{v}" for v in TOPV]
SUBST_TOP = [f"  subst h_{v}" for v in TOPV]
def B_vars(vs): return ["(" + " ".join(vs) + " : L)"]
def B_hyps(names): return [f"({n} : {EQ[n]} = 0)" for n in names]
zfact = {v: poly(val) for v, val, _ in cert["E4"]}
xfact = {v: poly(val) for v, val, _ in cert["E3"]}
ZP = [v for v, _, _ in cert["E4"]]; XP = [v for v, _, _ in cert["E3"]]
B_HZ = [f"(hz_{v} : {v} = {zfact[v]})" for v in ZP]; A_HZ = [f"hz_{v}" for v in ZP]
B_HX = [f"(hx_{v} : {v} = {xfact[v]})" for v in XP]; A_HX = [f"hx_{v}" for v in XP]
Fexpr = [poly(F) for F in cert["F"]]
B_HF = [f"(hF{i} : {Fexpr[i]} = 0)" for i in range(7)]; A_HF = [f"hF{i}" for i in range(7)]

def lemma(name, binders, concl, body):
    s = [f"theorem {name} {{L : Type*}} [Field L] [CharZero L]"]
    s += ["    " + b for b in binders]
    s[-1] += f" :\n    {concl} := by"
    return "\n".join(s + body) + "\n"

files = {}
mods = []
def put(sub, name, text):
    files[f"{sub}/{name}"] = HDR + "\n" + text + FTR
    mods.append(f"Jacobian.Descent.{sub}.{name}")
# ---- E4
for v, val, E_ in cert["E4"]:
    body = SUBST_TOP + HWLEM + [f"  linear_combination (norm := skip) {lincomb(E_, HN['-3'])}", f"  {CLOSE}"]
    put("E4", f"z_{v}", lemma(f"e4_{v}", B_W + B_TOP + B_vars(Z) + B_hyps(HN["-3"]), f"{v} = {zfact[v]}", body))
# ---- E3, stage A: each E3 equation with the E4 facts substituted, reduced mod R
R3 = [poly(p_) for p_ in cert["E3red"]]; R2 = [poly(p_) for p_ in cert["E2red"]]
RN3 = [f"r3_{n[3:]}" for n in HN["-2"]]; RN2 = [f"r2_{n[3:]}" for n in HN["-1"]]
for n, rn, rp in zip(HN["-2"], RN3, R3):
    body = SUBST_TOP + [f"  subst {h}" for h in A_HZ] + HWLEM + [f"  linear_combination (norm := skip) h", f"  {CLOSE}"]
    put("E3red", rn, lemma(f"e3red_{n[3:]}", B_W + B_TOP + B_vars(Z) + B_HZ + B_vars(X) + [f"(h : {EQ[n]} = 0)"],
                           f"{rp} = 0", body))
# ---- E3, stage B: pivots from the reduced equations
XV = X
B_R3 = [f"({rn} : {rp} = 0)" for rn, rp in zip(RN3, R3)]
for v, val, E_ in cert["E3"]:
    body = HWLEM + [f"  linear_combination (norm := skip) {lincomb(E_, RN3)}", f"  {CLOSE}"]
    put("E3", f"x_{v}", lemma(f"e3_{v}", B_W + B_vars([T1, T2] + XV) + B_R3, f"{v} = {xfact[v]}", body))
# ---- E2, stage A: each E2 equation with E4 and E3 facts substituted, reduced mod R
for n, rn, rp in zip(HN["-1"], RN2, R2):
    body = SUBST_TOP + [f"  subst {h}" for h in A_HZ] + [f"  subst {h}" for h in A_HX] + HWLEM + \
        [f"  linear_combination (norm := skip) h", f"  {CLOSE}"]
    put("E2red", rn, lemma(f"e2red_{n[3:]}", B_W + B_TOP + B_vars(Z) + B_HZ + B_vars(X) + B_HX + B_vars(B0) +
                           [f"(h : {EQ[n]} = 0)"], f"{rp} = 0", body))
# ---- E2, stage B: the seven conditions and the t = 0 step
B_R2 = [f"({rn} : {rp} = 0)" for rn, rp in zip(RN2, R2)]
for i, wrow in enumerate(cert["W"]):
    body = HWLEM + [f"  linear_combination (norm := skip) {lincomb(wrow, RN2)}", f"  {CLOSE}"]
    put("E2", f"F{i}", lemma(f"e2_F{i}", B_W + B_vars([T1, T2, S1, S2] + B0) + B_R2, f"{Fexpr[i]} = 0", body))
body = ["  subst ht1", "  subst ht2"] + HWLEM + \
    [f"  linear_combination (norm := skip) {lincomb(cert['inv12'], RN2)}", f"  {CLOSE}"]
put("E2", "T0", lemma("e2_t0", B_W + B_vars([T1, T2, S1, S2] + B0) + B_R2 +
                      [f"(ht1 : {T1} = 0)", f"(ht2 : {T2} = 0)"], "b_12_24 = 0", body))
# ---- span
for nm, G, tv in (("span_t1", cert["G0"], T1), ("span_t2", cert["G1"], T2)):
    gl = " + ".join(f"{poly(g)} * hF{i}" for i, g in enumerate(G) if g)
    body = HWLEM + [f"  linear_combination (norm := skip) {gl}", f"  {CLOSE}"]
    put("Span", nm, lemma(nm, B_W + B_vars([T1, T2, S1, S2]) + B_HF, f"{tv} ^ 5 = 0", body))
# ---- main
HDR_MAIN = HDR.replace("import Mathlib\n", "import Mathlib\n" + "".join(f"import {m}\n" for m in mods))
body = []
for v in ZP:
    body.append(f"  have hz_{v} := e4_{v} " + " ".join(A_W + A_TOP + Z + HN["-3"]))
for n, rn in zip(HN["-2"], RN3):
    body.append(f"  have {rn} := e3red_{n[3:]} " + " ".join(A_W + A_TOP + Z + A_HZ + X + [n]))
for v in XP:
    body.append(f"  have hx_{v} := e3_{v} " + " ".join(A_W + [T1, T2] + X + RN3))
for n, rn in zip(HN["-1"], RN2):
    body.append(f"  have {rn} := e2red_{n[3:]} " + " ".join(A_W + A_TOP + Z + A_HZ + X + A_HX + B0 + [n]))
for i in range(7):
    body.append(f"  have hF{i} := e2_F{i} " + " ".join(A_W + [T1, T2, S1, S2] + B0 + RN2))
body.append(f"  have ht1 := span_t1 " + " ".join(A_W + [T1, T2, S1, S2] + A_HF))
body.append(f"  have ht2 := span_t2 " + " ".join(A_W + [T1, T2, S1, S2] + A_HF))
body.append(f"  have ht1' : {T1} = 0 := pow_eq_zero_iff (by norm_num) |>.mp ht1")
body.append(f"  have ht2' : {T2} = 0 := pow_eq_zero_iff (by norm_num) |>.mp ht2")
body.append(f"  exact hv (e2_t0 " + " ".join(A_W + [T1, T2, S1, S2] + B0 + RN2 + ["ht1'", "ht2'"]) + ")")
doc = '''/-- **Exact K₅ descent.**  For every field `L` of characteristic zero and every root `w` of
`R = w⁵ − w⁴ + 3w³ + 3w² + 26`, the bracket equations of weights −3, −2, −1 (the E₄, E₃, E₂ layers)
at the rescaled K₅ top layer have no solution with `b₁₂,₂₄ ≠ 0`. -/
'''
main = lemma("descent_K5", B_W + B_TOP + B_vars(Z + X + B0) + B_hyps(HN["-3"] + HN["-2"] + HN["-1"]) +
             ["(hv : b_12_24 ≠ 0)"], "False", body)
files["Main"] = HDR_MAIN + "\n" + doc + main + FTR
import shutil
for sub in ("E4", "E3red", "E3", "E2red", "E2", "Span"):
    shutil.rmtree(f"{OUT}/{sub}", ignore_errors=True)
    if os.path.exists(f"{OUT}/{sub}.lean"): os.remove(f"{OUT}/{sub}.lean")
    os.makedirs(f"{OUT}/{sub}", exist_ok=True)
for n, text in files.items():
    open(f"{OUT}/{n}.lean", "w").write(text)
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "modules.txt"), "w").write("\n".join(mods) + "\n")
print(len(files), "files;", sum(len(t) for t in files.values()), "bytes")
