"""
gen_main.py -- emit Jacobian/BranchAbMain.lean:

  no_completion_K5_PQ            : P, Q with support in N(P), N(Q), J(P,Q) = λx², top-layer coefficients of
                                   P and Q on the torus orbit of a K5 point, and Q.coeff(12,24) ≠ 0  →  False
  main_theorem_of_classification : TopLayerClassification L  →  ¬∃ P Q λ, λ ≠ 0 ∧ NewtonNF2 P Q ∧ J(P,Q) = λx²
                                   (the paper's Main Theorem 1.1, for any characteristic-0 field L)

The per-coefficient bridging between the layer theorem `no_completion_K5` (explicit K5 values) and the
P,Q-level hypotheses (`topA w i`, `topB w k`) is generated; everything else is general.
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
cert = json.load(open(os.path.join(HERE, "cert.json")))
top = cert["top"]
KEY = lambda v: (v[0], int(v.split('_')[1]), int(v.split('_')[2]))
TOPV = sorted(top, key=KEY)
SUPP = [("A₀", 0, 0, 8), ("A₁", 1, 1, 8), ("A₂", 2, 1, 8), ("B₀", 0, 0, 12), ("B₁", 1, 1, 12), ("B₂", 2, 2, 12), ("B₃", 3, 2, 12)]

L = ['''import Jacobian.BranchAbFinal
import Jacobian.BranchAbNewton
import Jacobian.BranchAbClassification

/-! Generated by gen_main.py.  The paper's Main Theorem 1.1 in Lean, conditional only on the top-layer
classification `TopLayerClassification` (Proposition 6.1), which is stated but not proved. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false

open MvPolynomial

noncomputable section

namespace BranchAb

/-- Layer data of `P` (weights 0, 1, 2) and `Q` (weights 0, …, 3) from the Newton-polygon supports. -/
theorem layers_of_support {K : Type*} [Field K] (P Q : MvPolynomial (Fin 2) K)
    (hP : ∀ m ∈ P.support, inNP m) (hQ : ∀ m ∈ Q.support, inNQ m) :
    P = layerPiece P 0 + layerPiece P 1 + layerPiece P 2 ∧
    Q = layerPiece Q 0 + layerPiece Q 1 + layerPiece Q 2 + layerPiece Q 3 := by
  constructor
  · have h := eq_sum_layerPiece P 2 (fun m hm => by have := hP m hm; unfold inNP at this; omega)
    simpa [Finset.sum_range_succ] using h
  · have h := eq_sum_layerPiece Q 3 (fun m hm => by have := hQ m hm; unfold inNQ at this; omega)
    simpa [Finset.sum_range_succ] using h
''']
L.append('''/-- **No completion of the K₅ orbit, at the level of `P` and `Q`.** -/''')
L.append("theorem no_completion_K5_PQ {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) (lam : L) (P Q : MvPolynomial (Fin 2) L)")
L.append("    (hP : ∀ m ∈ P.support, inNP m) (hQ : ∀ m ∈ Q.support, inNQ m)")
L.append("    (hJ : jac P Q = C lam * X 0 ^ 2) (ρ σ ε : L) (hρ : ρ ≠ 0) (hσ : σ ≠ 0) (hε : ε ≠ 0)")
L.append("    (tP : ∀ i, 1 ≤ i → i ≤ 8 → P.coeff (mono i (2 * i - 2)) = ρ * ε ^ (i - 1) * topA w i)")
L.append("    (tQ : ∀ k, 2 ≤ k → k ≤ 12 → Q.coeff (mono k (2 * k - 3)) = σ * ε ^ (k - 2) * topB w k)")
L.append("    (hv : Q.coeff (mono 12 24) ≠ 0) : False := by")
L.append("  obtain ⟨hPs, hQs⟩ := layers_of_support P Q hP hQ")
L.append("  have hJ' : jac (layerPiece P 0 + layerPiece P 1 + layerPiece P 2)")
L.append("      (layerPiece Q 0 + layerPiece Q 1 + layerPiece Q 2 + layerPiece Q 3) = C lam * X 0 ^ 2 := by")
L.append("    rw [← hPs, ← hQs]; exact hJ")
for nm, a, lo, hi in SUPP:
    PQ = "P" if nm.startswith("A") else "Q"; S = "inNP" if PQ == "P" else "inNQ"; hh = "hP" if PQ == "P" else "hQ"
    L.append(f"  have s{nm} : ∀ i, (layerPoly {PQ} {a}).coeff i ≠ 0 → {lo} ≤ i ∧ i ≤ {hi} :=")
    L.append(f"    layerPoly_support {PQ} {a} {S} {hh} {lo} {hi} (fun i ha h => by unfold {S} at h; simp at h; omega)")
tops = []
for v in TOPV:
    i = int(v.split('_')[1]); a = v[0]
    PQ, lay, t, ex, fn = ("P", 2, "tP", f"{i - 1}", "topA") if a == 'a' else ("Q", 3, "tQ", f"{i - 2}", "topB")
    L.append(f"  have t_{v} := by")
    L.append(f"    have h := {t} {i} (by norm_num) (by norm_num)")
    L.append(f"    rw [← coeff_layerPoly_of_le {PQ} {lay} {i} (by norm_num)] at h")
    L.append(f"    exact h")
    tops.append(f"t_{v}")
L.append("  have hv' : (layerPoly Q 0).coeff 12 ≠ 0 := by")
L.append("    rw [coeff_layerPoly_of_le Q 0 12 (by norm_num)]; exact hv")
args = ("w hw lam (layerPoly P 0) (layerPoly P 1) (layerPoly P 2) (layerPoly Q 0) (layerPoly Q 1) "
        "(layerPoly Q 2) (layerPoly Q 3) (layerPiece P 0) (layerPiece P 1) (layerPiece P 2) (layerPiece Q 0) "
        "(layerPiece Q 1) (layerPiece Q 2) (layerPiece Q 3) (X1_pow_mul_layerPiece P 0) (X1_pow_mul_layerPiece P 1) "
        "(X1_pow_mul_layerPiece P 2) (X1_pow_mul_layerPiece Q 0) (X1_pow_mul_layerPiece Q 1) "
        "(X1_pow_mul_layerPiece Q 2) (X1_pow_mul_layerPiece Q 3) hJ' " +
        " ".join(f"s{nm}" for nm, _, _, _ in SUPP) + " ρ σ ε hρ hσ hε")
L.append("  refine no_completion_K5 " + args + " ?_ " * len(tops) + " hv'")
for t in tops:
    L.append(f"  · exact {t}")
L.append('''
/-- **Main Theorem 1.1 of the paper, conditional on the top-layer classification.**  Over a field of
characteristic zero in which `TopLayerClassification` holds (for `ℂ`, this is the paper's
Proposition 6.1), there are no `P, Q` with the normal-form-(2) Newton polygons
`N(P) = conv{(0,0),(1,0),(8,14),(8,16)}` and `N(Q) = conv{(0,0),(2,1),(12,21),(12,24)}` and
`[P, Q] = λ x²` with `λ ≠ 0`.  GGHV Proposition 4.3, which reduces a (72,108) counterexample to the
normal forms, is not part of this statement. -/
theorem main_theorem_of_classification {L : Type*} [Field L] [CharZero L]
    (hcl : TopLayerClassification L) :
    ¬ ∃ (P Q : MvPolynomial (Fin 2) L) (lam : L), lam ≠ 0 ∧ NewtonNF2 P Q ∧ jac P Q = C lam * X 0 ^ 2 := by
  rintro ⟨P, Q, lam, -, ⟨hP, hQ, -, v10, v814, -, -, w21, w1221, w1224⟩, hJ⟩
  obtain ⟨hPs, hQs⟩ := layers_of_support P Q hP hQ
  have hJ' : jac (layerPiece P 0 + layerPiece P 1 + layerPiece P 2)
      (layerPiece Q 0 + layerPiece Q 1 + layerPiece Q 2 + layerPiece Q 3) = C lam * X 0 ^ 2 := by
    rw [← hPs, ← hQs]; exact hJ
  obtain ⟨E5, -, -, -, -⟩ := layers_of_jac lam _ _ _ _ _ _ _ _ _ _ _ _ _ _
    (X1_pow_mul_layerPiece P 0) (X1_pow_mul_layerPiece P 1) (X1_pow_mul_layerPiece P 2)
    (X1_pow_mul_layerPiece Q 0) (X1_pow_mul_layerPiece Q 1) (X1_pow_mul_layerPiece Q 2)
    (X1_pow_mul_layerPiece Q 3) hJ'
  have sA₂ : ∀ i, (layerPoly P 2).coeff i ≠ 0 → 1 ≤ i ∧ i ≤ 8 :=
    layerPoly_support P 2 inNP hP 1 8 (fun i ha h => by unfold inNP at h; simp at h; omega)
  have sB₃ : ∀ i, (layerPoly Q 3).coeff i ≠ 0 → 2 ≤ i ∧ i ≤ 12 :=
    layerPoly_support Q 3 inNQ hQ 2 12 (fun i ha h => by unfold inNQ at h; simp at h; omega)
  have a1 : (layerPoly P 2).coeff 1 ≠ 0 := by rw [coeff_layerPoly_of_le P 2 1 (by norm_num)]; exact v10
  have a8 : (layerPoly P 2).coeff 8 ≠ 0 := by rw [coeff_layerPoly_of_le P 2 8 (by norm_num)]; exact v814
  have b2 : (layerPoly Q 3).coeff 2 ≠ 0 := by rw [coeff_layerPoly_of_le Q 3 2 (by norm_num)]; exact w21
  have b12 : (layerPoly Q 3).coeff 12 ≠ 0 := by rw [coeff_layerPoly_of_le Q 3 12 (by norm_num)]; exact w1221
  obtain ⟨w, ρ, σ, ε, hw, hρ, hσ, hε, hA, hB⟩ := hcl _ _ lam sA₂ sB₃ a1 a8 b2 b12 E5
  refine no_completion_K5_PQ w hw lam P Q hP hQ hJ ρ σ ε hρ hσ hε ?_ ?_ w1224
  · intro i hi1 hi8
    rw [← coeff_layerPoly_of_le P 2 i (by omega)]; exact hA i
  · intro k hk2 hk12
    rw [← coeff_layerPoly_of_le Q 3 k (by omega)]; exact hB k

end BranchAb
''')
open(os.path.join(HERE, "..", "Jacobian", "BranchAbMain.lean"), "w").write("\n".join(L))
print("written BranchAbMain.lean")
