"""
gen_chart.py -- emit Jacobian/BranchAbChart.lean.

Reduces the top-layer classification (Proposition 6.1, `TopLayerClassification`) to a statement about one
zero-dimensional polynomial system, `ChartClassification`, and proves the reduction in Lean.

Normalization.  Let x_j = A2.coeff (j+1) (j = 0..7) and y_k = B3.coeff (k+2) (k = 0..10); all four of
x_0, x_7, y_0, y_10 are nonzero by the vertex hypotheses.  Put
    kappa = x_0^3 y_10^2 / (x_7^3 y_0^2),   a_j = x_j kappa^j / x_0,   b_k = y_k kappa^k / (kappa^10 y_10).
Then a_0 = b_10 = 1, the E5 coefficient equations become the 16 bilinear equations
    E_n :  sum_{i+k=n} (1 + 2k - 3i) a_i b_k = 0      (n = 1..16),
and the torus is fixed by  a_7^3 b_0^2 = 1  (the weight-1 invariant x_7^3 y_0^2 / (x_0^3 y_10^2) scaled to 1).
No case split is needed: kappa only divides by the four vertex coefficients.

`ChartClassification L`: every solution (a_1..a_7, b_0..b_9) in L of E_1..E_16 and a_7^3 b_0^2 = 1 is the
chart point (P_j(w), Q_k(w)) of the K5 top layer for some root w of R.  P_j, Q_k are computed exactly in
k5point.py (chartpoint.json) from the hard-coded top layer topA/topB.

`topLayerClassification_of_chart`: ChartClassification L -> TopLayerClassification L   (kernel-checked).
"""
import json, os, sys
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "Jacobian", "BranchAbChart.lean")
w = sp.symbols('w')
RP = sp.Poly(w**5 - w**4 + 3*w**3 + 3*w**2 + 26, w, domain='QQ')

cp = json.load(open(os.path.join(HERE, "chartpoint.json")))
P = {int(i): sp.Poly(list(reversed([sp.Rational(c) for c in v])), w, domain='QQ') for i, v in cp["P"].items()}
Q = {int(k): sp.Poly(list(reversed([sp.Rational(c) for c in v])), w, domain='QQ') for k, v in cp["Q"].items()}
kT = sp.Poly(list(reversed([sp.Rational(c) for c in cp["kT"]])), w, domain='QQ')

# topA / topB from the sharpness module (the same values gen_sharp.py writes)
import re
src = open(os.path.join(HERE, "..", "Jacobian", "BranchAbSharp.lean")).read()
TA, TB = {}, {}
for line in src.splitlines():
    m = re.match(r"\s*\(t([AB])(\d+) : [AB].\.coeff (\d+) = (.*)\)$", line)
    if m:
        ex = m.group(4).replace(": L", "").replace("w ^ (", "w**(").replace(" : ℕ)", ")")
        (TA if m.group(1) == 'A' else TB)[int(m.group(3))] = sp.Poly(sp.sympify(ex), w, domain='QQ')
assert sorted(TA) == list(range(1, 9)) and sorted(TB) == list(range(2, 13))

def red(p): return p.rem(RP)
def quo(p): return p.div(RP)[0]
def inv(p):
    s, t, g = sp.gcdex(p.as_expr(), RP.as_expr(), w)
    g = sp.Poly(g, w, domain='QQ'); assert g.degree() == 0
    return red(sp.Poly(s, w, domain='QQ') * (1 / g.as_expr()))

def lq(c):
    c = sp.Rational(c)
    return f"(({c.p} : L))" if c.q == 1 else f"(({c.p}) / {c.q} : L)"
def lpoly(p):
    cs = p.all_coeffs()[::-1]
    terms = []
    for e, c in enumerate(cs):
        if c == 0: continue
        terms.append(lq(c) if e == 0 else f"{lq(c)} * w" if e == 1 else f"{lq(c)} * w ^ ({e} : ℕ)")
    return "(" + (" + ".join(terms) if terms else "(0 : L)") + ")"

def coef(i, k): return 1 + 2 * k - 3 * i
AV = {i: f"a{i}" for i in range(1, 8)}; BV = {k: f"b{k}" for k in range(0, 10)}
def eq_n(n, A, B):
    """E_n with a0 = 1, b10 = 1; A, B map index -> Lean term"""
    t = []
    for i in range(0, 8):
        k = n - i
        if 0 <= k <= 10 and coef(i, k):
            fa = A.get(i); fb = B.get(k)
            parts = [f"({coef(i, k)} : L)"] + ([fa] if fa else []) + ([fb] if fb else [])
            t.append(" * ".join(parts))
    return " + ".join(t)

VARS = [AV[i] for i in range(1, 8)] + [BV[k] for k in range(0, 10)]

L = ['''import Jacobian.BranchAbMain

/-! Generated by gen_chart.py.  Reduction of the top-layer classification (Proposition 6.1) to one
zero-dimensional polynomial system.

With `x_j = A₂.coeff (j+1)`, `y_k = B₃.coeff (k+2)` and `κ = x₀³ y₁₀² / (x₇³ y₀²)`, the chart coordinates
`a_j = x_j κ^j / x₀`, `b_k = y_k κ^k / (κ^10 y₁₀)` satisfy `a₀ = b₁₀ = 1`, the sixteen bilinear equations
`E_n : Σ_{i+k=n} (1 + 2k − 3i) a_i b_k = 0` (`n = 1, …, 16`, from E5) and the torus normalization
`a₇³ b₀² = 1`.  Only the four vertex coefficients are inverted, so no case split is needed.

* `ChartClassification L`: every solution of this system in `L` is the chart point of the K₅ top layer,
  `(a_j, b_k) = (P_j(w), Q_k(w))`, for some root `w` of `R`.
* `topLayerClassification_of_chart`: `ChartClassification L → TopLayerClassification L`.
-/

set_option maxHeartbeats 0
set_option maxRecDepth 1000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false
set_option linter.unnecessarySeqFocus false

open Polynomial

noncomputable section

namespace BranchAb
''']

# --- statement of ChartClassification
L.append("/-- **The chart system has only the K₅ solutions.**  Every solution of `E₁, …, E₁₆` and")
L.append("`a₇³ b₀² = 1` (with `a₀ = b₁₀ = 1`) is the chart point of the K₅ top layer for a root `w` of `R`. -/")
L.append("def ChartClassification (L : Type*) [Field L] : Prop :=")
L.append("  ∀ " + " ".join(VARS) + " : L,")
for n in range(1, 17):
    L.append(f"    {eq_n(n, AV, BV)} = 0 →")
L.append("    a7 ^ 3 * b0 ^ 2 = 1 →")
L.append("    ∃ w : L, w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0 ∧")
concl = [f"a{i} = {lpoly(P[i])}" for i in range(1, 8)] + [f"b{k} = {lpoly(Q[k])}" for k in range(0, 10)]
L.append("      " + " ∧\n      ".join(concl))
L.append("")

# --- K5 identities used in the reconstruction
# (1) P_j = kT^j * TA_{j+1}  mod R          (j = 0..7)
# (2) Q_k * kT^(10-k) * TB_12 = TB_{k+2} mod R   (k = 0..10)
# (3) kT * kTinv = 1, TB12 * TB12inv = 1  mod R
kTinv = inv(kT); TB12inv = inv(TB[12])
def lc_hint(expr_poly):
    q = quo(expr_poly)
    return lpoly(q) + " * hw"
L.append("/-- K₅ identities behind the reconstruction of `A₂`, `B₃` from the chart point. -/")
L.append("theorem chart_K5_identities {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) :")
ids = []
for j in range(0, 8):
    lhs = P[j]; rhs = sp.Poly((kT ** j * TA[j + 1]).as_expr(), w, domain='QQ')
    ids.append((f"{lpoly(P[j])} = {lpoly(kT)} ^ {j} * topA w {j + 1}", lhs - rhs))
for k in range(0, 11):
    lhs = sp.Poly((Q[k] * kT ** (10 - k) * TB[12]).as_expr(), w, domain='QQ'); rhs = TB[k + 2]
    ids.append((f"{lpoly(Q[k])} * {lpoly(kT)} ^ {10 - k} * topB w 12 = topB w {k + 2}", lhs - rhs))
ids.append((f"{lpoly(kT)} * {lpoly(kTinv)} = 1", sp.Poly((kT * kTinv).as_expr() - 1, w, domain='QQ')))
ids.append((f"topB w 12 * {lpoly(TB12inv)} = 1", sp.Poly((TB[12] * TB12inv).as_expr() - 1, w, domain='QQ')))
L.append("    (" + ") ∧\n    (".join(s for s, _ in ids) + ") := by")
for s_, diff in ids:
    assert red(diff).is_zero, s_
L.append("  refine ⟨" + ", ".join("?_" for _ in ids) + "⟩")
for s_, diff in ids:
    pre = "simp only [topA, topB]; " if ("topA" in s_ or "topB" in s_) else ""
    L.append(f"  · {pre}linear_combination ({lc_hint(diff)})")
L.append("")


# --- the reduction theorem
L.append("lemma topA_of_ge {L : Type*} [Field L] (w : L) (i : ℕ) (h : 9 ≤ i) : topA w i = 0 := by")
L.append("  obtain ⟨j, rfl⟩ : ∃ j, i = j + 9 := ⟨i - 9, by omega⟩")
L.append("  rfl")
L.append("lemma topB_of_ge {L : Type*} [Field L] (w : L) (i : ℕ) (h : 13 ≤ i) : topB w i = 0 := by")
L.append("  obtain ⟨j, rfl⟩ : ∃ j, i = j + 13 := ⟨i - 13, by omega⟩")
L.append("  rfl")
L.append("")
L.append("/-- **Reduction of Proposition 6.1 to the chart system.** -/")
L.append("theorem topLayerClassification_of_chart {L : Type*} [Field L] [CharZero L]")
L.append("    (hc : ChartClassification L) : TopLayerClassification L := by")
L.append("  intro A₂ B₃ lam sA sB h1 h8 h2 h12 hE5")
ZA = [0] + list(range(9, 21)); ZB = [0, 1] + list(range(13, 21))
for i in ZA: L.append(f"  have zA{i} : A₂.coeff {i} = 0 := coeff_zero_of_support _ 1 8 sA {i} (by omega)")
for k in ZB: L.append(f"  have zB{k} : B₃.coeff {k} = 0 := coeff_zero_of_support _ 2 12 sB {k} (by omega)")
zs = ", ".join([f"zA{i}" for i in ZA] + [f"zB{k}" for k in ZB])
XV = {i: f"A₂.coeff {i + 1}" for i in range(0, 8)}; YV = {k: f"B₃.coeff {k + 2}" for k in range(0, 11)}
def scal(n):
    t = []
    for i in range(0, 8):
        k = n - i
        if 0 <= k <= 10 and coef(i, k): t.append(f"({coef(i, k)} : L) * {XV[i]} * {YV[k]}")
    return " + ".join(t)
for n in range(1, 17):
    L.append(f"  have s{n} : {scal(n)} = 0 := by")
    L.append(f"    have e := congrArg (fun F => Polynomial.coeff F {n + 2}) hE5")
    L.append(f"    simp only [coeff_layerTerm, Polynomial.coeff_C_mul_X_pow, Finset.sum_range_succ, Finset.sum_range_zero, Nat.cast_ofNat, Nat.cast_zero, Nat.cast_one, zero_add, {zs}, mul_zero, zero_mul, add_zero, sub_zero, ↓reduceIte] at e")
    L.append(f"    rw [ite_eq_right (by norm_num : ({n + 2} : ℕ) ≠ 2)] at e")
    L.append(f"    linear_combination e")
L.append("  obtain ⟨κ, hκ⟩ : ∃ κ : L, κ = A₂.coeff 1 ^ 3 * B₃.coeff 12 ^ 2 / (A₂.coeff 8 ^ 3 * B₃.coeff 2 ^ 2) := ⟨_, rfl⟩")
L.append("  have hκ0 : κ ≠ 0 := by")
L.append("    rw [hκ]; exact div_ne_zero (mul_ne_zero (pow_ne_zero _ h1) (pow_ne_zero _ h12)) (mul_ne_zero (pow_ne_zero _ h8) (pow_ne_zero _ h2))")
AX = {i: f"(A₂.coeff {i + 1} * κ ^ {i} / A₂.coeff 1)" for i in range(1, 8)}
BX = {k: f"(B₃.coeff {k + 2} * κ ^ {k} / (κ ^ 10 * B₃.coeff 12))" for k in range(0, 10)}
for n in range(1, 17):
    L.append(f"  have e{n} : {eq_n(n, AX, BX)} = 0 := by")
    L.append(f"    have key : {eq_n(n, AX, BX)} = κ ^ {n} / (κ ^ 10 * A₂.coeff 1 * B₃.coeff 12) * ({scal(n)}) := by")
    L.append(f"      field_simp")
    L.append(f"      try ring")
    L.append(f"    rw [key, s{n}, mul_zero]")
L.append(f"  have en : {AX[7]} ^ 3 * {BX[0]} ^ 2 = 1 := by")
L.append(f"    rw [hκ]; field_simp")
L.append(f"    try ring")
args = " ".join([AX[i] for i in range(1, 8)] + [BX[k] for k in range(0, 10)])
L.append(f"  obtain ⟨w, hw, " + ", ".join([f"ha{i}" for i in range(1, 8)] + [f"hb{k}" for k in range(0, 10)]) + "⟩ :=")
L.append(f"    hc {args} " + " ".join(f"e{n}" for n in range(1, 17)) + " en")
L.append("  obtain ⟨" + ", ".join([f"i{j}" for j in range(8)] + [f"j{k}" for k in range(11)] + ["ikT", "iTB"]) + "⟩ := chart_K5_identities w hw")
L.append(f"  have hkT : {lpoly(kT)} ≠ 0 := left_ne_zero_of_mul_eq_one ikT")
L.append(f"  have hTB : topB w 12 ≠ 0 := left_ne_zero_of_mul_eq_one iTB")
L.append("  -- make the K₅ torus parameter an opaque atom (so that `field_simp` does not expand it)")
L.append(f"  generalize hKd : {lpoly(kT)} = K at hkT " + " ".join([f"i{j}" for j in range(8)] + [f"j{k}" for k in range(11)]))
L.append(f"  have hε : K / κ ≠ 0 := div_ne_zero hkT hκ0")
L.append(f"  refine ⟨w, A₂.coeff 1, B₃.coeff 12 / ((K / κ) ^ 10 * topB w 12), K / κ, hw, h1,")
L.append(f"    div_ne_zero h12 (mul_ne_zero (pow_ne_zero _ hε) hTB), hε, ?_, ?_⟩")
# A part
L.append("  · intro i")
L.append("    rcases Nat.lt_or_ge i 9 with hi | hi")
L.append("    · interval_cases i")
L.append("      · rw [zA0]; simp [topA]")
L.append("      · simp [topA]")
for j in range(1, 8):
    L.append(f"      · have c1 : A₂.coeff {j + 1} * κ ^ {j} / A₂.coeff 1 * A₂.coeff 1 / κ ^ {j} = A₂.coeff {j + 1} := by")
    L.append(f"          rw [div_mul_cancel₀ _ h1, mul_div_cancel_right₀ _ (pow_ne_zero _ hκ0)]")
    L.append(f"        rw [show ({j + 1} : ℕ) - 1 = {j} from rfl, ← c1, ha{j}, i{j}, div_pow]")
    L.append(f"        ring")
L.append("    · rw [coeff_zero_of_support _ 1 8 sA i (by omega), topA_of_ge w i hi, mul_zero]")
# B part
L.append("  · intro k")
L.append("    rcases Nat.lt_or_ge k 13 with hk | hk")
L.append("    · interval_cases k")
L.append("      · rw [zB0]; simp [topB]")
L.append("      · rw [zB1]; simp [topB]")
for k in range(0, 10):
    L.append(f"      · have c1 : B₃.coeff {k + 2} * κ ^ {k} / (κ ^ 10 * B₃.coeff 12) * (κ ^ 10 * B₃.coeff 12) / κ ^ {k} = B₃.coeff {k + 2} := by")
    L.append(f"          rw [div_mul_cancel₀ _ (mul_ne_zero (pow_ne_zero _ hκ0) h12), mul_div_cancel_right₀ _ (pow_ne_zero _ hκ0)]")
    L.append(f"        rw [show ({k + 2} : ℕ) - 2 = {k} from rfl, ← c1, hb{k}, ← j{k}]")
    L.append(f"        field_simp")
    L.append(f"        try ring")
L.append(f"      · rw [show (12 : ℕ) - 2 = 10 from rfl]")
L.append(f"        field_simp")
L.append("    · rw [coeff_zero_of_support _ 2 12 sB k (by omega), topB_of_ge w k hk, mul_zero]")
L.append("")

# --- non-vacuity: the chart point solves the chart system
L.append("/-- **Non-vacuity of `ChartClassification`.**  For every root `w` of `R`, the K₅ chart point")
L.append("`(P_j(w), Q_k(w))` satisfies `E₁, …, E₁₆` and `a₇³ b₀² = 1`. -/")
L.append("theorem chart_point_solves {L : Type*} [Field L] [CharZero L] (w : L)")
L.append("    (hw : w ^ 5 - w ^ 4 + 3 * w ^ 3 + 3 * w ^ 2 + 26 = 0) :")
PA = {i: lpoly(P[i]) for i in range(1, 8)}; QB = {k: lpoly(Q[k]) for k in range(0, 10)}
goals = []
for n in range(1, 17):
    expr = sp.Poly(0, w, domain='QQ')
    for i in range(0, 8):
        k = n - i
        if 0 <= k <= 10 and coef(i, k):
            expr += coef(i, k) * P[i] * Q[k]
    goals.append((f"{eq_n(n, PA, QB)} = 0", expr))
goals.append((f"{PA[7]} ^ 3 * {QB[0]} ^ 2 = 1", sp.Poly((P[7] ** 3 * Q[0] ** 2).as_expr() - 1, w, domain='QQ')))
L.append("    (" + ") ∧\n    (".join(g for g, _ in goals) + ") := by")
L.append("  refine ⟨" + ", ".join("?_" for _ in goals) + "⟩")
for g, e in goals:
    assert red(e).is_zero
    L.append(f"  · linear_combination ({lc_hint(e)})")
L.append("")
L.append("/-- **Main Theorem 1.1, conditional only on the chart system.**  `ChartClassification L` is a statement")
L.append("about one explicit zero-dimensional polynomial system (17 equations in 17 unknowns). -/")
L.append("theorem main_theorem_of_chart {L : Type*} [Field L] [CharZero L] (hc : ChartClassification L) :")
L.append("    ¬ ∃ (P Q : MvPolynomial (Fin 2) L) (lam : L), lam ≠ 0 ∧ NewtonNF2 P Q ∧ jac P Q = MvPolynomial.C lam * MvPolynomial.X 0 ^ 2 :=")
L.append("  main_theorem_of_classification (topLayerClassification_of_chart hc)")
L.append("")
L.append("end BranchAb")

open(OUT, "w").write("\n".join(L))
print("written", OUT)
