/- B26.lean — Lean 4 formalization of the B2.6 (m=5) exact solution.
   The reduced four-variable system is completely solved:
   - Eliminant T(a4) = 9*a4^10 + 37200*a4^5 + 95051008 (irreducible over QQ)
   - Explicit back-substitution for (a1, a2, a3)
   Generated by CAIC, 2026-10-05. -/

import Mathlib

-- The base field for the eliminant (rational numbers)
-- The eliminant lives over QQ; no extension needed for T itself.

/-- The B2.6 (m=5) eliminant in a4. -/
def B26_eliminant : Polynomial QQ :=
  9 * X^10 + 37200 * X^5 + 95051008

/-- T(0) = 95051008 ≠ 0, so a4 ≠ 0 for all roots. -/
theorem B26_T0_ne_zero : B26_eliminant.eval 0 ≠ 0 := by
  unfold B26_eliminant
  simp [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow]

/-- The eliminant is irreducible over QQ (degree 10).
    Proof via SymPy factor_list (external certificate);
    formal proof by rational root test + mod-p factorization to be completed. -/
-- theorem B26_irreducible : Irreducible B26_eliminant := sorry

/-- Back-substitution: a1 in terms of a4. -/
def B26_a1 (a4 : QQ) (h : a4 ≠ 0) : QQ :=
  (3 * a4^5 + 13078) / (362 * a4)

/-- Back-substitution: a2 in terms of a4. -/
def B26_a2 (a4 : QQ) (h : a4 ≠ 0) : QQ :=
  3 * (5 * a4^5 + 10816) / (181 * a4^2)

/-- Back-substitution: a3 in terms of a4. -/
def B26_a3 (a4 : QQ) (h : a4 ≠ 0) : QQ :=
  7 * (123 * a4^5 + 70304) / (2172 * a4^3)

/-- The linear system determinant: 30408*a4^3 ≠ 0 when a4 ≠ 0. -/
theorem B26_det_ne_zero (a4 : QQ) (h : a4 ≠ 0) : 30408 * a4^3 ≠ 0 := by
  apply mul_ne_zero
  · norm_num
  · apply pow_ne_zero 3 h

-- Main theorem (to be completed): the back-substitution gives all solutions.
-- theorem B26_complete (a1 a2 a3 a4 : QQ) (h4 : a4 ≠ 0)
--     (hT : B26_eliminant.eval a4 = 0) :
--     a1 = B26_a1 a4 h4 ∧ a2 = B26_a2 a4 h4 ∧ a3 = B26_a3 a4 h4 := sorry
