import Jacobian.B26.Defs
import Jacobian.B26.M5Rel1
import Jacobian.B26.M5Rel2
import Jacobian.B26.M5Rel3
import Jacobian.B26.M5Res0
import Jacobian.B26.M5Res1
import Jacobian.B26.M5Res2
import Jacobian.B26.M5Res3
import Jacobian.B26.M5T

/-!
# The `m = 3` and `m = 5` top-layer chart systems (B2.6), classified in characteristic 0

Generated by `gen_b26_lean.py` (repository `scripts/b26_m5_eliminant/lean_certificates/`).  This file replaces the
2026-10-05 skeleton `B26.lean`, whose statements were over `ℚ`, where the eliminant has no root, so they would have
been vacuous; it also did not compile (`QQ` is not a Mathlib name).

The top-layer equation `E₅` of the paper (eq. `e5`) is `α β + u (2 α β' - 3 α' β) = 1` with `deg α = m`,
`deg β = n = (3m - 1)/2`.  In the chart `α₀ = α_m = 1`, `β₀ = 1` (paper, proof of Proposition `prop:top-class`)
write `α = 1 + a₁ u + ⋯ + a_{m-1} u^{m-1} + u^m` and `β = 1 + b₁ u + ⋯ + b_n u^n`.  The coefficient of `u^N` is
`E_N = Σ_{i+k=N} (1 + 2k - 3i) α_i β_k`; `E₀ = 1` holds automatically, and `m5Chart`/`m3Chart` below are the
equations `E_N = 0` for `N = 1, …, n + m` (the last one is identically zero because `1 + 2n - 3m = 0`).

Main results, over any field `L` of characteristic 0:
* `m5_chart_iff`: the `m = 5` chart system holds iff `T₅(a₄) = 0`, `a₁, a₂, a₃` are the explicit functions of `a₄`
  (`362 a₄ a₁ = 3 a₄⁵ + 13078`, `181 a₄² a₂ = 15 a₄⁵ + 32448`, `2172 a₄³ a₃ = 861 a₄⁵ + 492128`), and
  `b₁, …, b₇` are the explicit polynomials `m5B1 … m5B7` in `a₁, …, a₄`.
* `m5_residual_iff`: CAIC's residuals `r₀, …, r₃` (`r_k = 3003 · E_{8+k}` once `β` is eliminated) cut out exactly
  the same set as `T₅(a₄)` and the three back-substitution relations (an equality of ideals, both inclusions
  certified).
* `m5_T_ne_zero_at_zero`, `m5_a4_ne_zero`, `m5_T_squarefree`: `T₅(0) ≠ 0`, so `a₄ ≠ 0`; `T₅` and `T₅'` have no
  common root.  Hence over an algebraically closed field the chart system has exactly `10` solutions, one for each
  of the `10` distinct roots of `T₅`. The count is this bijection plus `deg T₅ = 10`; it is proved as
  `m5_chart_card` (and `m3_chart_card` for `m = 3`) in `Jacobian/B26Count.lean`.
* the same for `m = 3` with `T₃(a₂) = 3 a₂³ - 32` and `8 a₁ = 5 a₂²` (`m3_chart_iff`, `m3_residual_iff`,
  `m3_a2_ne_zero`, `m3_T_squarefree`).
The irreducibility of `T₅` and `T₃` over `ℚ` is not used here; it is proved as `T5poly_irreducible` and
`T3poly_irreducible` in `Jacobian/B26Irred.lean`.
-/

set_option maxHeartbeats 0
set_option linter.unusedVariables false

namespace BranchAb.TopLayerSmall

variable {L : Type*} [Field L] [CharZero L]

/-- The four residuals cut out exactly `T₅(a₄) = 0` plus the back-substitution relations (ideal equality). -/
theorem m5_residual_iff (a1 a2 a3 a4 : L) :
    (m5r0 a1 a2 a3 a4 = 0 ∧ m5r1 a1 a2 a3 a4 = 0 ∧ m5r2 a1 a2 a3 a4 = 0 ∧ m5r3 a1 a2 a3 a4 = 0) ↔
    (m5T a4 = 0 ∧ 362 * a4 * a1 = 3 * a4^5 + 13078 ∧ 181 * a4^2 * a2 = 15 * a4^5 + 32448 ∧
      2172 * a4^3 * a3 = 861 * a4^5 + 492128) := by
  constructor
  · rintro ⟨h0, h1, h2, h3⟩
    exact ⟨m5_T_of_residuals a1 a2 a3 a4 h0 h1 h2 h3, m5_rel1_of_residuals a1 a2 a3 a4 h0 h1 h2 h3,
      m5_rel2_of_residuals a1 a2 a3 a4 h0 h1 h2 h3, m5_rel3_of_residuals a1 a2 a3 a4 h0 h1 h2 h3⟩
  · rintro ⟨hT, h1, h2, h3⟩
    exact ⟨m5_residual0_of_solution a1 a2 a3 a4 hT h1 h2 h3, m5_residual1_of_solution a1 a2 a3 a4 hT h1 h2 h3,
      m5_residual2_of_solution a1 a2 a3 a4 hT h1 h2 h3, m5_residual3_of_solution a1 a2 a3 a4 hT h1 h2 h3⟩

/-- **`m = 5` classification.**  The chart system holds iff `T₅(a₄) = 0`, `a₁, a₂, a₃` satisfy the three
back-substitution relations, and `b₁, …, b₇` are the polynomials `m5B1, …, m5B7` in `a₁, …, a₄`. -/
theorem m5_chart_iff (a1 a2 a3 a4 b1 b2 b3 b4 b5 b6 b7 : L) :
    m5Chart a1 a2 a3 a4 b1 b2 b3 b4 b5 b6 b7 ↔
    (m5T a4 = 0 ∧ 362 * a4 * a1 = 3 * a4^5 + 13078 ∧ 181 * a4^2 * a2 = 15 * a4^5 + 32448 ∧
      2172 * a4^3 * a3 = 861 * a4^5 + 492128 ∧ b1 = m5B1 a1 a2 a3 a4 ∧ b2 = m5B2 a1 a2 a3 a4 ∧ b3 = m5B3 a1 a2 a3 a4 ∧ b4 = m5B4 a1 a2 a3 a4 ∧ b5 = m5B5 a1 a2 a3 a4 ∧ b6 = m5B6 a1 a2 a3 a4 ∧ b7 = m5B7 a1 a2 a3 a4) := by
  constructor
  · rintro ⟨e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12⟩
    have hb1 : b1 = (2/3) * a1 := by linear_combination (1/3) * e1
    subst b1
    have hb2 : b2 = a2 := by linear_combination (1/5) * e2
    subst b2
    have hb3 : b3 = (8/7) * a3 := by linear_combination (1/7) * e3
    subst b3
    have hb4 : b4 = (-4/63) * a1 * a3 + (1/9) * a2^2 + (11/9) * a4 := by linear_combination (1/9) * e4
    subst b4
    have hb5 : b5 = (8/231) * a1^2 * a3 + (-2/33) * a1 * a2^2 + (-4/33) * a1 * a4 + (20/77) * a2 * a3 + (14/11) := by linear_combination (1/11) * e5
    subst b5
    have hb6 : b6 = (-64/3003) * a1^3 * a3 + (16/429) * a1^2 * a2^2 + (32/429) * a1^2 * a4 + (-436/3003) * a1 * a2 * a3 + (-24/143) * a1 + (-1/39) * a2^3 + (10/39) * a2 * a4 + (16/91) * a3^2 := by linear_combination (1/13) * e6
    subst b6
    have hb7 : b7 = (128/9009) * a1^4 * a3 + (-32/1287) * a1^3 * a2^2 + (-64/1287) * a1^3 * a4 + (256/3003) * a1^2 * a2 * a3 + (16/143) * a1^2 + (16/429) * a1 * a2^3 + (-56/429) * a1 * a2 * a4 + (-32/273) * a1 * a3^2 + (-20/231) * a2^2 * a3 + (8/33) * a2 + (8/21) * a3 * a4 := by linear_combination (1/15) * e7
    subst b7
    have hr := (m5_residual_iff a1 a2 a3 a4).mp ⟨by unfold m5r0; linear_combination 3003 * e8, by unfold m5r1; linear_combination 3003 * e9, by unfold m5r2; linear_combination 3003 * e10, by unfold m5r3; linear_combination 3003 * e11⟩
    exact ⟨hr.1, hr.2.1, hr.2.2.1, hr.2.2.2, by unfold m5B1; ring, by unfold m5B2; ring, by unfold m5B3; ring, by unfold m5B4; ring, by unfold m5B5; ring, by unfold m5B6; ring, by unfold m5B7; ring⟩
  · rintro ⟨hT, h1, h2, h3, hb1, hb2, hb3, hb4, hb5, hb6, hb7⟩
    subst b1 b2 b3 b4 b5 b6 b7
    obtain ⟨r0, r1, r2, r3⟩ := (m5_residual_iff a1 a2 a3 a4).mpr ⟨hT, h1, h2, h3⟩
    unfold m5Chart m5B1 m5B2 m5B3 m5B4 m5B5 m5B6 m5B7
    unfold m5r0 at r0
    unfold m5r1 at r1
    unfold m5r2 at r2
    unfold m5r3 at r3
    refine ⟨by ring, by ring, by ring, by ring, by ring, by ring, by ring, by linear_combination (1/3003 : L) * r0, by linear_combination (1/3003 : L) * r1, by linear_combination (1/3003 : L) * r2, by linear_combination (1/3003 : L) * r3, by ring⟩

theorem m5_T_ne_zero_at_zero : m5T (0 : L) ≠ 0 := by
  unfold m5T; norm_num

theorem m5_a4_ne_zero (a4 : L) (h : m5T a4 = 0) : a4 ≠ 0 := by
  rintro rfl; exact m5_T_ne_zero_at_zero h

/-- `T₅` and `T₅' = 90 x⁹ + 186000 x⁴` have no common root (Bezout identity `u T₅ + v T₅' = 1`), so `T₅` is
squarefree: over an algebraically closed field it has `10` distinct roots. -/
theorem m5_T_squarefree (x : L) (h : m5T x = 0) : 90 * x^9 + 186000 * x^4 ≠ 0 := by
  intro h'
  unfold m5T at h
  have : (1 : L) = 0 := by
    linear_combination ((-775/224205557262336) * x^5 + (1/95051008)) * h + ((155/448411114524672) * x^6 + (-141961/420385419866880) * x) * h'
  exact one_ne_zero this

/-- The explicit solution: `a₁, a₂, a₃` as rational functions of the root `a₄` of `T₅`. -/
theorem m5_solution_formulas (a1 a2 a3 a4 : L) (hT : m5T a4 = 0) (h1 : 362 * a4 * a1 = 3 * a4^5 + 13078)
    (h2 : 181 * a4^2 * a2 = 15 * a4^5 + 32448) (h3 : 2172 * a4^3 * a3 = 861 * a4^5 + 492128) :
    a1 = (3 * a4^5 + 13078) / (362 * a4) ∧ a2 = 3 * (5 * a4^5 + 10816) / (181 * a4^2) ∧
      a3 = 7 * (123 * a4^5 + 70304) / (2172 * a4^3) := by
  have ha : a4 ≠ 0 := m5_a4_ne_zero a4 hT
  refine ⟨?_, ?_, ?_⟩
  · rw [eq_div_iff (mul_ne_zero (by norm_num) ha)]; linear_combination h1
  · rw [eq_div_iff (mul_ne_zero (by norm_num) (pow_ne_zero 2 ha))]; linear_combination h2
  · rw [eq_div_iff (mul_ne_zero (by norm_num) (pow_ne_zero 3 ha))]; linear_combination h3

theorem m3_residual_iff (a1 a2 : L) :
    (m3s0 a1 a2 = 0 ∧ m3s1 a1 a2 = 0) ↔ (m3T a2 = 0 ∧ 8 * a1 = 5 * a2^2) := by
  unfold m3s0 m3s1 m3T
  constructor
  · rintro ⟨h0, h1⟩
    exact ⟨by linear_combination ((1/18) * a2^2) * h0 + ((-1/18) * a1 * a2 + (2/3)) * h1, by linear_combination ((1/6) * a2) * h0 + ((-1/6) * a1) * h1⟩
  · rintro ⟨hT, h1⟩
    exact ⟨by linear_combination ((15/16) * a2) * hT + ((-1/2) * a1 + (9/16) * a2^2) * h1, by linear_combination ((3/2)) * hT + ((-1/2) * a2) * h1⟩

/-- **`m = 3` classification.**  The chart system holds iff `T₃(a₂) = 0`, `8 a₁ = 5 a₂²` and `b₁, …, b₄` are
the polynomials `m3B1, …, m3B4` in `a₁, a₂`. -/
theorem m3_chart_iff (a1 a2 b1 b2 b3 b4 : L) :
    m3Chart a1 a2 b1 b2 b3 b4 ↔
    (m3T a2 = 0 ∧ 8 * a1 = 5 * a2^2 ∧ b1 = m3B1 a1 a2 ∧ b2 = m3B2 a1 a2 ∧ b3 = m3B3 a1 a2 ∧ b4 = m3B4 a1 a2) := by
  constructor
  · rintro ⟨e1, e2, e3, e4, e5, e6, e7⟩
    have hb1 : b1 = (2/3) * a1 := by linear_combination (1/3) * e1
    subst b1
    have hb2 : b2 = a2 := by linear_combination (1/5) * e2
    subst b2
    have hb3 : b3 = (8/7) := by linear_combination (1/7) * e3
    subst b3
    have hb4 : b4 = (-4/63) * a1 + (1/9) * a2^2 := by linear_combination (1/9) * e4
    subst b4
    have hr := (m3_residual_iff a1 a2).mp ⟨by unfold m3s0; linear_combination (21/2 : L) * e5,
      by unfold m3s1; linear_combination 21 * e6⟩
    exact ⟨hr.1, hr.2, by unfold m3B1; ring, by unfold m3B2; ring, by unfold m3B3; ring, by unfold m3B4; ring⟩
  · rintro ⟨hT, h1, hb1, hb2, hb3, hb4⟩
    subst b1 b2 b3 b4
    obtain ⟨r0, r1⟩ := (m3_residual_iff a1 a2).mpr ⟨hT, h1⟩
    unfold m3Chart m3B1 m3B2 m3B3 m3B4
    unfold m3s0 at r0
    unfold m3s1 at r1
    refine ⟨by ring, by ring, by ring, by ring, by linear_combination (2/21 : L) * r0, by linear_combination (1/21 : L) * r1, by ring⟩

theorem m3_a2_ne_zero (a2 : L) (h : m3T a2 = 0) : a2 ≠ 0 := by
  rintro rfl; unfold m3T at h; norm_num at h

/-- `T₃ = 3x³ - 32` and `T₃' = 9x²` have no common root: `(-1/32) T₃ + (x/96) T₃' = 1`. -/
theorem m3_T_squarefree (x : L) (h : m3T x = 0) : 9 * x^2 ≠ 0 := by
  intro h'
  unfold m3T at h
  have : (1 : L) = 0 := by linear_combination (-1/32 : L) * h + (x/96) * h'
  exact one_ne_zero this

end BranchAb.TopLayerSmall
